### ISSUE TITLE
clang-format "BraceWrapping.AfterControlStatement: Always" causes break before "break"

### ISSUE THREAD

**Issue by detly** [llvm/llvm-project#102268]
Consider this source:

```c
int do_thing(int magic)
{
    switch (magic)
    {
        case 0:
        {
            if (0)
            {
                return 0;
            }
            else
            {
                return 1;
            }
        } break;
    }

    return 0;
}
```

...and this `.clang-format`:

```yaml
BasedOnStyle: WebKit
Language: Cpp

BreakBeforeBraces: Custom
BraceWrapping:
  AfterCaseLabel: true
  AfterControlStatement: Always
  AfterFunction: true
  BeforeElse: true

IndentCaseLabels: true
IndentCaseBlocks: false
```

Running `clang-format` puts the `break` on a new line:

```c
int do_thing(int magic)
{
    switch (magic)
    {
        case 0:
        {
            if (0)
            {
                return 0;
            }
            else
            {
                return 1;
            }
        }
        break;
    }

    return 0;
}
```

If, on the other hand, I remove the `AfterControlStatement: Always` option, the `break` stays where it is, but the braces after the `if` statements are now put on the same line as the `if`:

```c
int do_thing(int magic)
{
    switch (magic) {
        case 0:
        {
            if (0) {
                return 0;
            }
            else {
                return 1;
            }
        } break;
    }

    return 0;
}
```

This is confusing to me, because I would expect it to not affect a brace _before_ the `break` control statement, since it only concerns breaking _after_ control statements. There seems to be no combination of `BraceWrapping` options that preserves the original code.

Tested with `clang-format` 18 and 19, on Ubuntu 24.04.
