### ISSUE TITLE
[mlir][doc] Adds a `\n` if description string not end with `\n`.

### ISSUE THREAD

**Issue by CoTinker** [llvm/llvm-project#112672]
The `mlir-linalg-ods-yaml-gen` tool converts description to a single-line string in tblgen file.
For example:
```yaml
metadata: !LinalgOpMetadata
  name: abs
  cpp_class_name: AbsOp
  doc: |-
    Applies abs(x) elementwise.

    No numeric casting is performed on the input operand.
```
is converted to
```tblgen
let description = [{No numeric casting is performed on the input operand.}];
```
In this case, the string of description is `"No numeric casting is performed on the input operand."`, without a trailing newline(`\n`). This causes the  `Traits` section to appear on the same line as the end of description in the generated markdown, as seen here  https://mlir.llvm.org/docs/Dialects/Linalg/#linalgabs-linalgabsop.
![image](https://github.com/user-attachments/assets/db1d17af-c770-4d43-b6d9-49f3dc226659)

Generially, we define `description` as a multi-line string in tblgen. Such as:
```tblgen
let description = [{
  No numeric casting is performed on the input operand.
}];
```
In this case, the string becomes `"\n  No numeric casting is performed on the input operand.\n"`, end with `\n`, which ensures that `Traits` starts on a new line after the description.

To fix this, we should append a newline (`\n`) if the description string doesn’t already end with one.
