### ISSUE TITLE
clang-format: Inconsistent macro formatting with num literal 

### ISSUE THREAD

**Issue by MaJerle** [llvm/llvm-project#113807]
I've noticed that depending on the parenthesis and type of variable (versus literal number) used in the macro, the formatting won't be always the same.

I often use macro like:

```c
//Get lower 10-bits only
#define MY_MACRO(num)  ((num) & 0x3FFUL)
```

Which will be formatted as
```c
#define MY_MACRO(num)  ((num)&0x3FFUL)
```

I've put together few examples below. It seems that clang-format will put the spaces between ampersand in most of the cases, but not in the case when:

- there are parenthesis in the full macro scope (outer parenthesis). If you don't have them, then space is added. Not having them is generally bad, but that's beyond the point here IMO.
- there is a variable without its own parenthesis

```c
#define MY_MACRO(flag) (config) & 0x1234 // No outer parenthesis
#define MY_MACRO(flag) ((config)&0x1234) // <- see here
#define MY_MACRO(flag) (config) & (0x1234)
#define MY_MACRO(flag) ((config) & (0x1234))
#define MY_MACRO(flag) (config) & flag
#define MY_MACRO(flag) ((config)&flag) // <- see here
#define MY_MACRO(flag) (config) & (flag)
#define MY_MACRO(flag) ((config) & (flag))
#define MY_MACRO(flag) ((config)->var & 0x1234)
#define MY_MACRO(flag) ((config)->var & (0x1234))
#define MY_MACRO(flag) ((config)->var & flag)
#define MY_MACRO(flag) ((config)->var & (flag))
#define MY_MACRO(flag) ((config).var & 0x1234)
#define MY_MACRO(flag) ((config).var & (0x1234))
#define MY_MACRO(flag) ((config).var & flag)
#define MY_MACRO(flag) ((config).var & (flag))
#define MY_MACRO(flag) (config & 0x1234)
#define MY_MACRO(flag) (config & (0x1234))
#define MY_MACRO(flag) (config & flag)
#define MY_MACRO(flag) (config & (flag))
#define MY_MACRO(flag) (config->var & 0x1234)
#define MY_MACRO(flag) (config->var & (0x1234))
#define MY_MACRO(flag) (config->var & flag)
#define MY_MACRO(flag) (config->var & (flag))
#define MY_MACRO(flag) (config.var & 0x1234)
#define MY_MACRO(flag) (config.var & (0x1234))
#define MY_MACRO(flag) (config.var & flag)
#define MY_MACRO(flag) (config.var & (flag))
```

Expectation

```c
#define MY_MACRO(flag) (config) & 0x1234
#define MY_MACRO(flag) ((config) & 0x1234) // <- see here, with spaces
#define MY_MACRO(flag) (config) & (0x1234)
#define MY_MACRO(flag) ((config) & (0x1234))
#define MY_MACRO(flag) (config) & flag
#define MY_MACRO(flag) ((config) & flag) // <- see here, with spaces
#define MY_MACRO(flag) (config) & (flag)
#define MY_MACRO(flag) ((config) & (flag))
#define MY_MACRO(flag) ((config)->var & 0x1234)
#define MY_MACRO(flag) ((config)->var & (0x1234))
#define MY_MACRO(flag) ((config)->var & flag)
#define MY_MACRO(flag) ((config)->var & (flag))
#define MY_MACRO(flag) ((config).var & 0x1234)
#define MY_MACRO(flag) ((config).var & (0x1234))
#define MY_MACRO(flag) ((config).var & flag)
#define MY_MACRO(flag) ((config).var & (flag))
#define MY_MACRO(flag) (config & 0x1234)
#define MY_MACRO(flag) (config & (0x1234))
#define MY_MACRO(flag) (config & flag)
#define MY_MACRO(flag) (config & (flag))
#define MY_MACRO(flag) (config->var & 0x1234)
#define MY_MACRO(flag) (config->var & (0x1234))
#define MY_MACRO(flag) (config->var & flag)
#define MY_MACRO(flag) (config->var & (flag))
#define MY_MACRO(flag) (config.var & 0x1234)
#define MY_MACRO(flag) (config.var & (0x1234))
#define MY_MACRO(flag) (config.var & flag)
#define MY_MACRO(flag) (config.var & (flag))
```

My full format file

```
---
Language: Cpp
# BasedOnStyle:  LLVM
AccessModifierOffset: -2
AlignAfterOpenBracket: Align
AlignArrayOfStructures: None
AlignConsecutiveMacros:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: true
AlignConsecutiveAssignments: None
AlignConsecutiveBitFields:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: true
AlignConsecutiveDeclarations: None
AlignEscapedNewlines: Right
AlignOperands: Align
SortIncludes: true
InsertBraces: true # Control statements must have curly brackets
AlignTrailingComments: true
AllowAllArgumentsOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortEnumsOnASingleLine: true
AllowShortBlocksOnASingleLine: Empty
AllowShortCaseLabelsOnASingleLine: true
AllowShortFunctionsOnASingleLine: All
AllowShortLambdasOnASingleLine: All
AllowShortIfStatementsOnASingleLine: Never
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: AllDefinitions
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: Yes
AttributeMacros:
  - __capability
BinPackArguments: true
BinPackParameters: true
BraceWrapping:
  AfterCaseLabel: false
  AfterClass: false
  AfterControlStatement: Never
  AfterEnum: false
  AfterFunction: false
  AfterNamespace: false
  AfterObjCDeclaration: false
  AfterStruct: false
  AfterUnion: false
  AfterExternBlock: false
  BeforeCatch: false
  BeforeElse: false
  BeforeLambdaBody: false
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: true
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeConceptDeclarations: true
BreakBeforeBraces: Attach
BreakBeforeInheritanceComma: false
BreakInheritanceList: BeforeColon
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
BreakConstructorInitializers: BeforeColon
BreakAfterJavaFieldAnnotations: false
BreakStringLiterals: true
ColumnLimit: 120
CommentPragmas: "^ IWYU pragma:"
QualifierAlignment: Leave
CompactNamespaces: false
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DeriveLineEnding: true
DerivePointerAlignment: false
DisableFormat: false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: LogicalBlock
ExperimentalAutoDetectBinPacking: false
PackConstructorInitializers: BinPack
BasedOnStyle: ""
ConstructorInitializerAllOnOneLineOrOnePerLine: false
AllowAllConstructorInitializersOnNextLine: true
FixNamespaceComments: true
ForEachMacros:
  - foreach
  - Q_FOREACH
  - BOOST_FOREACH
IfMacros:
  - KJ_IF_MAYBE
IncludeBlocks: Preserve
IncludeCategories:
  - Regex: "^<(.*)>"
    Priority: 0
  - Regex: '^"(.*)"'
    Priority: 1
  - Regex: "(.*)"
    Priority: 2
IncludeIsMainRegex: "(Test)?$"
IncludeIsMainSourceRegex: ""
IndentAccessModifiers: false
IndentCaseLabels: true
IndentCaseBlocks: false
IndentGotoLabels: true
IndentPPDirectives: None
IndentExternBlock: AfterExternBlock
IndentRequires: true
IndentWidth: 4
IndentWrappedFunctionNames: false
InsertTrailingCommas: None
JavaScriptQuotes: Leave
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: true
LambdaBodyIndentation: Signature
MacroBlockBegin: ""
MacroBlockEnd: ""
MaxEmptyLinesToKeep: 1
NamespaceIndentation: None
ObjCBinPackProtocolList: Auto
ObjCBlockIndentWidth: 2
ObjCBreakBeforeNestedBlockParam: true
ObjCSpaceAfterProperty: false
ObjCSpaceBeforeProtocolList: true
PenaltyBreakAssignment: 50
PenaltyBreakBeforeFirstCallParameter: 9
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakOpenParenthesis: 0
PenaltyBreakString: 1000
PenaltyBreakTemplateDeclaration: 10
PenaltyExcessCharacter: 1000000
PenaltyReturnTypeOnItsOwnLine: 60
PenaltyIndentedWhitespace: 0
PointerAlignment: Left
PPIndentWidth: -1
ReferenceAlignment: Pointer
ReflowComments: false
RemoveBracesLLVM: false
SeparateDefinitionBlocks: Always
ShortNamespaceLines: 1
SortJavaStaticImport: Before
SortUsingDeclarations: true
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeParens: ControlStatements
SpaceBeforeParensOptions:
  AfterControlStatements: true
  AfterForeachMacros: true
  AfterFunctionDefinitionName: false
  AfterFunctionDeclarationName: false
  AfterIfMacros: true
  AfterOverloadedOperator: false
  BeforeNonEmptyParentheses: false
SpaceAroundPointerQualifiers: Default
SpaceBeforeRangeBasedForLoopColon: true
SpaceInEmptyBlock: false
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: Never
SpacesInConditionalStatement: false
SpacesInContainerLiterals: true
SpacesInCStyleCastParentheses: false
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: -1
SpacesInParentheses: false
SpacesInSquareBrackets: false
SpaceBeforeSquareBrackets: false
BitFieldColonSpacing: Both
Standard: Latest
StatementAttributeLikeMacros:
  - Q_EMIT
StatementMacros:
  - Q_UNUSED
  - QT_REQUIRE_VERSION
TabWidth: 8
UseCRLF: false
UseTab: Never
WhitespaceSensitiveMacros:
  - STRINGIZE
  - PP_STRINGIZE
  - BOOST_PP_STRINGIZE
  - NS_SWIFT_NAME
  - CF_SWIFT_NAME
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
---
```
