### ISSUE TITLE
[llvm] - Stack dump without symbol names

### ISSUE THREAD

**Issue by eredotpkfr** [llvm/llvm-project#115488]
I have following github action workflow for my rust project, to get coverage of my tests I'm currently using `cargo-llvm-cov` package with rust nightly toolchain. 

```yml
jobs:
  cargo-llvm-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2

      - name: Generate code coverage
        run: |
          cargo +nightly llvm-cov \
          --all-features \
          --workspace \
          --doctests \
          --lcov \
          --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

```

Couple of my doctests are not compiling as expected and getting following error on my actions

```
error: aborting due to 1 previous error

Couldn't compile the test.
---- src/utilities/regex.rs - utilities::regex::generate_subdomain_regex (line 9) stdout ----
error: linking with `cc` failed: exit status: 1

  = note: PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
          Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
          0  libLLVM.so.19.1-rust-1.84.0-nightly 0x00007f90c7f4f637 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 39
          1  libLLVM.so.19.1-rust-1.84.0-nightly 0x00007f90c7f4fa4c
          2  libc.so.6                           0x00007f90c3c42520
          3  libc.so.6                           0x00007f90c3da07e5
          4  rust-lld                            0x00005647db2c0c08
          5  rust-lld                            0x00005647db30e7e3
          6  libLLVM.so.19.1-rust-1.84.0-nightly 0x00007f90c7f00f02
          7  libLLVM.so.19.1-rust-1.84.0-nightly 0x00007f90c7f002ba
          8  libLLVM.so.19.1-rust-1.84.0-nightly 0x00007f90c7e7b900
          9  libc.so.6                           0x00007f90c3c94ac3
          10 libc.so.6                           0x00007f90c3d26850
          collect2: fatal error: ld terminated with signal 7 [Bus error], core dumped
          compilation terminated.

```
I don't have any idea, just thinking that rust nightly version and llvm tools chains are not compatible. My versions are as following

```shell
$ cargo +nightly --version
cargo 1.84.0-nightly (cf53cc54b 2024-10-18)
$ cargo llvm-cov --version
cargo-llvm-cov 0.6.13
```
