### ISSUE TITLE
[libc] Annotate types in new hdrgen with standard

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#115960]
Unlike functions, types in new hdrgen don't currently include standard which means that the generated headers unconditionally include all types. This is a regression from old hdrgen where the generated headers only included types based on the selected standards.

**Comment by petrhosek** [comment]
Note that addressing this issue would likely require changing the YAML format since the type currently only includes a name:
```yaml
types:
  - type_name: struct_timeval
  - type_name: time_t
```
We would likely need to use a structure more akin to the one used for functions:
```yaml
types:
  - name: struct_timeval
    standard:
      - POSIX
  - name: time_t
    standard:
      - stdc
```
