### ISSUE TITLE
.clang-tidy (via clangd in VSCode) - any HungarianPrefix is not working properly for any pointer variable.

### ISSUE THREAD

**Issue by Khallington** [llvm/llvm-project#116818]
I'm only using ``.clang-tidy`` file via the ``clangd`` VSCode extension, simply just to verify naming styles and code formatting with ``.clang-format`` as well.

The main issue is with the ``.clang-tidy`` file. In that file I have the following:

``` yaml
... 

#ParameterCase
  - key:           'readability-identifier-naming.ParameterCase' 
    value:         'CamelCase'

#ParameterHungarianPrefix
  - key:           'readability-identifier-naming.ParameterHungarianPrefix' 
    value:         'LowerCase'

...
```
With this setting, any parameter should have the Hungarian Prefix with '_' and the CamelCase.

However, if a parameter is a pointer, the editor highlights the naming rule violation, I apply the fix, the editor renames the pointer correctly but it keeps highlighting the naming rule violation and suggesting a fix on a loop. This case happens for all pointer variables, be it global, local, etc.

Below are 4 screenshots showcasing this issue:

No fix, editor highlights the issue:
![vscode1](https://github.com/user-attachments/assets/df8c1eca-d0c0-4165-89cc-14f9aeaf76b5)

Suggested fix:
![vscode2](https://github.com/user-attachments/assets/35d36f37-bac4-45ff-a34b-5f80339e79da)

After the fix, the edito still highlights the issue:
![vscode3](https://github.com/user-attachments/assets/26bff535-a132-4787-87ac-6d3d4508c3bd)

Suggested fix:
![vscode4](https://github.com/user-attachments/assets/eee34550-9f8c-4d03-ab5e-d9cb140112fa)

... and so on

Is there a conflict with the HungaryPrefix property for pointers ?

I've also used the PointerParameter property but the problem still persists, but it seems like it's a general issue on pointers.

Thank you.
