### ISSUE TITLE
[ClangFormat] Adjusting Include Order for Main Headers by Prefix Match

### ISSUE THREAD

**Issue by thirumurugan-git** [llvm/llvm-project#118002]
Does the `IncludeIsMainRegex` option in the Clang format file only search for the suffix in the header stem? Is there an option to check the header prefix to identify it as "not a main file"? For example, consider the following code:

```cpp
// file: a.cc
#include "b.h"
#include "../a.h"

// some code
```

When formatting this, `a.h` is prioritized as `0` (default) and always appears first. However, I want it to be placed last. Does Clang-Format support any option in the `.clang-format` file to address this, or would I need to use `clang-off` for the include section? 

**Note:** The include must retain the relative path. Alternate approaches are not feasible. Could such an option be introduced in the future?"

**Comment by owenca** [comment]
You can insert an empty line between the two includes:
```
$ cat foo.cpp
// file: a.cc
#include "b.h"

#include "../a.h"

// some code
$ clang-format foo.cpp | diff foo.cpp -
$ 
```

**Comment by thirumurugan-git** [comment]
@owenca  Sorry for the delay. I have the following .clang-format configuration:

```yaml
IncludeBlocks: Regroup
IncludeCategories:
    - Regex:           '^<.*\.h>'
      Priority:        1
    - Regex:           '^<.*'
      Priority:        2
    - Regex:           '^[a-zA-Z].*'
      Priority:        3
    - Regex:           '\.\.\/.*'
      Priority:        4
```

I want to regroup all headers based on their priority, but I need the relative path headers to be placed in the last group. Is this possible? By default, headers with the same stem as the current file are assigned a priority of 0. However, with `IncludeBlocks: Regroup`, I can't seem to reorder the relative path headers to appear last in my case.
