### ISSUE TITLE
[clang-format] AlignOperands: DontAlign doesn't seem to affect ternary operators

### ISSUE THREAD

**Issue by DanielSWolf** [llvm/llvm-project#118950]
I'm using `clang-format` 19.1.0 and the following config file to format the following C++ code.

```yaml
AlignOperands: DontAlign
BreakBeforeBinaryOperators: NonAssignment
ColumnLimit: 80
```

```cpp
void test() {
  const auto c = "dddddddddddddddddd"
    ? "ffffffffffffffffffffffffffffffffff"
    : "ddddddddddddddddddddddddddd";
}
```

**Expected result:**

The file remains formatted as-is. The [documentation for AlignOperands](https://releases.llvm.org/19.1.0/tools/clang/docs/ClangFormatStyleOptions.html#alignoperands) says:

> `DontAlign`: Do not align operands of binary and ternary expressions. The wrapped lines are indented `ContinuationIndentWidth` spaces from the start of the line.

**Actual result:**

The `:` of the ternary operator gets aligned with the `?`, like this:

```cpp
void test() {
  const auto c = "dddddddddddddddddd" ? "ffffffffffffffffffffffffffffffffff"
                                      : "ddddddddddddddddddddddddddd";
}
```

**Comment by DanielSWolf** [comment]
I just stumbled across a different but possibly related case.

My goal is to only ever indent lines by four spaces; I never want their start to be aligned with some symbol from the line above. So the following config is meant to disable alignment altogether:

```yaml
BasedOnStyle: Chromium
AlignOperands: DontAlign
BreakBeforeBinaryOperators: NonAssignment
ColumnLimit: 100
IndentWidth: 4
```

However, this still results in the following formatted code, with the function arguments aligned with the opening parenthesis:

```cpp
void test() {
    const auto foo123 = someFunction("ddddddddddddddddddddddddddddddddddddd",
                                     "sssssssssssssssssssssssssssssssssssss",
                                     "fffffffffffffffffffffffffffffffffffff")
        + 1;
}
```

Is this a bug, or am I missing an option?
