### ISSUE TITLE
Misaligned formatting of array of objects with designated initializers

### ISSUE THREAD

**Issue by GlebMorgan** [llvm/llvm-project#119688]
Looks like Clang-format fails to properly format arrays of objects (tables) with long rows which don't fit onto a single line (according to set `ColumnLimit`).
```c
type_t table[] = {
    { .name = "foo", .description = "...", .value = 37, .type = TYPE_SOME, .arg = NULL },
    { .name = "bar", .description = "...", .value = 42, .type = TYPE_ANOTHER, .arg = NULL },
    ...
};
```

It works for simple cases, but starts to fail when line wrapping is required.
Below are some examples I discovered after playing around a bit.

### Current behavior
- Closing bracket of the 1st inner object is incorrectly indented
- 1st initializer of the 2nd inner object is over-indented
```c
some_struct_t test_1[] = {
    { .field_1 = some_long_expression(1),
     .field_2 = some_long_expression(2),
     .field_3 = some_long_expression(3),
     .field_4 = some_long_expression(4)                                           },
    {                       .field_1 = 1, .field_2 = 2, .field_3 = 3, .field_4 = 4 },
};
```

### Expected result
```
some_struct_t test_1[] = {
    { .field_1 = some_long_expression(1),
      .field_2 = some_long_expression(2),
      .field_3 = some_long_expression(3),
      .field_4 = some_long_expression(4) },
    { .field_1 = 1, .field_2 = 2, .field_3 = 3, .field_4 = 4 },
};
```

### Current behavior
- Closing bracket of the 1st inner object is incorrectly indented
- Last initializer of the 2nd inner object is over-indented
```c
some_struct_t test_2[] = {
    { .field_1 = 1,
     .field_2 = 2,
     .field_3 = 3,
     .field_4 = some_long_expression(4)                             },
    { .field_1 = 1, .field_2 = 2, .field_3 = 3,         .field_4 = 4 },
};
```

### Expected result
```
some_struct_t test_2[] = {
    { .field_1 = 1,
      .field_2 = 2,
      .field_3 = 3,
      .field_4 = some_long_expression(4) },
    { .field_1 = 1, .field_2 = 2, .field_3 = 3, .field_4 = 4 },
};
```

### Current behavior
- All initializers after the 1st one are under-indented by 1 space

> Note: no trailing comma after `some_long_expression(4)`
```c
some_struct_t test_3[] = {
    { .field_1 = some_long_expression(1),
     .field_2 = some_long_expression(2),
     .field_3 = some_long_expression(3),
     .field_4 = some_long_expression(4) },
    { .field_1 = some_long_expression(1),
     .field_2 = some_long_expression(2),
     .field_3 = some_long_expression(3),
     .field_4 = some_long_expression(4) },
};
```

### Expected result
```
some_struct_t test_3[] = {
    { .field_1 = some_long_expression(1),
      .field_2 = some_long_expression(2),
      .field_3 = some_long_expression(3),
      .field_4 = some_long_expression(4) },
    { .field_1 = some_long_expression(1),
      .field_2 = some_long_expression(2),
      .field_3 = some_long_expression(3),
      .field_4 = some_long_expression(4) },
};
```

### Current behavior
- Closing brackets of both inner objects are over-indented by 1 space
- Neither `BracedInitializerIndentWidth` or `ContinuationIndentWidth` are respected

> Note: trailing comma added after `some_long_expression(4)`
```c
some_struct_t test_4[] = {
    {
     .field_1 = some_long_expression(1),
     .field_2 = some_long_expression(2),
     .field_3 = some_long_expression(3),
     .field_4 = some_long_expression(4),
     },
    {
     .field_1 = some_long_expression(1),
     .field_2 = some_long_expression(2),
     .field_3 = some_long_expression(3),
     .field_4 = some_long_expression(4),
     },
};
```

### Expected result
```
some_struct_t test_4[] = {
    {
        .field_1 = some_long_expression(1),
        .field_2 = some_long_expression(2),
        .field_3 = some_long_expression(3),
        .field_4 = some_long_expression(4),
    },
    {
        .field_1 = some_long_expression(1),
        .field_2 = some_long_expression(2),
        .field_3 = some_long_expression(3),
        .field_4 = some_long_expression(4),
    },
};
```

---

It is possible that our `.clang-format` file is misconfigured somehow, please let me know if that is the case

The command used to format files:
```bash
clang-format -i --style=file test.c
```

Used `.clang-format` configuration:
```yaml
BasedOnStyle: LLVM
Language: Cpp
IndentWidth: 4
AlignAfterOpenBracket: Align
ColumnLimit: 80
AlignConsecutiveAssignments: None
AlignConsecutiveBitFields: Consecutive
AlignConsecutiveDeclarations: None
AlignConsecutiveMacros: Consecutive
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments: true
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Empty
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: Never
BinPackArguments: false
BinPackParameters: false
BreakBeforeBraces: Custom
BraceWrapping:
  AfterCaseLabel: false
  AfterControlStatement: Never
  AfterEnum: false
  AfterFunction: false
  AfterStruct: false
  AfterUnion: false
  BeforeElse: false
  BeforeWhile: false
BreakBeforeTernaryOperators: false
ContinuationIndentWidth: 4
PointerAlignment: Right
IndentCaseBlocks: false
IndentCaseLabels: true
IndentPPDirectives: AfterHash
KeepEmptyLinesAtTheStartOfBlocks: false
ReflowComments: true
SortIncludes: true
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceBeforeParens: ControlStatementsExceptControlMacros
SpacesBeforeTrailingComments: 4
Cpp11BracedListStyle: false
UseTab: Never
IndentWrappedFunctionNames: false
AlwaysBreakAfterDefinitionReturnType: None
PenaltyReturnTypeOnItsOwnLine: 160
```
