### ISSUE TITLE
Crash in clangd when running modernize-macro-to-enum clang-tidy checker

### ISSUE THREAD

**Issue by FrK5E** [llvm/llvm-project#127965]
Hi, 
I love llvm project, keep it up! Tried to build clangd from label llvmorg-20.1.0-rc2, got a crash in my codebase when running this clangd under vscode. 

```
clangd: /local/py467/code/llvm-project/clang-tools-extra/clang-tidy/modernize/MacroToEnumCheck.cpp:397: virtual void clang::tidy::modernize::MacroToEnumCallbacks::Endif(clang::SourceLocation, clang::SourceLocation): Assertion `CurrentFile->ConditionScopes > 0' failed.


backtrace: 

 #0 0x00000000005de4bb llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/local/py467/code/llvm-project/build/bin/clangd+0x5de4bb)
 #1 0x00000000005db68b llvm::sys::RunSignalHandlers() (/local/py467/code/llvm-project/build/bin/clangd+0x5db68b)
 #2 0x00000000005db7a9 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f9e0f48bd10 __restore_rt (/lib64/libpthread.so.0+0x12d10)
 #4 0x00007f9e0defa52f raise (/lib64/libc.so.6+0x4e52f)
 #5 0x00007f9e0decde65 abort (/lib64/libc.so.6+0x21e65)
 #6 0x00007f9e0decdd39 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21d39)
 #7 0x00007f9e0def2e86 (/lib64/libc.so.6+0x46e86)
 #8 0x000000000333a9d3 clang::tidy::modernize::MacroToEnumCallbacks::Endif(clang::SourceLocation, clang::SourceLocation) (/local/py467/code/llvm-project/build/bin/clangd+0x333a9d3)
 #9 0x0000000000e347c8 clang::PPChainedCallbacks::Endif(clang::SourceLocation, clang::SourceLocation) (/local/py467/code/llvm-project/build/bin/clangd+0xe347c8)
#10 0x0000000000db947e clang::Preprocessor::HandleDirective(clang::Token&) (/local/py467/code/llvm-project/build/bin/clangd+0xdb947e)
#11 0x0000000000d8c9aa clang::Lexer::LexTokenInternal(clang::Token&, bool) (/local/py467/code/llvm-project/build/bin/clangd+0xd8c9aa)
#12 0x0000000000d8ea8f clang::Lexer::Lex(clang::Token&) (/local/py467/code/llvm-project/build/bin/clangd+0xd8ea8f)
#13 0x0000000000df724c clang::Preprocessor::Lex(clang::Token&) (/local/py467/code/llvm-project/build/bin/clangd+0xdf724c)
#14 0x0000000003be44b6 clang::Parser::ConsumeBrace() (/local/py467/code/llvm-project/build/bin/clangd+0x3be44b6)
#15 0x0000000003bedf80 clang::BalancedDelimiterTracker::consumeClose() (/local/py467/code/llvm-project/build/bin/clangd+0x3bedf80)
#16 0x0000000003c48591 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (/local/py467/code/llvm-project/build/bin/clangd+0x3c48591)
#17 0x0000000003c2decc clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/local/py467/code/llvm-project/build/bin/clangd+0x3c2decc)
#18 0x0000000003bf0ee5 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/local/py467/code/llvm-project/build/bin/clangd+0x3bf0ee5)
#19 0x0000000003bf1d85 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/local/py467/code/llvm-project/build/bin/clangd+0x3bf1d85)
#20 0x0000000003be2cea clang::ParseAST(clang::Sema&, bool, bool) (/local/py467/code/llvm-project/build/bin/clangd+0x3be2cea)
#21 0x0000000003943423 clang::FrontendAction::Execute() (/local/py467/code/llvm-project/build/bin/clangd+0x3943423)
#22 0x0000000001c0c56a clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) (/local/py467/code/llvm-project/build/bin/clangd+0x1c0c56a)
#23 0x0000000001ca6f7a clang::clangd::(anonymous namespace)::ASTWorker::generateDiagnostics(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, clang::clangd::ParseInputs, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag>>) TUScheduler.cpp:0:0
#24 0x0000000001ca7af2 clang::clangd::(anonymous namespace)::ASTWorker::updatePreamble(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, clang::clangd::ParseInputs, std::shared_ptr<clang::clangd::PreambleData const>, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag>>, clang::clangd::WantDiagnostics)::'lambda'()::operator()() TUScheduler.cpp:0:0
#25 0x0000000001c9f6c2 clang::clangd::(anonymous namespace)::ASTWorker::runTask(llvm::StringRef, llvm::function_ref<void ()>) (.constprop.0) TUScheduler.cpp:0:0
#26 0x0000000001ca09c9 clang::clangd::(anonymous namespace)::ASTWorker::run() TUScheduler.cpp:0:0
#27 0x0000000001e80765 void* llvm::thread::ThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::'lambda0'()>>(void*) Threading.cpp:0:0
#28 0x00007f9e0f4811ca start_thread (/lib64/libpthread.so.0+0x81ca)
#29 0x00007f9e0dee58d3 clone (/lib64/libc.so.6+0x398d3)
```

`.clang-tidy`:

```yaml
---

Checks:          'clang-diagnostic-*,clang-analyzer-*,boost-*,bugprone-*,cppcoreguidelines-*,modernize-*,performance-*,readability-*'

WarningsAsErrors: ''

HeaderFileExtensions:
  - ''
  - h
  - hh
  - hpp
  - hxx

ImplementationFileExtensions:
  - c
  - cc
  - cpp
  - cxx

HeaderFilterRegex: ''
ExcludeHeaderFilterRegex: ''
SystemHeaders:   false

CheckOptions:
  cert-arr39-c.WarnOnSizeOfCompareToConstant: 'false'
  cert-arr39-c.WarnOnSizeOfConstant: 'false'
  cert-arr39-c.WarnOnSizeOfIntegerExpression: 'false'
  cert-arr39-c.WarnOnSizeOfPointer: 'false'
  cert-arr39-c.WarnOnSizeOfPointerToAggregate: 'false'
  cert-arr39-c.WarnOnSizeOfThis: 'false'

  cert-dcl16-c.NewSuffixes: 'L;LL;LU;LLU'

  cert-err33-c.AllowCastToVoid: 'true'
  cert-err33-c.CheckedFunctions: '^::aligned_alloc;^::asctime_s;^::at_quick_exit;^::atexit;^::bsearch;^::bsearch_s;^::btowc;^::c16rtomb;^::c32rtomb;^::calloc;^::clock;^::cnd_broadcast;^::cnd_init;^::cnd_signal;^::cnd_timedwait;^::cnd_wait;^::ctime_s;^::fclose;^::fflush;^::fgetc;^::fgetpos;^::fgets;^::fgetwc;^::fopen;^::fopen_s;^::fprintf;^::fprintf_s;^::fputc;^::fputs;^::fputwc;^::fputws;^::fread;^::freopen;^::freopen_s;^::fscanf;^::fscanf_s;^::fseek;^::fsetpos;^::ftell;^::fwprintf;^::fwprintf_s;^::fwrite;^::fwscanf;^::fwscanf_s;^::getc;^::getchar;^::getenv;^::getenv_s;^::gets_s;^::getwc;^::getwchar;^::gmtime;^::gmtime_s;^::localtime;^::localtime_s;^::malloc;^::mbrtoc16;^::mbrtoc32;^::mbsrtowcs;^::mbsrtowcs_s;^::mbstowcs;^::mbstowcs_s;^::memchr;^::mktime;^::mtx_init;^::mtx_lock;^::mtx_timedlock;^::mtx_trylock;^::mtx_unlock;^::printf_s;^::putc;^::putwc;^::raise;^::realloc;^::remove;^::rename;^::scanf;^::scanf_s;^::setlocale;^::setvbuf;^::signal;^::snprintf;^::snprintf_s;^::sprintf;^::sprintf_s;^::sscanf;^::sscanf_s;^::strchr;^::strerror_s;^::strftime;^::strpbrk;^::strrchr;^::strstr;^::strtod;^::strtof;^::strtoimax;^::strtok;^::strtok_s;^::strtol;^::strtold;^::strtoll;^::strtoul;^::strtoull;^::strtoumax;^::strxfrm;^::swprintf;^::swprintf_s;^::swscanf;^::swscanf_s;^::thrd_create;^::thrd_detach;^::thrd_join;^::thrd_sleep;^::time;^::timespec_get;^::tmpfile;^::tmpfile_s;^::tmpnam;^::tmpnam_s;^::tss_create;^::tss_get;^::tss_set;^::ungetc;^::ungetwc;^::vfprintf;^::vfprintf_s;^::vfscanf;^::vfscanf_s;^::vfwprintf;^::vfwprintf_s;^::vfwscanf;^::vfwscanf_s;^::vprintf_s;^::vscanf;^::vscanf_s;^::vsnprintf;^::vsnprintf_s;^::vsprintf;^::vsprintf_s;^::vsscanf;^::vsscanf_s;^::vswprintf;^::vswprintf_s;^::vswscanf;^::vswscanf_s;^::vwprintf_s;^::vwscanf;^::vwscanf_s;^::wcrtomb;^::wcschr;^::wcsftime;^::wcspbrk;^::wcsrchr;^::wcsrtombs;^::wcsrtombs_s;^::wcsstr;^::wcstod;^::wcstof;^::wcstoimax;^::wcstok;^::wcstok_s;^::wcstol;^::wcstold;^::wcstoll;^::wcstombs;^::wcstombs_s;^::wcstoul;^::wcstoull;^::wcstoumax;^::wcsxfrm;^::wctob;^::wctrans;^::wctype;^::wmemchr;^::wprintf_s;^::wscanf;^::wscanf_s;'

  cert-oop54-cpp.WarnOnlyIfThisHasSuspiciousField: 'false'

  cert-str34-c.DiagnoseSignedUnsignedCharComparisons: 'false'

  cppcoreguidelines-non-private-member-variables-in-classes.IgnoreClassesWithAllMemberVariablesBeingPublic: 'true'

  google-readability-braces-around-statements.ShortStatementLines: '1'

  google-readability-function-size.StatementThreshold: '800'

  google-readability-namespace-comments.ShortNamespaceLines: '10'
  google-readability-namespace-comments.SpacesBeforeComments: '2'

  llvm-else-after-return.WarnOnConditionVariables: 'false'
  llvm-else-after-return.WarnOnUnfixable: 'false'

  llvm-qualified-auto.AddConstToQualified: 'false'
...
```

**Comment by PiotrZSL** [comment]
Got some reproduction example ?

**Comment by EugeneZelenko** [comment]
Could you please try to run Clang-tidy standalone? Just to separate problems.

**Comment by HighCommander4** [comment]
The error occurs while running the `modernize-macro-to-enum` clang-tidy check.

As a workaround until the issue is resolved, you can disable this check for clangd using the following in `.clangd`:

```yaml
Diagnostics:
  ClangTidy:
    Remove: modernize-macro-to-enum
```
