### ISSUE TITLE
[flang-rt] Some CMake checks fail in flang-rt configure step

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#131008]
Just noticed this in the CMake log of the configuration checks when flang-rt is built via `-DLLVM_ENABLE_RUNTIMES="flang-rt"`:
```
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/local/share/cmake-3.28/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "/local/home/szakharin/lorado/src/llvm-project/flang-rt/CMakeLists.txt:58 (enable_language)"
...
      variable: "CMAKE_Fortran_ABI_COMPILED"
...
        ld.lld: error: unable to find library -lflang_rt.runtime
        flang-21: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.
...
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.28/Modules/CMakeTestFortranCompiler.cmake:75 (try_compile)"
      - "/local/home/szakharin/lorado/src/llvm-project/flang-rt/CMakeLists.txt:58 (enable_language)"
...
      variable: "CMAKE_Fortran_COMPILER_SUPPORTS_F90"
...
        ld.lld: error: unable to find library -lflang_rt.runtime
        flang-21: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.
```

The build seems to work with these checks failing, so I am not sure if we have to do anything here.  Opening this just for insights from other people.

@Meinersbur FYI
