### ISSUE TITLE
[clang-tidy] Invalid options reported by --dump-config

### ISSUE THREAD

**Issue by felix642** [llvm/llvm-project#137241]
Assuming the following .clang-tidy config file

````
---
Checks: readability-identifier-naming

CheckOptions:
  - key: readability-identifier-naming.TypedefSuffix
    value: '_t'
````

If I run the command `clang-tidy --dump-config <file.cpp>`
I will get the following output:
````
---
Checks:          'clang-diagnostic-*,clang-analyzer-*,readability-identifier-naming'
[...]
CheckOptions:
  [...]
  readability-identifier-naming.AggressiveDependentMemberLookup: 'false'
  readability-identifier-naming.CheckAnonFieldInParent: 'false'
  readability-identifier-naming.GetConfigPerFile: 'true'
  readability-identifier-naming.IgnoreFailedSplit: 'false'
  readability-identifier-naming.IgnoreMainLikeFunctions: 'false'
  readability-identifier-naming.TypedefHungarianPrefix: Off
  readability-identifier-naming.TypedefIgnoredRegexp: ''
  readability-identifier-naming.TypedefPrefix: ''
  readability-identifier-naming.TypedefSuffix: _t
SystemHeaders:   false
...
````

Now, I've trimmed the output of the command to keep the interesting part.
Notice that the config mentions the option `TypedefHungarianPrefix`, but this option is not recognised by clang-tidy and is not documented anywhere.
This leads me to think that this is an "internal" parameter and should not be part of the `--dump-config` output.
I've also noticed the same issue with the parameters `MacroDefinitionHungarianPrefix` and `TypeAliasHungarianPrefix`. There are probably more of those parameters, but I did not take the time to investigate.
