### ISSUE TITLE
[clang-tidy][bug] Why does the same config not produce the same effect for ClassCase and EnumConstant?

### ISSUE THREAD

**Issue by yaoxinliu** [llvm/llvm-project#140175]
Consider the .clang-tidy config snippet:

```
CheckOptions:
  - key: readability-identifier-naming.ClassCase  
    value: CamelCase
  
  - key: readability-identifier-naming.ClassIgnoredRegexp    
    value: '^[A-Za-z]+(_[a-zA-Z0-9]+)*_?$'

  - key: readability-identifier-naming.EnumConstantCase
    value: CamelCase
    
  - key: readability-identifier-naming.EnumConstantIgnoredRegexp
    value: '^[A-Za-z]+(_[a-zA-Z0-9]+)*_?$'
```
and the following main.cpp:

```
class Ab_Cd {}; // ok

enum class A : char {
    Ab_Cd // warning by clang-tidy
};

int main() {}
```
My clang-tidy version is 20.1.5.

Why does the same config not produce the same effect for ClassCase and EnumConstant?
