### ISSUE TITLE
[clang-format] const method quilifier is split on own line

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#142512]
Code snippet:

```
#include <string>

class Test
{
public:
    void some_method_name(const std::string& p1, const std::string& p2, const std::string& p3) const;
};

void Test::some_method_name(const std::string& p1, const std::string& p2, const std::string& p3) const
{
}
```

Expected output:

```
#include <string>

class Test
{
public:
    void some_method_name(
        const std::string& p1,
        const std::string& p2,
        const std::string& p3) const;
};

void Test::some_method_name(
    const std::string& p1,
    const std::string& p2,
    const std::string& p3) const
{
}
```

Configuration:

```
BasedOnStyle: LLVM

BreakBeforeBraces: Allman
ColumnLimit: 100
IndentPPDirectives: AfterHash
IndentWidth: 4
LineEnding: LF
UseTab: Never

Language: Cpp
AccessModifierOffset: -4
AlignAfterOpenBracket: AlwaysBreak
AlignArrayOfStructures: Left
AlignConsecutiveAssignments: AcrossComments
AlignConsecutiveBitFields:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: true
AlignConsecutiveDeclarations:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
AlignConsecutiveMacros: AcrossEmptyLines
AlignConsecutiveShortCaseStatements:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: true
  AlignCaseColons: false
AlignEscapedNewlines: LeftWithLastLine
AlignOperands: Align
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortCaseExpressionOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortCompoundRequirementOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: false
BitFieldColonSpacing: After
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeComma
BreakTemplateDeclarations: Yes
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 4
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: Always
FixNamespaceComments: true
Macros:
  - PyVarObject_HEAD_INIT(x, y)=x, y,
MainIncludeChar: Quote
MaxEmptyLinesToKeep: 1
PackConstructorInitializers: Never
PenaltyReturnTypeOnItsOwnLine: 1000
PointerAlignment: Left
SortUsingDeclarations: true
SpaceAfterTemplateKeyword: false
StatementMacros:
  - PyObject_HEAD
  - Q_OBJECT
```
