### ISSUE TITLE
Incorrect handling of nested brace blocks

### ISSUE THREAD

**Issue by 54aefcd4-c07d-4252-8441-723563c8826f** [llvm/llvm-project#26170]
|  |  |
| --- | --- |
| Bugzilla Link | [25796](https://llvm.org/bz25796) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Given:
```cpp
template<typename T, int N>
struct vector { 
  vector(std::initializer_list<int>) {}
};
```

The following:
```cpp
int main() {
  {
    {
       vector<int, 3> a = {1, 2, 3};
       vector<int, 3> b = {1, 2, 3};
    }
  }
  return 0;
}
```
Is wrongly indented to: 
```cpp
int main() {
  {{vector<int, 3> a = {1, 2, 3};
  vector<int, 3> b   = {1, 2, 3};
}
}
  return 0;
}
```
Using the configuration file (below).

It should probably be something like:
```cpp
int main() {
  {
    {
      vector<int, 3> a = {1, 2, 3};
      vector<int, 3> b = {1, 2, 3};
    }
  }
  return 0;
}
```
Configuration file:
```yaml
BasedOnStyle: Google
AccessModifierOffset: -1
AlignAfterOpenBracket: true
AlignConsecutiveAssignments: true
AlignEscapedNewlinesLeft: true
AlignOperands: true
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: true
AllowShortCaseLabelsOnASingleLine: true
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: true
AllowShortLoopsOnASingleLine: true
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: false
BinPackArguments: true
BinPackParameters: true
BreakBeforeBinaryOperators: true
BreakBeforeBraces: Attach
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: true
ColumnLimit: 80
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 1
ContinuationIndentWidth: 1
Cpp11BracedListStyle: true
DerivePointerBinding: false
ExperimentalAutoDetectBinPacking: false
ForEachMacros: ['RANGES_FOR', 'BOOST_FOREACH']
IndentCaseLabels: true
IndentFunctionDeclarationAfterType: true
IndentWidth: 2
IndentWrappedFunctionNames: true
KeepEmptyLinesAtTheStartOfBlocks: false
Language: Cpp
MaxEmptyLinesToKeep: 1
NamespaceIndentation: None
PenaltyBreakBeforeFirstCallParameter: 10
PointerAlignment: Left
SpaceAfterCStyleCast: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 2
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInAngles:  false
SpacesInSquareBrackets: false
Standard: Cpp11
TabWidth: 2
UseTab: Never
```
