### ISSUE TITLE
Need an option to leave a white space at the end of namespace block

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#28599]
|  |  |
| --- | --- |
| Bugzilla Link | [28225](https://llvm.org/bz28225) |
| Version | 3.8 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This code:

```
   namespace A {
   namespace B {

   void somefunc()
   {
   }

   }
   }
```

with the appropriate options (break before all braces except namespace braces, keep empty lines at start of block), ends up formatting like this:

```
   namespace A {
   namespace B {

   void somefunc()
   {
   }
   }
   }
```

which has a definite loss of readability. I can't find any options to put that white space back.

**Comment by mydeveloperday** [comment]
As of 2021.12.17  clang-format version 14.0.0 (https://github.com/llvm/llvm-project.git 55d392cc30fb36e6361ba71f4b568c093f8b23f3)

Using the following style will give you what you require and won't remove the extra line

```
BasedOnStyle: LLVM
BreakBeforeBraces: Custom
BraceWrapping:
    AfterFunction: true
    AfterControlStatement: Always
    AfterNamespace: false
    SplitEmptyFunction: true
    SplitEmptyRecord: true
AllowShortBlocksOnASingleLine: Never
AllowShortFunctionsOnASingleLine: None
```


```
namespace A {
namespace B {

void somefunc()
{
}

} // namespace B
} // namespace A
```
As this issue seems fixed I will close this issue, feel free to reopen if you are still experiencing issues.
