### ISSUE TITLE
[java] BraceWrapping: AfterFunction affects synchronized blocks

### ISSUE THREAD

**Issue by ed628777-e86e-4544-8e44-c6f20c9fc656** [llvm/llvm-project#32031]
|  |  |
| --- | --- |
| Bugzilla Link | [32684](https://llvm.org/bz32684) |
| Version | trunk |
| OS | Windows NT |

## Extended Description 
It seems that synchronized blocks in Java are affected by BraceWrapping's AfterFunction setting, rather than AfterControlStatement.

This config:

```
BreakBeforeBraces: Custom
BraceWrapping:
  AfterControlStatement: false
  AfterFunction: true
```

Results in this formatting:

```
class Foo {
  void bar()
  {
    synchronized (this)
    {
      System.out.println("");
      System.out.println("");
    }
  }
}
```

I would expect the { of the synchronized block to remain on the same line here.

clang-format version: 5.0.0 (1cd6beccb6bb876db3bbfa763e8979)
