### ISSUE TITLE
[clang-format] Failed to format nested blocks

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#33891]
|  |  |
| --- | --- |
| Bugzilla Link | [34543](https://llvm.org/bz34543) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
It works fine if there is only one nested block:
```cpp
int main()
{
    {
        {
            int a = 0;
        }
    }
}
```
But if we copy the code in the main function again, like this
```cpp
int main()
{
    {
        {
            int a = 0;
        }
    }
    {
        {
            int a = 0;
        }
    }
}
```
clang-format will format the code above like this:
```cpp
int main()
{
    {{int a = 0;
}
}
{
    {
        int a = 0;
    }
}
}
```
Configuration for clang-format is:
```yml
{
    Language: Cpp,
    BasedOnStyle: Google,

    DerivePointerAlignment: false,
    PointerAlignment: Left,

    BreakBeforeBraces: Allman,

    AlignOperands: true,
    AlignAfterOpenBracket: Align,

    AccessModifierOffset: -4,

    Cpp11BracedListStyle: true,
    NamespaceIndentation: None,
    UseTab: Never,
    TabWidth: 4,
    Standard: Cpp11,
    SpaceBeforeParens: ControlStatements,
    AlwaysBreakTemplateDeclarations: true,

    BinPackArguments: false,
    BinPackParameters: false,

    AlignAfterOpenBracket: true,
    AlignConsecutiveAssignments: true,
    IndentWidth: 4,
    ColumnLimit: 120,
    AllowShortFunctionsOnASingleLine: Inline,
    AllowShortBlocksOnASingleLine: false,

    BreakConstructorInitializersBeforeComma: true,
    BreakBeforeBinaryOperators: NonAssignment,
    BreakBeforeTernaryOperators: true,

    BreakStringLiterals: false,

    SortIncludes: true,
}
```
