### ISSUE TITLE
BreakBeforeBraces and AllowShortBlocksOnASingleLine interferrs with each other

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#34454]
|  |  |
| --- | --- |
| Bugzilla Link | [35106](https://llvm.org/bz35106) |
| Version | 5.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This works as expected:
```yaml
---
Language:        Cpp
BasedOnStyle: LLVM
AllowShortBlocksOnASingleLine: true
AllowShortLoopsOnASingleLine: true
...
```
```cpp
int code(std::vector<int> vec) {
  int count;
  for (auto &el : vec) count++;
  for (auto &el : vec) { count++; }
  for (auto &el : vec) {
    count++;
    break;
  }
}
```
This too:
```yaml
---
Language:        Cpp
BasedOnStyle: LLVM
AllowShortLoopsOnASingleLine: true
BreakBeforeBraces: Allman
...
```
```cpp
int code(std::vector<int> vec)
{
  int count;
  for (auto &el : vec) count++;
  for (auto &el : vec)
  {
    count++;
  }
  for (auto &el : vec)
  {
    count++;
    break;
  }
}
```
Combining these do not work:
```yaml
---
Language:        Cpp
BasedOnStyle: LLVM
AllowShortBlocksOnASingleLine: true
AllowShortLoopsOnASingleLine: true
BreakBeforeBraces: Allman
...
```
```cpp
int code(std::vector<int> vec)
{
  int count;
  for (auto &el : vec) count++;
  for (auto &el : vec) {
    count++;
  }
  for (auto &el : vec) {
    count++;
    break;
  }
}
```
Two errors:
1) All braces on ControlStatements are pulled up instead of following Allman.
2) 'ShortBlock's aren't made

Expected output:
```cpp
int code(std::vector<int> vec)
{
  int count;
  for (auto &el : vec) count++;
  for (auto &el : vec) { count++; }
  for (auto &el : vec)
  {
    count++;
    break;
  }
}
```
