### ISSUE TITLE
clang-format doesn't insert newlines consistently with noexcept specifier

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#44544]
|  |  |
| --- | --- |
| Bugzilla Link | [45199](https://llvm.org/bz45199) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
The following:

    template<typename T, typename U>
    class is_nothrow_swappable_with final :
        public bool_constant<
            is_detected<details::is_nothrow_swappable_with_type, T, U>::value &&
            is_detected<details::is_nothrow_swappable_with_type, U, T>::value &&
            noexcept(swap(declval<T>(), declval<U>())) &&
            noexcept(swap(declval<U>(), declval<T>()))>
    {};

Results in this:

    template<typename T, typename U>
    class is_nothrow_swappable_with final :
        public bool_constant<
            is_detected<details::is_nothrow_swappable_with_type, T, U>::value &&
            is_detected<details::is_nothrow_swappable_with_type, U, T>::value &&noexcept(
                swap(declval<T>(), declval<U>())) &&
            noexcept(swap(declval<U>(), declval<T>()))>
    {};

With this:

```
AccessModifierOffset: -4
AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Right
AlignOperands: true
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: false
AllowShortLambdasOnASingleLine: Empty
AllowShortLoopsOnASingleLine: false
# AlwaysBreakAfterDefinitionReturnType
AlwaysBreakAfterReturnType: AllDefinitions
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: Yes
BinPackArguments: false
BinPackParameters: false
BraceWrapping:
    AfterClass: true
    AfterControlStatement: false
    AfterEnum: true
    AfterFunction: true
    AfterNamespace: true
    # AfterObjCDeclaration
    AfterStruct: true
    AfterUnion: true
    AfterExternBlock: true
    BeforeCatch: true
    BeforeElse: true
    IndentBraces: false
    SplitEmptyFunction: false
    SplitEmptyRecord: false
    SplitEmptyNamespace: false
# BreakAfterJavaFieldAnnotations
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Custom
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeComma
BreakInheritanceList: AfterColon
BreakStringLiterals: true
ColumnLimit: 100
# CommentPragmas
CompactNamespaces: false
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DerivePointerAlignment: false
# DisableFormat
# ExperimentalAutoDetectBinPacking
FixNamespaceComments: false
# ForEachMacros
# IncludeBlocks
# IncludeCategories
# IncludeIsMainRegex
IndentCaseLabels: true
IndentPPDirectives: None
IndentWidth: 4
IndentWrappedFunctionNames: false
# JavaImportGroups
# JavaScriptQuotes
# JavaScriptWrapImports
KeepEmptyLinesAtTheStartOfBlocks: true
Language: Cpp
# MacroBlockBegin
# MacroBlockEnd
MaxEmptyLinesToKeep: 1
NamespaceIndentation: All
# ObjCBinPackProtocolList
# ObjCBlockIndentWidth
# ObjCSpaceAfterProperty
# ObjCSpaceBeforeProtocolList
# PenaltyBreakAssignment
# PenaltyBreakBeforeFirstCallParameter
# PenaltyBreakComment
# PenaltyBreakFirstLessLess
# PenaltyBreakString
# PenaltyBreakTemplateDeclaration
# PenaltyExcessCharacter
# PenaltyReturnTypeOnItsOwnLine
PointerAlignment: Right
# RawStringFormats
ReflowComments: false
SortIncludes: false
SortUsingDeclarations: false
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 4
SpacesInAngles: false
SpacesInCStyleCastParentheses: false
SpacesInContainerLiterals: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: Auto
# StatementMacros
# TabWidth
UseTab: Never
```
