### ISSUE TITLE
SplitEmptyRecord also affects whether to SplitEmptyFunction

### ISSUE THREAD

**Issue by lichray** [llvm/llvm-project#50051]
|  |  |
| --- | --- |
| Bugzilla Link | [50707](https://llvm.org/bz50707) |
| Version | trunk |
| OS | All |
| Attachments | [test case](https://user-images.githubusercontent.com/433009/143762230-4ef6f6b3-c376-4700-ae7f-2896cd260db1.gz) |

## Extended Description 

Given the following .clang-format file:

```
---
BasedOnStyle: Microsoft
AccessModifierOffset: '-4'
AllowAllConstructorInitializersOnNextLine: 'false'
ConstructorInitializerAllOnOneLineOrOnePerLine: 'true'
AllowShortFunctionsOnASingleLine: Empty
BreakConstructorInitializers: AfterColon
ColumnLimit: '80'
Language: Cpp
Standard: Latest
BraceWrapping:
  SplitEmptyFunction: true
  SplitEmptyRecord: false

...
```

Long function bodies are not becoming
{
}

Expects (test.cc): --

```
class Short
{};

class Test
{
public:
    Test() :
        bEnabled(false),
        eDestination(eOutputDestination::file),
        uiMaxSize(DEFAULT_MAX_LOGGER_FILE_SIZE)
    {
    }

    void memFun(void *caller, std::function<int(char const *, char)> cb,
                std::tuple<bool, std::string> param)
    {
    }
};

void regularFun(void *caller, std::function<int(char const *, char)> cb,
                std::tuple<bool, std::string> param)
{
}
```

Got: --

```
class Short
{};

class Test
{
public:
    Test() :
        bEnabled(false),
        eDestination(eOutputDestination::file),
        uiMaxSize(DEFAULT_MAX_LOGGER_FILE_SIZE)
    {}

    void memFun(void *caller, std::function<int(char const *, char)> cb,
                std::tuple<bool, std::string> param)
    {}
};

void regularFun(void *caller, std::function<int(char const *, char)> cb,
                std::tuple<bool, std::string> param)
{}

```
Trying out all 4 combinations of SplitEmptyFunction and SplitEmptyRecord and got a surprising result.

```
SplitEmptyFunction: false
SplitEmptyRecord: false
Good

SplitEmptyFunction: true
SplitEmptyRecord: false
Bad, same as above

SplitEmptyFunction: false
SplitEmptyRecord: true
Good

SplitEmptyFunction: true
SplitEmptyRecord: true
Good
```
