### ISSUE TITLE
clang-format C# switch expression formatting differs from normal switch formatting

### ISSUE THREAD

**Issue by eazrael** [llvm/llvm-project#52677]
OS: Win10 64bit
Clang-format version: 13.0.0, precompiled binary
Language C#

I am not sure if this is an bug or C# switch expressions are for clang-format something different as normal switch code and are affected by other options. My expectation is that a switch expression is formatted the same as normal switch code with regard to brace positioning. It seems that switch expressions always use 1TBS. 
Addtionally all case in an switch expression are packed into as few lines as possible. 

```
namespace a
{
    class A
    {
        void f(int a)
        {
            int x; 
            switch(a)
            {
                case 1:
                    x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0;
                    break; 
                case 2:
                    x = 1; 
                default: 
                  x = 2;
            }
        }

        void g(int a)
        {
            int x = a switch 
            { 
                1 => (0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0), 
                2 => 1,
                _ => 2 
            };
        }
    }
}

```
with the style settings 
```
AlignAfterOpenBracket: DontAlign
AlignArrayOfStructures: Right
AllowAllArgumentsOnNextLine: false
AlignOperands: DontAlign
AllowShortBlocksOnASingleLine: Empty
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: All
AlwaysBreakTemplateDeclarations: No
# BreakBeforeBraces: Allman
BreakBeforeBraces: Custom
BraceWrapping:
#  AfterCaseLabel: true
  AfterClass: true
  AfterControlStatement: true
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: true
  AfterStruct: true
  BeforeCatch: true
  BeforeElse: true
  AfterObjCDeclaration: true
  BeforeLambdaBody: false
  BeforeWhile: false
  IndentBraces: false
BreakBeforeConceptDeclarations: false
ColumnLimit: 80
ContinuationIndentWidth: 4
IncludeBlocks: Merge
IndentWidth: 4
IndentRequires: false
NamespaceIndentation: All
SpaceAfterCStyleCast: true
SpaceBeforeParens: false
SortIncludes: CaseInsensitive

```
gets formatted to 

```
namespace a
{
    class A
    {
        void f(int a)
        {
            int x;
            switch(a)
            {
            case 1:
                x = 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0;
                break;
            case 2:
                x = 1;
            default:
                x = 2;
            }
        }

        void g(int a)
        {
            int x = a switch { 1 => (0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0),
                2 => 1, _ => 2 };
        }
    }
}
```
My expection is that the switch expression in g() is formatted like in my source. This is also the style Microsoft uses https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression
