### ISSUE TITLE
[clang-format] Forced to use a deprecated option

### ISSUE THREAD

**Issue by reconndev** [llvm/llvm-project#52852]
# Description

`AlwaysBreakAfterDefinitionReturnType` is allegedly deprecated but the user is still forced to use it when based on e.g., Mozilla.

# Reproduction

Example to reformat:
```
int main() {}
```
`.clang-format` file:
```yaml
---
BasedOnStyle: Mozilla
### These two options ALONE don't affect the result (they probably should)
AlwaysBreakAfterReturnType: None
PenaltyReturnTypeOnItsOwnLine: 0
### User is forced to undefine this Mozilla default even though AlwaysBreakAfterReturnType is None already
AlwaysBreakAfterDefinitionReturnType: None
...
```

Expected result: **file is unchanged** without the explicit declaration of AlwaysBreakAfterDefinitionReturnType.
