### ISSUE TITLE
Clang-format D117142 breaks trivial short function handling

### ISSUE THREAD

**Issue by zhihaoy** [llvm/llvm-project#53430]
.clang-format
```
---
BasedOnStyle: Microsoft
AllowShortFunctionsOnASingleLine: InlineOnly
Standard: Latest
BreakBeforeBraces: Custom
BraceWrapping:
  AfterFunction: true
  BeforeLambdaBody: true
  SplitEmptyFunction: false

...
```

Test case
```cpp
struct C
{
    int h() noexcept
    {
        return -1;
    }
};
```

When reaching https://github.com/llvm/llvm-project/blob/7af11989be21df00ad6a510a831ea2425e48fa90/clang/lib/Format/UnwrappedLineFormatter.cpp#L290-L295, `RecordToken` is `{`.

cc @mkurdej
