### ISSUE TITLE
[clang-tidy] How to specify multiple values for a key?

### ISSUE THREAD

**Issue by shrek1402** [llvm/llvm-project#53517]
Is it possible to specify multiple values for a key? Something like this:
```
CheckOptions:
  - key:   readability-identifier-naming.AbstractClassCase
    value: 'lower_case', 'UPPER_CASE'
  - key:   readability-identifier-naming.StructPrefix
    value: '_', '' # '_' or empty
```
