### ISSUE TITLE
[Formatter] Excess spaces around specializations in concepts

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#53819]
Here's the diffs after updating Clang.
```diff
 export template<class T, template<class> class Trait, class ValueType> concept base_characteristic_of =
-  base_characteristic_of_impl<T, Trait<T>, ValueType>;
+  base_characteristic_of_impl < T,
+                                                                               Trait<T>,
+ValueType > ;
 
-export template<class T, template<class> class U> concept distinguished_value_trait_in = value_trait_for<U<T>, T>;
+export template<class T, template<class> class U> concept distinguished_value_trait_in = value_trait_for < U<T>,
+T > ;

 template<class T, class U> concept scalable_with = //
-  std::common_with<number_scalar_t<T>, U> and      //
-  weakly_scalable<T> and                           //
-  weakly_scalable<U> and                           //
-  dividable_with<T, U> and                         //
-  inversible_number<U>;
+  std::common_with < number_scalar_t<T>,
+U > and                         //
+    weakly_scalable<T>and       //
+      weakly_scalable<U>and     //
+        dividable_with<T, U>and //
+          inversible_number<U>;

-export template<class T> concept vector_space =   //
-  negatable_number<T> and                         //
-  multipliable_with<number_scalar_t<T>, T, T> and //
-  inversible_number<number_scalar_t<T>>;
+export template<class T> concept vector_space = //
+  negatable_number<T> and                       //
+  multipliable_with < number_scalar_t<T>,
+T, T > and //
+       inversible_number<number_scalar_t<T>>;

-template<class T> concept bit_castable_to_storage   = bit_castable<storage_for<T>, T>;
+template<class T> concept bit_castable_to_storage   = bit_castable < storage_for<T>,
+T > ;
```
`.clang-format`:
```yaml
AccessModifierOffset: -2
AlignAfterOpenBracket: AlwaysBreak
AlignArrayOfStructures: None
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveBitFields: true
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Right
AlignOperands: Align
AlignTrailingComments: true
AllowAllArgumentsOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: Always
AllowShortCaseLabelsOnASingleLine: true
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: AllIfsAndElse
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: true
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: No
BinPackArguments: true
BinPackParameters: true
BitFieldColonSpacing: Both
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Attach
BreakBeforeConceptDeclarations: Allowed
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeColon
BreakInheritanceList: BeforeColon
BreakStringLiterals: true
ColumnLimit: 120
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
Cpp11BracedListStyle: true
DeriveLineEnding: false
DerivePointerAlignment: false
DisableFormat: false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: Always
FixNamespaceComments: true
IncludeBlocks: Preserve
IncludeCategories:
  - Regex:      '<(experimental/)?[a-z_]+>' # C++ standard library
    Priority:   1
IndentAccessModifiers: false
IndentCaseBlocks: false
IndentCaseLabels: false
IndentPPDirectives: AfterHash
IndentRequiresClause: true
IndentWidth: 2
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: false
LambdaBodyIndentation: Signature
Language: Cpp
MaxEmptyLinesToKeep: 1
NamespaceIndentation: Inner
PackConstructorInitializers: NextLine
PointerAlignment: Left
PPIndentWidth: -1
QualifierAlignment: Custom
QualifierOrder: ["static", "inline", "constexpr", "const", "volatile", "type"]
ReferenceAlignment: Pointer
ReflowComments: true
RequiresClausePosition: WithPreceding
ShortNamespaceLines: 0
SortIncludes: CaseInsensitive
SortUsingDeclarations: true
SpaceAfterLogicalNot: true
SpaceAfterTemplateKeyword: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: true
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false
SpacesInConditionalStatement: false
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 1
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: Latest
TabWidth: 2
UseCRLF: false
UseTab: Never
```
