### ISSUE TITLE
[Formatter] Attribute after `requires` is formatted wrongly

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#53820]
Seems like it's considered part of the `requires`.
Here's the diff after updating Clang.
```diff
 export template<class DerivedRef, class Base>
-  requires(
-    std::is_reference_v<DerivedRef> and
-    not std::is_same_v<std::remove_cvref_t<DerivedRef>, std::remove_cvref_t<Base>> and
-    std::derived_from<std::remove_reference_t<DerivedRef>, std::remove_reference_t<Base>>)
-[[nodiscard]] constexpr auto static_downcast(Base&& b) noexcept
+requires(std::is_reference_v<DerivedRef> and
+         not std::is_same_v<std::remove_cvref_t<DerivedRef>, std::remove_cvref_t<Base>> and
+         std::derived_from<std::remove_reference_t<DerivedRef>, std::remove_reference_t<Base>>) [
+        [nodiscard]] constexpr auto static_downcast(Base&& b) noexcept
   -> decltype(static_cast<DerivedRef>(std::forward<Base>(b))) {
   return static_cast<DerivedRef>(std::forward<Base>(b));
 }

 #if defined(__clang__) or not defined(__GNUC__)
 export template<class To> [[nodiscard]] constexpr To convert_to(To to) { return to; }
-export template<class To, class From>
-  requires(not std::convertible_to<const From&, To>)
-[[nodiscard]] constexpr To convert_to(const From& from) { return static_cast<To>(from); }
+export template<class To, class From> requires(not std::convertible_to<const From&, To>) [
+  [nodiscard]] constexpr To convert_to(const From& from) {
+  return static_cast<To>(from);
+}
 #else
-export template<class To, class From>
-  requires std::convertible_to<const From&, To>
-[[nodiscard]] constexpr const From& convert_to(const From& from) { return from; }
+export template<class To, class From> requires std::convertible_to<const From&, To> [
+  [nodiscard]] constexpr const From&
+convert_to(const From& from) {
+  return from;
+}
 export template<class To, class From> [[nodiscard]] constexpr To convert_to(const From& from) {
   return static_cast<To>(from);
 }
#endif

 struct [[nodiscard]] zero_t {
-  template<class T>
-    requires requires { number_zero_v<T>; }
-  [[nodiscard]] constexpr operator T() const { return number_zero_v<T>; }
+  template<class T> requires requires { number_zero_v<T>; } [
+    [nodiscard]] constexpr
+  operator T() const {
+    return number_zero_v<T>;
+  }
 };
 struct [[nodiscard]] one_t {
-  template<class T>
-    requires requires { number_one_v<T>; }
-  [[nodiscard]] constexpr operator T() const { return number_one_v<T>; }
+  template<class T> requires requires { number_one_v<T>; } [
+    [nodiscard]] constexpr
+  operator T() const {
+    return number_one_v<T>;
+  }
 };
```
`.clang-format`:
```yaml
AccessModifierOffset: -2
AlignAfterOpenBracket: AlwaysBreak
AlignArrayOfStructures: None
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveBitFields: true
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Right
AlignOperands: Align
AlignTrailingComments: true
AllowAllArgumentsOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: Always
AllowShortCaseLabelsOnASingleLine: true
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: AllIfsAndElse
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: true
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: No
BinPackArguments: true
BinPackParameters: true
BitFieldColonSpacing: Both
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Attach
BreakBeforeConceptDeclarations: Allowed
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeColon
BreakInheritanceList: BeforeColon
BreakStringLiterals: true
ColumnLimit: 120
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
Cpp11BracedListStyle: true
DeriveLineEnding: false
DerivePointerAlignment: false
DisableFormat: false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: Always
FixNamespaceComments: true
IncludeBlocks: Preserve
IncludeCategories:
  - Regex:      '<(experimental/)?[a-z_]+>' # C++ standard library
    Priority:   1
IndentAccessModifiers: false
IndentCaseBlocks: false
IndentCaseLabels: false
IndentPPDirectives: AfterHash
IndentRequiresClause: true
IndentWidth: 2
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: false
LambdaBodyIndentation: Signature
Language: Cpp
MaxEmptyLinesToKeep: 1
NamespaceIndentation: Inner
PackConstructorInitializers: NextLine
PointerAlignment: Left
PPIndentWidth: -1
QualifierAlignment: Custom
QualifierOrder: ["static", "inline", "constexpr", "const", "volatile", "type"]
ReferenceAlignment: Pointer
ReflowComments: true
RequiresClausePosition: WithPreceding
ShortNamespaceLines: 0
SortIncludes: CaseInsensitive
SortUsingDeclarations: true
SpaceAfterLogicalNot: true
SpaceAfterTemplateKeyword: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: true
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false
SpacesInConditionalStatement: false
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 1
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: Latest
TabWidth: 2
UseCRLF: false
UseTab: Never
```
