### ISSUE TITLE
clang-format: Allow empty structs and classes on single line

### ISSUE THREAD

**Issue by AdamBucior** [llvm/llvm-project#53960]
When I format this example code:
```
struct A
{
  int i;
};

struct B {};

class C
{
  void foo();
};

class D {};
```
With this `.clang-format` file:
```
BraceWrapping:
 AfterClass: true
 AfterStruct: true
 SplitEmptyRecord: false

BreakBeforeBraces: Custom
```
I get this ugly result:
```
struct A
{
  int i;
};

struct B
{};

class C
{
  void foo();
};

class D
{};
```
I would like there to be an option to allow empty structs and classes on a single line (so that the example code is left unchanged) just like it is possible with functions by using `AllowShortFunctionsOnASingleLine`.
