### ISSUE TITLE
clang-format crash due to AlignArrayOfStructures

### ISSUE THREAD

**Issue by xsxkair** [llvm/llvm-project#54771]
..\clang-format.exe -style=file -i ..\ThirdParty\MotorModule\Motor_Data.c
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ..\\clang-format.exe -style=file -i ..\\ThirdParty\\MotorModule\\Motor_Data.c
0x00007FF6136ACCE9 (0x000000FE00000000 0x00007FF613654081 0x0000021B0686A560 0x000000000000443A)
0x00007FF6136AC719 (0x0000049EFFFFFFFF 0x0000000000000000 0x000000FEFC98CB28 0x0000000000000000)
0x00007FF6136AB2A9 (0x0000000000000000 0x000000FE00000000 0x000000FEFC98E658 0x00007FFA0835F05B)
0x00007FF6136A84E7 (0x000000FEFC98BAC0 0x000000FE00000000 0x00000000066B0FE0 0x0000000000000000)
0x00007FF613670B28 (0x000000FEFC98C190 0x0000000000000002 0x000000FEFC98BE40 0x000000020161C68D)
0x00007FF613685C37 (0x000000FEFC98CF60 0x0000000000000026 0x00007FF61376E065 0x0000000000000002)
0x00007FF61367CB14 (0x0000000000000010 0x00007FFA00000000 0x000000FEFC98D6F8 0x0000021B06664830)
0x00007FF613667759 (0x0000021B06645110 0x00007FFA0ABD47B1 0x0000021B06667230 0x0000021B06630000)
0x00007FF613668019 (0x0041005F00000040 0x0000000000000000 0x0000000000000000 0x0000000000000001)
0x00007FF6135F44B2 (0x0000000000000000 0x0000000000000001 0x0000021B06635360 0x000000FE00000000)
0x00007FF6135F2FC6 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF613769C84 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA0A017034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFA0AC02651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

### this is my file
```
/******************************************File Start**********************************************
*FileName:
*Description:
*Author:xsx
*Data:
****************************************************************************************************/

/***************************************************************************************************/
/******************************************Header List**********************************************/
/***************************************************************************************************/
#include    "Motor_Data.h"

#include    "Motors_GPIO_Driver.h"
#include    "Sensor_Driver.h"
#include    "Task_Param_Utils.h"
#include    "Com_Result.h"
#include    "Log.h"

#include    <string.h>
#include    "stdio.h"
#include    "stdlib.h"
#include    "math.h"

/***************************************************************************************************/
/******************************************Static Variables*****************************************/
/***************************************************************************************************/
const char * motor_name[] = {
    "HuChongYe_Motor",
    "Sample_Motor",
    "Card_1_Motor",
    "Card_2_Motor",
    "Card_3_Motor",
    "Lighter_Motor",
    "Sample_Z_Motor",
    "Sample_X_Motor",
};

const com_msg_code_e gb_motor_sensor_tri_event[end_motor][MOTOR_SENSOR_NUM] = 
{
    {com_msg_water_loc_sensor_trigged },    //HuChongYe_Motor,
    {com_msg_blood_loc_sensor_trigged},    //Sample_Motor,
    {com_msg_none},    //Card_1_Motor,
    {com_msg_none},    //Card_2_Motor,
    {com_msg_none},    //Card_3_Motor,
    {com_msg_none},    //Lighter_Motor,
    {com_msg_water_deep_sensor_trigged},    //Sample_Z_Motor,
    {com_msg_none},    //Sample_X_Motor,
};

const motor_base_info_t gb_motor_base_info[end_motor] = 
{
    {
        .id = HuChongYe_Motor,
        .name = "HuChongYe_Motor",
        
        .step_gpio_group = HuChongYe_Motor_CLK_Group,
        .step_gpio_pin = HuChongYe_Motor_CLK_Pin,

        .dir_gpio_group = HuChongYe_Motor_DIR_Group,
        .dir_gpio_pin = HuChongYe_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_RESET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = HuChongYe_Motor_Origin_Group,
                    .gpio_pin = HuChongYe_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {
                    .gpio_group = HuChongYe_Motor_Water_Group,
                    .gpio_pin = HuChongYe_Motor_Water_Pin,
                    .triggered_value = GPIO_PIN_SET,
                    .triggered_pass_cnt = 50
                },
            },
    },
    {
        .id = Sample_Motor,
        .name = "Sample_Motor",
        
        .step_gpio_group = Sample_Motor_CLK_Group,
        .step_gpio_pin = Sample_Motor_CLK_Pin,

        .dir_gpio_group = Sample_Motor_DIR_Group,
        .dir_gpio_pin = Sample_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_SET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = Sample_Motor_Origin_Group,
                    .gpio_pin = Sample_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {
                    .gpio_group = Sample_Motor_Get_Sample_Group,
                    .gpio_pin = Sample_Motor_Get_Sample_Pin,
                    .triggered_value = GPIO_PIN_SET,
                    .triggered_pass_cnt = 50
                },
            },
    },
    {
        .id = Card_1_Motor,
        .name = "Card_1_Motor",
        
        .step_gpio_group = Card_1_Motor_CLK_Group,
        .step_gpio_pin = Card_1_Motor_CLK_Pin,

        .dir_gpio_group = Card_1_Motor_DIR_Group,
        .dir_gpio_pin = Card_1_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_RESET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = Card_1_Motor_Origin_Group,
                    .gpio_pin = Card_1_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {
                    .gpio_group = NULL,
                },
            },
    },
    {
        .id = Card_2_Motor,
        .name = "Card_2_Motor",
        
        .step_gpio_group = Card_2_Motor_CLK_Group,
        .step_gpio_pin = Card_2_Motor_CLK_Pin,

        .dir_gpio_group = Card_2_Motor_DIR_Group,
        .dir_gpio_pin = Card_2_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_RESET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = Card_2_Motor_Origin_Group,
                    .gpio_pin = Card_2_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {
                    .gpio_group = NULL,
                },
            },
    },
    {
        .id = Card_3_Motor,
        .name = "Card_3_Motor",
        
        .step_gpio_group = Card_3_Motor_CLK_Group,
        .step_gpio_pin = Card_3_Motor_CLK_Pin,

        .dir_gpio_group = Card_3_Motor_DIR_Group,
        .dir_gpio_pin = Card_3_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_RESET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = Card_3_Motor_Origin_Group,
                    .gpio_pin = Card_3_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {
                    .gpio_group = NULL,
                },
            },
    },
    {
        .id = Lighter_Motor,
        .name = "Lighter_Motor",
        
        .step_gpio_group = Lighter_Motor_CLK_Group,
        .step_gpio_pin = Lighter_Motor_CLK_Pin,

        .dir_gpio_group = Lighter_Motor_DIR_Group,
        .dir_gpio_pin = Lighter_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_RESET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = Lighter_Motor_Origin_Group,
                    .gpio_pin = Lighter_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {
                    .gpio_group = NULL,
                },
            },
    },
    {
        .id = Sample_Z_Motor,
        .name = "Sample_Z_Motor",
        
        .step_gpio_group = Sample_Z_Motor_CLK_Group,
        .step_gpio_pin = Sample_Z_Motor_CLK_Pin,

        .dir_gpio_group = Sample_Z_Motor_DIR_Group,
        .dir_gpio_pin = Sample_Z_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_SET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = Sample_Z_Motor_Origin_Group,
                    .gpio_pin = Sample_Z_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {
                    .gpio_group = Sample_Z_Motor_Check_Water_Group,
                    .gpio_pin = Sample_Z_Motor_Check_Water_Pin,
                    .triggered_value = GPIO_PIN_SET,
                    .triggered_pass_cnt = 50
                },
            },
    },
    {
        .id = Sample_X_Motor,
        .name = "Sample_X_Motor",
        
        .step_gpio_group = Sample_X_Motor_CLK_Group,
        .step_gpio_pin = Sample_X_Motor_CLK_Pin,

        .dir_gpio_group = Sample_X_Motor_DIR_Group,
        .dir_gpio_pin = Sample_X_Motor_DIR_Pin,
        .forward_value = GPIO_PIN_RESET,

        .en_gpio_group = NULL,
        
        .limit_sensor = 
            {
                {
                    .gpio_group = Sample_X_Motor_Origin_Group,
                    .gpio_pin = Sample_X_Motor_Origin_Pin,
                    .triggered_value = GPIO_PIN_RESET,
                    .triggered_pass_cnt = 50
                },
                {.gpio_group = NULL,}
            },
        .other_sensor = 
            {
                {.gpio_group = NULL,}
            },
    },
};

Motor GB_Motors[end_motor] =
{
    {   
        .motor_base_info = &gb_motor_base_info[HuChongYe_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 20, 20},
        .acc_min_speed = 50,
        .acc_max_speed = 20,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 150,
    },
    {   
        .motor_base_info = &gb_motor_base_info[Sample_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 20, 20},
        .acc_min_speed = 50,
        .acc_max_speed = 20,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 150,
    },
    {   
        .motor_base_info = &gb_motor_base_info[Card_1_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 600, 20},
        .acc_min_speed = 50,
        .acc_max_speed = 6,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 200,
    },
    {   
        .motor_base_info = &gb_motor_base_info[Card_2_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 600, 20},
        .acc_min_speed = 50,
        .acc_max_speed = 6,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 200,
    },
    {   
        .motor_base_info = &gb_motor_base_info[Card_3_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 600, 20},
        .acc_min_speed = 50,
        .acc_max_speed = 6,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 200,
    },
    {   
        .motor_base_info = &gb_motor_base_info[Lighter_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 20, 20},
        .acc_min_speed = 50,
        .acc_max_speed = 6,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 150,
    },
    {   
        .motor_base_info = &gb_motor_base_info[Sample_Z_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 20, 20},
        .acc_min_speed = 50,
        .acc_max_speed = 12,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 100,
    },
    {   
        .motor_base_info = &gb_motor_base_info[Sample_X_Motor],
        .busy = 0,
        .dir = MOTOR_DIR_FONT,
        .init = 0,
        
        .max_location = 65535,
        .motorLocation = 0,
        .targetLocation = 0,
        
        .normal_speed = {40, 20, 20},
        .acc_min_speed = 80,
        .acc_max_speed = 14,
        .acc_speed_fix_param = 4,
        .acc_1_4_step_num = 400,
    },
};
/***************************************************************************************************/
/******************************************Static Methods*******************************************/
/***************************************************************************************************/

/***************************************************************************************************/
/***************************************************************************************************/
/******************************************Main Body************************************************/
/***************************************************************************************************/
/***************************************************************************************************/
/***************************************************************************************************/
Motor *getMotor(int motor)
{
    return &GB_Motors[motor];
}

signed int get_motor_location(int motor)
{
    return GB_Motors[motor].motorLocation;
}

unsigned char get_motor_index_from_addr(Motor *motor)
{
    unsigned char i = 0;
    Motor *temp = GB_Motors;
    for (i = 0; i < end_motor; i++)
    {
        if (motor == temp++)
            return i;
    }

    return 200;
}

unsigned char is_motor_loc_equal_with(motor_id_e motor_id, signed int loc)
{
    unsigned char motor_index = (unsigned char)motor_id;
    
    return (GB_Motors[motor_index].motorLocation == loc);
}
/***************************************************************************************************
*FunctionName: changeMotorSpeed
*Description: v = minPwmCnt + (motor->maxPwmCnt-motor->minPwmCnt)/(1 + e(-standCnt*(index - changeStepCnt)/changeStepCnt))
*Input:
*Output:
*Return:
*Author: xsx
*Date:
***************************************************************************************************/
void changeMotorSpeed(Motor *motor)
{
    double tempValue = 0.0f;
    tempValue = motor->cur_acc_step_num;
    tempValue -= motor->acc_1_4_step_num;
    tempValue *= motor->acc_speed_fix_param;
    tempValue /= motor->acc_1_4_step_num;
    tempValue = 0 - tempValue;
    tempValue = exp(tempValue);
    tempValue += 1;
    tempValue = (motor->acc_max_speed - motor->acc_min_speed) / tempValue;
    tempValue += motor->acc_min_speed;
    motor->cur_speed_totalPwmCnt = (unsigned char)tempValue;
}

void calMotorSpeed(Motor *motor)
{
    //no s line
    if (motor->speed_type != MOTOR_SPEED_ACC)
    {
        return;
    }
    //加速
    else if (motor->cur_acc_stage == 0)
    {
        changeMotorSpeed(motor);
        motor->cur_speed_highPwmCnt = motor->cur_speed_totalPwmCnt / 2;
        
        //如果当前速度大于等于最大速度，则开始匀速
        if (motor->cur_speed_totalPwmCnt <= motor->acc_max_speed)
        {
            motor->cur_acc_step_num = 0;
            motor->cur_acc_stage = 1;
        }
        //剩余步数小于减速距离，则开始减速
        else if(motor->moveStepNum <= (2 * motor->acc_1_4_step_num))
        {
            motor->cur_acc_stage = 2;
            if(motor->moveStepNum > motor->cur_acc_step_num)
                motor->cur_acc_step_num = motor->moveStepNum - motor->cur_acc_step_num;
            else
                motor->cur_acc_step_num = 0;
        }
        else
            motor->cur_acc_step_num++;
    }
    //匀速
    else if (motor->cur_acc_stage == 1)
    {
        //剩余行走步数，小于一个减速距离，则开始减速
        if (motor->moveStepNum <= (2 * motor->acc_1_4_step_num))
        {
            motor->cur_acc_stage = 2;
            motor->cur_acc_step_num = 0;
        }
    }
    //减速
    else
    {
        changeMotorSpeed(motor);
        motor->cur_speed_totalPwmCnt = motor->acc_max_speed + motor->acc_min_speed - motor->cur_speed_totalPwmCnt;
        motor->cur_speed_highPwmCnt = motor->cur_speed_totalPwmCnt / 2;
		if(motor->cur_speed_highPwmCnt == 0)
            motor->cur_speed_highPwmCnt = 1;
        motor->cur_acc_step_num++;
    }
    //if(motor->name == Sample_X_Motor && motor->log_buf && motor->log_buf->len < 4050){
    //    motor->log_buf->len += sprintf((char *)&motor->log_buf->data[motor->log_buf->len], "%d%d%d", motor->slineStep, motor->totalPwmCnt, motor->sStep);
    //}
}
/****************************************end of file************************************************/

```

**Comment by mkurdej** [comment]
Please include .clang-format config file and, if possible, be more specific in the title.

**Comment by xsxkair** [comment]
this is .clang-format file
```
---
# 语言: None, Cpp, Java, JavaScript, ObjC, Proto, TableGen, TextProto
Language:	Cpp
# BasedOnStyle:	LLVM
# 访问说明符(public、private等)的偏移
AccessModifierOffset:	-4
# 开括号(开圆括号、开尖括号、开方括号)后的对齐: Align, DontAlign, AlwaysBreak(总是在开括号后换行)
AlignAfterOpenBracket:	Align
# 连续赋值时，对齐所有等号
AlignConsecutiveAssignments:	true
# 连续声明时，对齐所有声明的变量名
AlignConsecutiveDeclarations:	false
# 左对齐逃脱换行(使用反斜杠换行)的反斜杠
AlignEscapedNewlinesLeft:	true
# 水平对齐二元和三元表达式的操作数
AlignOperands:	true
# 对齐连续的尾随的注释
AlignTrailingComments:	true
# 允许函数声明的所有参数在放在下一行
AllowAllParametersOfDeclarationOnNextLine:	true
# 允许短的块放在同一行
AllowShortBlocksOnASingleLine:	false
# 允许短的case标签放在同一行
AllowShortCaseLabelsOnASingleLine:	false
# 允许短的函数放在同一行: None, InlineOnly(定义在类中), Empty(空函数), Inline(定义在类中，空函数), All
AllowShortFunctionsOnASingleLine:	Empty
# 允许短的if语句保持在同一行
AllowShortIfStatementsOnASingleLine:	false
# 允许短的循环保持在同一行
AllowShortLoopsOnASingleLine:	false
# 总是在定义返回类型后换行(deprecated)
AlwaysBreakAfterDefinitionReturnType:	None
# 总是在返回类型后换行: None, All, TopLevel(顶级函数，不包括在类中的函数), 
#   AllDefinitions(所有的定义，不包括声明), TopLevelDefinitions(所有的顶级函数的定义)
AlwaysBreakAfterReturnType:	None
# 总是在多行string字面量前换行
AlwaysBreakBeforeMultilineStrings:	false
# 总是在template声明后换行
AlwaysBreakTemplateDeclarations:	false
# false表示函数实参要么都在同一行，要么都各自一行
BinPackArguments:	true
# false表示所有形参要么都在同一行，要么都各自一行
BinPackParameters:	true
# 大括号换行，只有当BreakBeforeBraces设置为Custom时才有效
BraceWrapping:   
  # class定义后面
  AfterClass:	false
  # 控制语句后面
  AfterControlStatement:	true
  # enum定义后面
  AfterEnum:	true
  # 函数定义后面
  AfterFunction:	true
  # 命名空间定义后面
  AfterNamespace:	false
  # ObjC定义后面
  AfterObjCDeclaration:	true
  # struct定义后面
  AfterStruct:	true
  # union定义后面
  AfterUnion:	false
  # catch之前
  BeforeCatch:	true
  # else之前
  BeforeElse:	true
  # 缩进大括号
  IndentBraces:	false
# 在二元运算符前换行: None(在操作符后换行), NonAssignment(在非赋值的操作符前换行), All(在操作符前换行)
BreakBeforeBinaryOperators:	NonAssignment
# 在大括号前换行: Attach(始终将大括号附加到周围的上下文), Linux(除函数、命名空间和类定义，与Attach类似), 
#   Mozilla(除枚举、函数、记录定义，与Attach类似), Stroustrup(除函数定义、catch、else，与Attach类似), 
#   Allman(总是在大括号前换行), GNU(总是在大括号前换行，并对于控制语句的大括号增加额外的缩进), WebKit(在函数前换行), Custom
#   注：这里认为语句块也属于函数
BreakBeforeBraces:	Custom
# 在三元运算符前换行
BreakBeforeTernaryOperators:	true
# 在构造函数的初始化列表的逗号前换行
BreakConstructorInitializersBeforeComma:	false
# 每行字符的限制，0表示没有限制
ColumnLimit:	140
# 描述具有特殊意义的注释的正则表达式，它不应该被分割为多行或以其它方式改变
CommentPragmas:	'^ IWYU pragma:'
# 构造函数的初始化列表要么都在同一行，要么都各自一行
ConstructorInitializerAllOnOneLineOrOnePerLine:	false
# 构造函数的初始化列表的缩进宽度
ConstructorInitializerIndentWidth:	4
# 延续的行的缩进宽度
ContinuationIndentWidth:	4
# 去除C++11的列表初始化的大括号{后和}前的空格
Cpp11BracedListStyle:	false
# 继承最常用的指针和引用的对齐方式
DerivePointerAlignment:	false
# 关闭格式化
DisableFormat:	false
# 自动检测函数的调用和定义是否被格式为每行一个参数(Experimental)
ExperimentalAutoDetectBinPacking:	false
# 需要被解读为foreach循环而不是函数调用的宏
ForEachMacros:	[ foreach, Q_FOREACH, BOOST_FOREACH ]
# 缩进case标签
IndentCaseLabels:	true
# 缩进宽度
IndentWidth:	4
# 函数返回类型换行时，缩进函数声明或函数定义的函数名
IndentWrappedFunctionNames:	false
# 保留在块开始处的空行
KeepEmptyLinesAtTheStartOfBlocks:	true
# 开始一个块的宏的正则表达式
MacroBlockBegin:	''
# 结束一个块的宏的正则表达式
MacroBlockEnd:	''
# 连续空行的最大数量
MaxEmptyLinesToKeep:	1
# 命名空间的缩进: None, Inner(缩进嵌套的命名空间中的内容), All
NamespaceIndentation:	Inner
# 使用ObjC块时缩进宽度
ObjCBlockIndentWidth:	4
# 在ObjC的@property后添加一个空格
ObjCSpaceAfterProperty:	false
# 在ObjC的protocol列表前添加一个空格
ObjCSpaceBeforeProtocolList:	true
# 在call(后对函数调用换行的penalty
PenaltyBreakBeforeFirstCallParameter:	19
# 在一个注释中引入换行的penalty
PenaltyBreakComment:	300
# 第一次在<<前换行的penalty
PenaltyBreakFirstLessLess:	120
# 在一个字符串字面量中引入换行的penalty
PenaltyBreakString:	1000
# 对于每个在行字符数限制之外的字符的penalty
PenaltyExcessCharacter:	1000000
# 将函数的返回类型放到它自己的行的penalty
PenaltyReturnTypeOnItsOwnLine:	60
# 指针和引用的对齐: Left, Right, Middle
PointerAlignment:	Left
# 允许重新排版注释
ReflowComments:	true
# 允许排序#include
SortIncludes:	true
# 在C风格类型转换后添加空格
SpaceAfterCStyleCast:	false
# 在赋值运算符之前添加空格
SpaceBeforeAssignmentOperators:	true
# 开圆括号之前添加一个空格: Never, ControlStatements, Always
SpaceBeforeParens:	ControlStatements
# 在空的圆括号中添加空格
SpaceInEmptyParentheses:	false
# 在尾随的评论前添加的空格数(只适用于//)
SpacesBeforeTrailingComments:	2
# 在尖括号的<后和>前添加空格
SpacesInAngles:	true
# 在容器(ObjC和JavaScript的数组和字典等)字面量中添加空格
SpacesInContainerLiterals:	true
# 在C风格类型转换的括号中添加空格
SpacesInCStyleCastParentheses:	true
# 在圆括号的(后和)前添加空格
SpacesInParentheses:	true
# 在方括号的[后和]前添加空格，lamda表达式和未指明大小的数组的声明不受影响
SpacesInSquareBrackets:	true
# 标准: Cpp03, Cpp11, Auto
Standard:	Cpp11
# tab宽度
TabWidth:	4
# 使用tab字符: Never, ForIndentation, ForContinuationAndIndentation, Always
UseTab:	Never
AlignArrayOfStructures: Left

#对齐连续宏定义的样式
#ACS_AcrossEmptyLinesAndComments:也跨越仅包含注释和空行的行
AlignConsecutiveMacros: true
```
