### ISSUE TITLE
[clang-format] inheritance list is not aligned, comment moved to other line

### ISSUE THREAD

**Issue by igagis** [llvm/llvm-project#55331]
# to reproduce

`.clang-format`:
```yaml
BreakConstructorInitializers: AfterColon
BreakInheritanceList: AfterColon
ConstructorInitializerIndentWidth: '2'
```

`main.cpp`:
```cpp
class A{};
class B{};

class C : //
public A,
public B{

	int c;
	int c1;

	C() : //
c(10),c1(20){}

};
```

run command:
```console
clang-format main.cpp
```

# expected result

```cpp
class A {};
class B {};

class C : //
  public A, public B{

  int c;
  int c1;

  C() : //
    c(10), c1(20) {}
};
```

# actual result

```cpp
class A {};
class B {};

class C : //
public A,
public B{

  int c;
  int c1;

  C() :
    //
    c(10), c1(20) {}
};
```

- inheritance list is not indented
- comment in `C` constructor initializer list is moved to the next line. Comments should not be moved to other lines.

**Comment by igagis** [comment]
Would be nice to have option similar to `PackConstructorInitializers` but for inheritance list with similar possible values. Maybe `PackInheritanceList`?

**Comment by igagis** [comment]
Looks like `BreakInheritanceList: AfterColon` option breaks the formatting of inheritance list.

I also have these options:
```yaml
BreakInheritanceList: AfterColon
ReflowComments: 'true'
SpacesBeforeTrailingComments: '1'
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: -1
```

and this snippet:
```cpp
class A ://some comment
	public B,public C
{
  int a; // some comment
};
```
is not changed at all

# expected result

```cpp
class A : // some comment
    public B,
    public C {
  int a; // some comment
};

```
