### ISSUE TITLE
[clang-format] Bad interaction between AlignConsecutiveAssignments.Enabled=true and BinPackArguments=false

### ISSUE THREAD

**Issue by cha5on** [llvm/llvm-project#55360]
### Description

`AlignConsecutiveAssignments` doesn't align properly if `BinPackArguments = false`.

First noticed with clang-format 14.0.0, but present in current main branch.

Proposed fix is at https://reviews.llvm.org/D125162 .

### Example 1

`.clang-format` for this example:

```yaml
---
Language:        Cpp
# BasedOnStyle:  LLVM
AccessModifierOffset: -2
AlignConsecutiveAssignments: Consecutive
BinPackArguments: false
BinPackParameters: false
```

Expected:
```cpp
struct A {
  int a;
  int b;
  int c;
};
struct B {
  A a1;
  A a2;
  A a3;
};
int a_long_name                  = 1;
int an_even_longer_name_for_wrap = 1;
auto b                           = B{{a_long_name, a_long_name, a_long_name},

                                     {an_even_longer_name_for_wrapping,
                                      an_even_longer_name_for_wrapping,
                                      an_even_longer_name_for_wrapping}};
```

Actual:

```cpp
struct A {
  int a;
  int b;
  int c;
};
struct B {
  A a1;
  A a2;
  A a3;
};
int a_long_name                  = 1;
int an_even_longer_name_for_wrap = 1;
auto b                           = B{{a_long_name, a_long_name, a_long_name},

           {an_even_longer_name_for_wrapping,
                                      an_even_longer_name_for_wrapping,
                                      an_even_longer_name_for_wrapping}};
```

### Example 2

A slightly smaller case with a reduced column limit.

`.clang-format` for this example:

```yaml
---
Language:        Cpp
# BasedOnStyle:  LLVM
AccessModifierOffset: -2
AlignConsecutiveAssignments: Consecutive
BinPackArguments: false
BinPackParameters: false
ColumnLimit:     50
```

Expected:

```cpp
struct A {
  int a;
  int b;
};
struct B {
  A a1;
  A a2;
};
int a_longer_name_for_wrap = 1;
// comment to prevent alignment
int a_long_name = 1;
auto b          = B({a_long_name, a_long_name},
                    {a_longer_name_for_wrap,
                     a_longer_name_for_wrap});
```

Actual:

```cpp
struct A {
  int a;
  int b;
};
struct B {
  A a1;
  A a2;
};
int a_longer_name_for_wrap = 1;
// comment to prevent alignment
int a_long_name = 1;
auto b          = B({a_long_name, a_long_name},
           {a_longer_name_for_wrap,
                     a_longer_name_for_wrap});
```
