### ISSUE TITLE
SplitEmptyRecord inconsistencies

### ISSUE THREAD

**Issue by yamt** [llvm/llvm-project#55379]
i want to format my source code as the following.
```
struct foo {
};
struct foo2 {
  int a;
};
class bar {
};
class bar2 {
  int a;
};
```

with clang-format version 13.0.1,
i was able to do that with a style like the following.
(`AfterFunction: true` is actually necessary.)
```
Language: Cpp
BasedOnStyle: LLVM
BreakBeforeBraces: Custom
BraceWrapping:
  AfterFunction: true
  AfterStruct: false
  AfterClass: false
  AfterUnion: false
```

however, with clang-format version 14.0.3,
it formats differently.
```
struct foo {};
struct foo2 {
  int a;
};
class bar {};
class bar2 {
  int a;
};
```

if i change the style to `AfterClass: true`,
they format like:

```
struct foo {
};
struct foo2 {
  int a;
};
class bar
{
};
class bar2
{
  int a;
};
```
