### ISSUE TITLE
[clang-format]: continuation for chained calls is wrong

### ISSUE THREAD

**Issue by igagis** [llvm/llvm-project#55478]
# input files

`.clang-format`:
```yaml
---
ColumnLimit: '120'
ContinuationIndentWidth: '1'
IndentWidth: '1'
Standard: Latest
TabWidth: '1'
UseCRLF: 'false'
UseTab: ForContinuationAndIndentation

...
```

`main.cpp`:
```cpp
void func()
{
	auto out = utki::linq(std::move(in))
		.select([](auto v) {
			auto r = std::make_pair(std::move(v.second), 13.4f);
			tst::check(v.second.empty(), SL);
			return r;
		})
		.get();
}
```

# command

```console
clang-format main.cpp
```

# expected result

formatting is not changed

# actual result

```cpp
void func() {
	auto out = utki::linq(std::move(in))
													.select([](auto v) {
														auto r = std::make_pair(std::move(v.second), 13.4f);
														tst::check(v.second.empty(), SL);
														return r;
													})
													.get();
}
```
The continuation indentation is wrong.

# version

```console
$ clang-format --version
Debian clang-format version 15.0.0-++20220513071846+693758b28295-1~exp1~20220513071937.249
```

**Comment by iarede** [comment]
@igagis 
You use `IndentWidth` and `ContinuationIndentWidth` equal to 1 column (_space_), and `TabWidth` equal to 1 column (_space_). But your editor treats 1 tab as 8 (_or 2, or 4_) spaces. Consequently, the indentation width increases by 8 (_or 2, or 4_) times. Try the following:
```yaml
ColumnLimit: '120'
ContinuationIndentWidth: '8' # '2' or '4'
IndentWidth: '8' # '2' or '4'
Standard: Latest
TabWidth: '8' # '2' or '4'
UseCRLF: 'false'
UseTab: ForContinuationAndIndentation
```

or change the settings in your editor.

Note: Line 3 indent starts with **u**tki::linq( 
```cpp
void func() {
	auto out = utki::linq(std::move(in))
			   .select([](auto v) {
				   auto r = std::make_pair(std::move(v.second), 13.4f);
				   tst::check(v.second.empty(), SL);
				   return r;
			   })
			   .get();
}
```
