### ISSUE TITLE
[clang-format]: treat double {{}} as single {} in array initialization

### ISSUE THREAD

**Issue by igagis** [llvm/llvm-project#55488]
# input

`.clang-format`:
```yaml
---
AlignAfterOpenBracket: BlockIndent
AlignArrayOfStructures: Right
BinPackArguments: 'false'
ColumnLimit: '120'
ContinuationIndentWidth: '1'
IndentWidth: '1'
Language: Cpp
Standard: Latest
TabWidth: '1'
UseCRLF: 'false'
UseTab: ForContinuationAndIndentation

...
```

`main.cpp`:
```cpp
std::array<str_num_pair, 5> arr = {{
	{"hello"sv, 13},
	{  "bye"sv, 15},
	{  "how"sv, 33},
	{  "are"sv,  4},
	{  "you"sv,  9}
}};
```

# after formatting

```cpp
std::array<str_num_pair, 5> arr = {
	{{"hello"sv, 13}, {"bye"sv, 15}, {"how"sv, 33}, {"are"sv, 4}, {"you"sv, 9}}
};
```

# proposal

when double curly brackets `{{...}}` appear in initializer, treat them as single ones `{ ... }`, i.e. the original code snippet formatting should not change.

**Comment by nyoma-diamond** [comment]
Bumping this as I'm still seeing this behavior in version 21.0.0git. From what I can tell this seems much more like a bug than a design issue. 

The issue appears to be caused by using `std::array` as opposed to standard C-style arrays (i.e., `Type obj[#]`) with structs or similar (e.g., `std::tuple`). It seems ClangFormat fails to handle this correctly, and therefore align the struct initializations wrong. 
I.e., it seems `AlignArrayOfStructures` doesn't respect `std::array` and confusion ensues.

(Also related: https://github.com/llvm/llvm-project/issues/55483 and https://github.com/llvm/llvm-project/issues/51829#issuecomment-981048026)

E.g., given
```c++
struct TestStruct {
    std::string foo;
    int bar;
    float baz;
};
```
A C-style array formats correctly as
```c++
// Normal, expected behavior with C-style arrays
TestStruct testArray1[5] = {
    {"abc",    10, 3.14},
    {"defghi", 5,  0.01},
    {"ghij",   20, 10.0},
    {"klm",    10, 5.00},
    {"nop",    7,  3.14}
};
```
but a C++ `std::array` fails to align and places the braces in odd places:
```c++
// faulty behavior with std::array. columns are not aligned
std::array<TestStruct, 5> testArray2 = {
    {
     {"abc", 10, 3.14},
     {"defghi", 5, 0.01},
     {"ghij", 20, 10.0},
     {"klm", 10, 5.00},
     {"nop", 7, 3.14},
     },
};
```

Interestingly the behavior differs slightly (displays behavior observed by @igagis) when using `std::tuple`/`std::pair` instead of a struct:
```c++
// Normal, expected behavior with C-style arrays
std::tuple<std::string, int, float> testArray3[5] = {
    {"abc",    10, 3.14},
    {"defghi", 5,  0.01},
    {"ghij",   20, 10. },
    {"klm",    10, 5.0 },
    {"nop",    7,  3.14}
};

// faulty behavior with std::array. each should be on its own line and column-aligned
std::array<std::tuple<std::string, int, float>, 5> testArray4 = {
    {{"abc", 10, 3.14}, {"defghi", 5, 0.01}, {"ghij", 20, 10.}, {"klm", 10, 5.0}, {"nop", 7, 3.14}}
};

// faulty behavior with std::array. columns are not aligned
std::array<std::tuple<std::string, int, float>, 5> testArray5 = {
    {{"abc longer so it forces a wrap", 10, 3.14},
     {"defghi longer so it forces a wrap", 5, 0.01},
     {"ghij longer so it forces a wrap", 20, 10.},
     {"klm longer so it forces a wrap", 10, 5.0},
     {"nop longer so it forces a wrap", 7, 3.14}}
};
```


In my case, this is my `.clang-format`:
```YAML
---
BasedOnStyle: Chromium
IndentWidth: 4
UseTab: Never
ColumnLimit: 120

AlignAfterOpenBracket: BlockIndent   # Occurs whether this is enabled or not
BreakBinaryOperations: RespectPrecedence
BreakBeforeBinaryOperators: NonAssignment
BinPackParameters: OnePerLine
BinPackArguments: true
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AlignArrayOfStructures: Left

...

```


Are there any thoughts on this?
