### ISSUE TITLE
clang-tidy with --export-fixes doesn't apply formatting (but it works with --fix)

### ISSUE THREAD

**Issue by sean-mcmanus** [llvm/llvm-project#55569]
I'm using clang-tidy 14.0.3 (on Windows 11, I could try Linux/Mac if you want, but I assume it doesn't matter).

Use test.cpp
```cpp

int main()
{
    if (true)
        return 0;
}
```
with some .clang-format file in the folder like
```yaml
BasedOnStyle: LLVM
UseTab: Never
IndentWidth: 4
TabWidth: 4
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
AccessModifierOffset: -4
NamespaceIndentation: All
FixNamespaceComments: false
SeparateDefinitionBlocks: Always
```
and run `clang-tidy.exe --config="{Checks: 'readability-braces-around-statements', FormatStyle: file}" --export-fixes=<path>/out.yaml <path>/test.cpp --`

Bug: The out.yaml is
```yaml
---
MainSourceFile:  '<path>/test.cpp'
Diagnostics:
  - DiagnosticName:  readability-braces-around-statements
    DiagnosticMessage:
      Message:         statement should be inside braces
      FilePath:        '<path>/test.cpp'
      FileOffset:      30
      Replacements:
        - FilePath:        '<path>/test.cpp'
          Offset:          30
          Length:          0
          ReplacementText: ' {'
        - FilePath:        '<path>/test.cpp'
          Offset:          49
          Length:          0
          ReplacementText: "\n}"
    Level:           Warning
    BuildDirectory:  '<path>'
...
```

which doesn't have the formatting applied -- in particular, the `}` has no indentation.

The bug doesn't repro when --export-fixes isn't used: `clang-tidy.exe --config="{Checks: 'readability-braces-around-statements', FormatStyle: file}" --fix <path>/test.cpp --` gives the expected result:
```

int main()
{
    if (true)
    {
        return 0;
    }
}
```

It also repros with `clang-tidy.exe --config="{Checks: 'modernize-concat-nested-namespaces', FormatStyle: file}" --export-fixes=<path>/out.yaml <path>/test.cpp -- -std=c++17`.

with test.cpp

```cpp

namespace foo1
{
    namespace foo2
    {
        int i;
    }
}
```

so it seems like it may repro with all checks.

I'm guessing we could work around the issue via running clang-format on the edited lines afterwards.
