### ISSUE TITLE
clang-format: BreakBeforeBinaryOperators doesn't seem to work correctly

### ISSUE THREAD

**Issue by Zingam** [llvm/llvm-project#55640]
```yml
---
Language: Cpp
Standard: Latest
BasedOnStyle: Mozilla
#AlignAfterOpenBracket: BlockIndent
AlignAfterOpenBracket: AlwaysBreak
AlignOperands: AlignAfterOperator
BreakBeforeBinaryOperators: NonAssignment
IndentPPDirectives: AfterHash
...
```

I get this result:

```C++
[[nodiscard]] auto
ass(
  int i,
  int atertertertertertertertert,
  int e,
  int arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd)
  -> int
{
  auto a =
    i + atertertertertertertertert & 1
    | 2 + arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
        + e;
  return i + atertertertertertertertert
       + arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
       + e + a;
}
```

I would expect somethig like this:

```C++
[[nodiscard]] auto
ass(
  int i,
  int atertertertertertertertert,
  int e,
  int arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd)
  -> int
{
  auto a = i
             + atertertertertertertertert 
             & 1
             | 2 
             + arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
             + e;
  return i 
       + atertertertertertertertert
       + arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
       + e 
       + a;
}
```

even better:

```C++
[[nodiscard]] auto
ass(
  int i,
  int atertertertertertertertert,
  int e,
  int arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd)
  -> int
{
  auto a = i
    + atertertertertertertertert 
    & 1
    | 2 
    + arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
    + e;
  return i 
    + atertertertertertertertert
    + arfdadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
    + e 
    + a;
}
```
