### ISSUE TITLE
clang-format: constructor initializers are not formatted after a requires clause

### ISSUE THREAD

**Issue by elevendroids** [llvm/llvm-project#56215]
Hello again :grin:  
Take a look at the following example:

```c++
template <typename T>
struct Foo {

    constexpr Foo(int value_)
    : value{value_}
    {
        do_magic();
        do_more_magic();
    }

    template<typename U>
    requires std::is_copy_constructible<T>
    constexpr Foo(Foo<U> const & other)
    : value{other.value}
    {
        do_magic();
        do_more_magic();
    }

    constexpr Foo(Foo const & other) requires std::is_copy_constructible<T>
    : value{other.value}
    {
        do_magic();
        do_more_magic();
    }

    constexpr Foo(Foo const & other) requires (std::is_copy_constructible<T>)
    : value{other.value}
    {
        do_magic();
        do_more_magic();
    }

    int value;
};
```

Formatting this with `--style="{BasedOnStyle: llvm, BreakConstructorInitializers: BeforeColon, ConstructorInitializerIndentWidth: 4, PackConstructorInitializers: Never}"` produces this output:

```c++
template <typename T> struct Foo {
// OK
  constexpr Foo(int value_)
      : value{value_} {
    do_magic();
    do_more_magic();
  }
// OK
  template <typename U>
    requires std::is_copy_constructible<T>
  constexpr Foo(Foo<U> const &other)
      : value{other.value} {
    do_magic();
    do_more_magic();
  }
// Not OK - initializers list not indented
  template <typename U>
  constexpr Foo(Foo<U> const &other)
    requires std::is_copy_constructible<T>
  : value{other.value} {
    do_magic();
    do_more_magic();
  }

// Not OK - initializers list not indented
  constexpr Foo(Foo const &other)
    requires std::is_copy_constructible<T>
  : value{other.value} {
    do_magic();
    do_more_magic();
  }

// Not OK - initializers list not indented
  constexpr Foo(Foo const &other)
    requires(std::is_copy_constructible<T>)
  : value{other.value} {
    do_magic();
    do_more_magic();
  }

  int value;
};

```

Version tested:
clang-format version 15.0.0 (https://github.com/llvm/llvm-project.git 1f69f7ea9af4bd4e8001a25044aa026557f366f7)

Platform:
Arch Linux, x86_64

**Comment by mkurdej** [comment]
@HazardyKnusperkeks, may it be related to #56176 (and so possibly fixed by https://github.com/llvm/llvm-project/commit/b3aeca3962bb39dfe110472ea033bda32044455d)?
@elevendroids, could you test it with the current main please?

**Comment by elevendroids** [comment]
@mkurdej Unfortunately, this is not related to the previous bug (also reported by me, works fine now) - here I've used 1f69f7e (see description) which is from day after the b3aeca3 merged.

**Comment by JohelEGP** [comment]
My case:
```C++
struct unit {
  [[nodiscard]] constexpr unit(const std::string_view symbol) noexcept /*requires(N == 0)*/
    : symbol{symbol}, description{} {}
  [[nodiscard]] constexpr unit(const std::string_view symbol) noexcept requires(N == 0)
  : symbol{symbol}, description{} {}
};

```
```yaml
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortFunctionsOnASingleLine: All
BreakConstructorInitializers: BeforeColon
ColumnLimit: 120
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
IndentRequiresClause: true
IndentWidth: 2
IndentWrappedFunctionNames: false
Language: Cpp
PackConstructorInitializers: NextLine
RequiresClausePosition: SingleLine
SpaceBeforeCtorInitializerColon: true
Standard: Latest
TabWidth: 2
```
