### ISSUE TITLE
clang-format misaligns comments when indenting preprocessor directives with BeforeHash

### ISSUE THREAD

**Issue by bradlitterell** [llvm/llvm-project#56326]
Seems like clang-format is attempting to align comments with a `#define`, but incorrectly uses `IndentWidth` instead of `PPIndentWidth` if they differ.

Example:

Output:
```cpp
#if 1
// not a define comment
int x = 3;
    // some comments
    // another
  #define foo 1
  #define vbarrr 2
  #define something_else_very_long
#endif
```

Format:
```yaml
---
Language:        Cpp
BasedOnStyle: LLVM
IndentPPDirectives: BeforeHash
IndentWidth: 4
PPIndentWidth: 2
...
```

Input Source:
```cpp
#if 1
// not a define comment
int x = 3;
// some comments
// another
#define foo 1
#define vbarrr 2
#define something_else_very_long
#endif
```
