### ISSUE TITLE
[clang-format] AlignConsecutiveAssignments with enumerated scalar

### ISSUE THREAD

**Issue by Creepercdn** [llvm/llvm-project#56407]
```yaml
AlignConsecutiveAssignments:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: true
  PadOperators: false
```
raises a error:
```shellsession
.clang-format:2:3: error: unknown enumerated scalar
  Enabled: true
  ^
```
but it is documented: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
