### ISSUE TITLE
[clang-format] insert and/or preserve newlines preceding a closing brace.

### ISSUE THREAD

**Issue by ancientjpeg** [llvm/llvm-project#56659]
Apologies if there is a setting for this, I wasn't able to find anything that could do what I'm looking for in the docs! At my job, we generally style code with a lot of extra space, like so: 

```cpp
if (mCondition) {

    doSomething();

}
```

however, no matter what I try, I can't stop clang-format from doing the following: 

```cpp
if (mCondition) {

    doSomething();
}
```

Here's my .clang-format: 

```yaml
AlignAfterOpenBracket: Align
AllowShortFunctionsOnASingleLine: Empty
BreakBeforeBraces: Linux
BreakInheritanceList: AfterComma
ColumnLimit: 0
IndentCaseLabels: True
IndentWidth: 4
PointerAlignment: Left
MaxEmptyLinesToKeep: 2
```

Thanks in advance for any help you can offer, ++ thanks to the team for making the best formatter out there!
