### ISSUE TITLE
[clang-tidy] ConstantParameterCase for references

### ISSUE THREAD

**Issue by hedtke** [llvm/llvm-project#57001]
`ConstantParameterCase` is not applied to constant references. Am I missing another parameter or is that a bug?

My `.clang-tidy`:

```yaml
Checks: '-*,readability-identifier-naming'
FormatStyle: 'file'
CheckOptions:
  - { key: readability-identifier-naming.ParameterCase, value: camelBack }
  - { key: readability-identifier-naming.ConstantParameterCase, value: UPPER_CASE }
```

My Code:

```cpp
#include <iostream>

int test(int const& I) {
	return I + 1;
}

int main()
{
	std::cout << test(43) << std::endl;
	return 0;
}
```

`clang-tidy` output:

```
$ clang-tidy main.cpp

Running without flags.
1 warning generated.
/Users/ivhedtke/.../main.cpp:3:21: warning: invalid case style for parameter 'I' [readability-identifier-naming]
int test(int const& I) {
                    ^
                    i
```
