### ISSUE TITLE
clang-format adds space in macro call that causes answer difference

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#57156]
Given:

```c++
#include <string.h>
#include <iostream>

#define CHECK(a) strcmp("one:two:three", #a)

int main() {
    std::cout << "CHECK = " << CHECK(one:two:three) << '\n';
    return 0;
}

```

and `_clang_format`:

```yaml
---
BasedOnStyle: Google
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: true
...

```
Running clang-format 13 or 14 gives:

```c++
#include <string.h>

#include <iostream>

#define CHECK(a) strcmp("one:two:three", #a)

int main() {
    std::cout << "CHECK = " << CHECK(one:two : three) << '\n';
    return 0;
}

```

Notice that spaces have been added around the second colon in the CHECK macro call. This causes the
answers to differ.
