### ISSUE TITLE
Short functions within macro clang-format regression in 15.x prerelease

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#57200]
Given:

```c++
#define Foo(ArgType, SetName)                    \
    void Bar::set##SetName(ArgType a##SetName) { \
        f##SetName = std::move(a##SetName);      \
    }
```

and `_clang-format`:

```yaml
---
BasedOnStyle: Google
ColumnLimit: 100
IndentWidth: 4
AllowShortFunctionsOnASingleLine: Empty
...
```

clang-format 13 and 14 yield the expect result (above). However, clang-format 15.x prerelease (commit 64260fe on Aug-17-2022)
does not honor `AllowShortFunctionsOnASingleLine: Empty` and produces:

```c++
#define Foo(ArgType, SetName) \
    void Bar::set##SetName(ArgType a##SetName) { f##SetName = std::move(a##SetName); }
```

Interestingly if you remove the ColumnLimit from _clang-format, clang-format 15.x prerelease behaves correctly.
