### ISSUE TITLE
regression in continuation indent in clang-format 15.x

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#57303]
Given:

```c++
void foo() {
    foobar::foobar_xyarray_ptr mxOtherActionsPtr(foobar::from_other2(xyOtherActions));
    testDiagnostic errmsg = evaluate2_NoThrow(
        "xyprivate",
        in_args("xyz...............................................................", test2Path,
                realProperty, internalVal, false, xyOtherActionsPtr),
        out_args(xyAllActionsPtr));
}

```

and `_clang-format`:

```yaml
---
BasedOnStyle: Google
ColumnLimit: 100
IndentWidth: 4
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: Consecutive
...
```

clang-format 13 and 14 yield correct continuation indent (above). However, clang-format 15.x
prerelease (commit 006b649 on Aug-22-2022) produces unexpected continuation indent for the line
starting with realProperty.

```c++
void foo() {
    foobar::foobar_xyarray_ptr mxOtherActionsPtr(foobar::from_other2(xyOtherActions));
    testDiagnostic             errmsg = evaluate2_NoThrow(
        "xyprivate",
        in_args("xyz...............................................................", test2Path,
                            realProperty, internalVal, false, xyOtherActionsPtr),
        out_args(xyAllActionsPtr));
}
```

One other note, clang-format 15.x does align the consecutive statements 13 and 14 do not, so
that is an improvement in 15.x.
