### ISSUE TITLE
clang-tidy readability-identifier-naming fails for template template parameters

### ISSUE THREAD

**Issue by marcin-szmagara** [llvm/llvm-project#57426]
Consider following `c++20` code:
```C++
template <template <typename> typename T>
constexpr bool always_true = true;

template <typename T>
using change_to_camel_case = void;

int main()
{
  always_true<change_to_camel_case>;
}
```
and following `.clang-tidy` config file:
```yaml
---
Checks: '-*, readability-identifier-naming'

FormatStyle:     file
CheckOptions:
  - { key: readability-identifier-naming.TypeAliasCase, value: CamelCase  }
...
```
Both `clang-tidy` with `--fix` option and `clangd` using code-actions, rename the type alias at it's definition, but not at it's usage. In other words, the output file is:
```C++
template <template <typename> typename T>
constexpr bool always_true = true;

template <typename T>
using ChangeToCamelCase = void;

int main()
{
  always_true<change_to_camel_case>;
}
```
