### ISSUE TITLE
clang-format: Namespace name comments after closing brace misaligned/indented with more than 2 nested namespaces and AlignTrailingComments: true

### ISSUE THREAD

**Issue by TriazoneZero** [llvm/llvm-project#57504]
Hello,

I am using clang-format 14 and in my `.clang-format` file, if have set the following parameters that affect the namespaces:
```yaml
AlignTrailingComments: true
CompactNamespaces: false
FixNamespaceComments: true
NamespaceIndentation: All
ShortNamespaceLines: 0
BraceWrapping:
  AfterNamespace: true
  SplitEmptyNamespace: true
```

If I have a more than two namespaces, I encounter the following formatting:
```cpp
namespace A
{
    namespace B
    {
        namespace C
        {
            namespace D
            {
                namespace E
                {

                }  // namespace E
            }      // namespace D
        }          // namespace C
    }              // namespace B
}  // namespace A
```

Which shows that the `AlignTrailingComments` parameter provokes this formatting, which is wrong to me. Whether all namespace comments should be indented or none. I would prefer **none**. If I set
```yaml
AlignTrailingComments: false
```
and leave the rest as is, I get the behavior I would expect here:

```cpp
namespace A
{
    namespace B
    {
        namespace C
        {
            namespace D
            {
                namespace E
                {

                }  // namespace E
            }  // namespace D
        }  // namespace C
    }  // namespace B
}  // namespace A
```
