### ISSUE TITLE
[clang-format] wrong formatting of initializer list

### ISSUE THREAD

**Issue by paolo-mastrapasqua** [llvm/llvm-project#57518]
Input code:
```cpp
    struct TestParams
    {
        std::chrono::nanoseconds notificationPeriod;
        std::chrono::nanoseconds timeout;
    };

    std::vector<TestParams> testParams = {
        {
            std::chrono::nanoseconds{0},        // Don't notify condition variable
            std::chrono::nanoseconds{1'000'000} // 1ms
        },
        {
            std::chrono::nanoseconds{0},         // Don't notify condition variable
            std::chrono::nanoseconds{10'000'000} // 10ms
        },
        {
            std::chrono::nanoseconds{0},          // Don't notify condition variable
            std::chrono::nanoseconds{100'000'000} // 100ms
        },
        {
            std::chrono::nanoseconds{0},            // Don't notify condition variable
            std::chrono::nanoseconds{2'000'000'000} // 2s
        },
    };
```

Output code:
```cpp
    struct TestParams
    {
        std::chrono::nanoseconds notificationPeriod;
        std::chrono::nanoseconds timeout;
    };

    std::vector<TestParams> testParams = {
        {
         std::chrono::nanoseconds{0},     // Don't notify condition variable
     std::chrono::nanoseconds{1'000'000} // 1ms},
        {
         std::chrono::nanoseconds{0},   // Don't notify condition variable
   std::chrono::nanoseconds{10'000'000} // 10ms},
        {
         std::chrono::nanoseconds{0}, // Don't notify condition variable
 std::chrono::nanoseconds{100'000'000} // 100ms},
        {
         std::chrono::nanoseconds{0},  // Don't notify condition variable
  std::chrono::nanoseconds{2'000'000'000} // 2s},
    };
```
As you can see, the internal `},` sequences end up in the comments on the previous lines, making the resulting code illegal.

I'm using version 14.0.6, with the following configuration file:
```
---
Language: Cpp
# BasedOnStyle:  LLVM
AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AlignArrayOfStructures: Right
AlignConsecutiveMacros: true
AlignConsecutiveAssignments: true
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Left
AlignOperands: true
AlignTrailingComments: true
AllowAllArgumentsOnNextLine: true
AllowAllConstructorInitializersOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortLambdasOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: Never
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: Yes
BinPackArguments: false
BinPackParameters: false
BraceWrapping:
  AfterCaseLabel: true
  AfterClass: true
  AfterControlStatement: true
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: true
  AfterObjCDeclaration: true
  AfterStruct: true
  AfterUnion: true
  AfterExternBlock: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: true
  BeforeWhile: true
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Custom
BreakBeforeInheritanceComma: false
BreakInheritanceList: BeforeComma
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
BreakConstructorInitializers: BeforeComma
BreakAfterJavaFieldAnnotations: false
BreakStringLiterals: true
ColumnLimit: 120
CommentPragmas: "^ IWYU pragma:"
CompactNamespaces: false
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DeriveLineEnding: true
DerivePointerAlignment: false
DisableFormat: false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: Always
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
ForEachMacros:
  - foreach
  - Q_FOREACH
  - BOOST_FOREACH
IncludeBlocks: Regroup
IncludeCategories:
  - Regex: "^<"
    Priority: 1
    SortPriority: 0
  - Regex: '^"(gtest|gmock|fmt|xercesc|boost|CLI|uuid|dds|refl|magic_enum|xtypes)'
    Priority: 2
    SortPriority: 0
  - Regex: '^"hrtf'
    Priority: 3
    SortPriority: 0
  - Regex: ".*"
    Priority: 4
    SortPriority: 0
IncludeIsMainRegex: "(Test)?$"
IncludeIsMainSourceRegex: ""
IndentCaseLabels: false
IndentExternBlock: AfterExternBlock
IndentGotoLabels: true
IndentPPDirectives: None
IndentWidth: 4
IndentWrappedFunctionNames: false
JavaScriptQuotes: Leave
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: true
MacroBlockBegin: ""
MacroBlockEnd: ""
MaxEmptyLinesToKeep: 1
NamespaceIndentation: All
ObjCBinPackProtocolList: Auto
ObjCBlockIndentWidth: 2
ObjCSpaceAfterProperty: false
ObjCSpaceBeforeProtocolList: true
PenaltyBreakAssignment: 2
PenaltyBreakBeforeFirstCallParameter: 19
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakString: 1000
PenaltyBreakTemplateDeclaration: 10
PenaltyExcessCharacter: 1000000
PenaltyReturnTypeOnItsOwnLine: 60
PointerAlignment: Left
ReferenceAlignment: Left
ReflowComments: true
SortIncludes: true
SortUsingDeclarations: true
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: true
SpaceAroundPointerQualifiers: Before
SpaceBeforeAssignmentOperators: true
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: false
SpaceInEmptyBlock: false
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false
SpacesInConditionalStatement: false
SpacesInContainerLiterals: true
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
SpaceBeforeSquareBrackets: false
Standard: Latest
StatementMacros:
  - Q_UNUSED
  - QT_REQUIRE_VERSION
TabWidth: 4
UseCRLF: false
UseTab: Never
```
