### ISSUE TITLE
Clang format crashed - Setting AlignArrayOfStructures on Left align and last struct comment

### ISSUE THREAD

**Issue by Komediruzecki** [llvm/llvm-project#57558]
The clang format 13 option - `AlignArrayOfStructures` (`ArrayInitializerAlignmentStyle`) - crashes on left alignment of arrays.

e.g., code:

```cpp
struct CFG_INTERRUPT_STRUCT {
    uint16_t maxNumber;        //!< Maximum number of interrupts in period
    uint16_t floodPeriod;      //!< Interrupt flooding period
    uint16_t minDisablePeriod; //!< Minimum period for which the interrupt will be disabled after the flood
};

CFG_INTERRUPT_STRUCT cfg_test[1] = {
    {
     .floodPeriod      = 3u, // other comments do not crash the format, just last one
     .maxNumber        = 60u,
     .minDisablePeriod = 2500u, // the comment crashes clang-format !CRASH!
    }
};
```

Crashes the clang-format with the log trace below, when the last comment is added, other comments are not affected, without the comment it formats without crash.

Configuration

Version: v14.0.6

```yaml
---
BasedOnStyle: LLVM
# For option description see: https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormatStyleOptions.html
# General Settings (tabs, spaces, limits)
Language: Cpp
Standard: Auto
ReflowComments: false
DisableFormat: false
ColumnLimit: 120
UseTab: Never
UseCRLF: false # clang-format 11
TabWidth: 4
IndentWidth: 4
ContinuationIndentWidth: 8 # Two tabs
IndentCaseLabels: true
IndentWrappedFunctionNames: true
IndentPPDirectives: None
IndentGotoLabels: false    # clang-format 10
IndentCaseBlocks: false    # clang-format 11
IndentExternBlock: Indent  # clang-format 12
PPIndentWidth: -1          # clang-format 14 - no indent, default
#InsertTrailingCommas: Wrapped # clang-format 12 - only for Javascript
# Spaces
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: Never
SpaceInEmptyParentheses: false
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInSquareBrackets: false
SpaceAfterLogicalNot: false
SpaceAfterCStyleCast: true
SpacesInConditionalStatement: false # clang-format 11
SpaceBeforeSquareBrackets: false    # clang-format 11
SpaceInEmptyBlock: false            # clang-format 11
SpaceAroundPointerQualifiers: After # clang-format 12
SpaceBeforeCaseColon: false         # clang-format 12
SeparateDefinitionBlocks: Leave     # clang-format 14
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 1
# Penalties
# This decides in what order things should be done if a line is too long
PenaltyBreakAssignment: 100
PenaltyBreakBeforeFirstCallParameter: 10
PenaltyBreakComment: 10
PenaltyBreakFirstLessLess: 0
PenaltyBreakString: 10
PenaltyExcessCharacter: 60
PenaltyReturnTypeOnItsOwnLine: 400 # out of reach to avoid this
PenaltyBreakTemplateDeclaration: 0 # C++
PenaltyBreakOpenParenthesis: 10
# Alignments
AlignAfterOpenBracket: DontAlign
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: None
AlignConsecutiveBitFields: Consecutive
AlignConsecutiveMacros: AcrossComments
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments: true
PointerAlignment: Right
DerivePointerAlignment: false

AlignArrayOfStructures: Left # clang-format 13
QualifierAlignment: Custom   # clang-format 14
QualifierOrder:
  - 'restrict'
  - 'inline'
  - 'static'
  - 'const'
  - 'constexpr' # for cpp
  - 'type'
# Allowances
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Always
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: Never
AllowShortLoopsOnASingleLine: false
# clang-format 12
AllowShortEnumsOnASingleLine: false
# Breaks
# Deprecated - retained for backwards compatibility
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None # PenaltyReturnTypeOnItsOwnLine is taken into account
AlwaysBreakBeforeMultilineStrings: false
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Attach # Could be set to Custom and then configured per brace type (function, ifs, enums)
BreakBeforeTernaryOperators: false # todo: maybe set to true to get cleaner ternary
BreakStringLiterals: false
# clang-format 12
AttributeMacros:
  - 'ASIL_A_B_CODE'
  - 'ASIL_C_D_CODE'
  - 'ASIL_C_D_BSS'
BitFieldColonSpacing: Both
# Other
# Could be useful for not formatting comments matched with a regex
CommentPragmas: '@(ref|p|param|li|warning|ingroup|author|related|relates|date|relatesalso|deprecated|image|brief|attention|copydoc|addtogroup|todo|tparam|see|note|skip|skipline|until|line|dontinclude|include) '
MaxEmptyLinesToKeep: 2
Cpp11BracedListStyle: false
KeepEmptyLinesAtTheStartOfBlocks: true
# File include management
SortIncludes: CaseInsensitive
IncludeBlocks: Regroup
IncludeCategories:
  # Module includes
  - Regex: '^"(mdl).*'
    Priority: 4
    SortPriority: 4
  # Configuration includes
  - Regex: '^"(cfg_mdl).*'
    Priority: 3
    SortPriority: 3
  # Submodule includes
  - Regex: '^"(isotp|uds|utils|xcp|bsp|drv|mcu).*'
    Priority: 2
    SortPriority: 2
  # Everything else (not organized, stdlib, ewl_c, other libraries)
  - Regex: '<[[:alnum:].]+>'
    Priority: 1
    SortPriority: 1
#IncludeIsMainRegex: ""

# List of macros which would start a block (and then be indented properly)
# Add regexes as needed
#MacroBlockBegin: "Regexp"
#MacroBlockEnd: "Regexp"

# clang-format 14 - CPP
#EmptyLineAfterAccessModifier: Leave
#EmptyLineBeforeAccessModifier: LogicalBlock
IfMacros:
  - 'NULL_CHECK1'
  - 'NULL_CHECK2'
  - 'NULL_CHECK3'
  - 'NULL_CHECK4'
# clang-format 12
WhitespaceSensitiveMacros:
  - 'NULL_CHEKC1'
  - 'NULL_CHEKC2'
  - 'NULL_CHEKC3'
  - 'NULL_CHEKC4'
```

```console
Stack dump:
Stack dump:
0.	Program arguments: "C:\\Program Files\\LLVM\\bin\\clang-format.exe" -assume-filename=C:\\Users\\<user-name>\\sw_projects\\<project_name>\\<project>\\<project>\\app\\config\\modules\\production\\cfg_mdl_iat.c -style=file -fallback-style=Google -offset=0 -length=4368
 #0 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0xbe843 C:\Program Files\LLVM\bin\clang-format.exe 0xbe319
 #1 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0xbcd39 C:\Program Files\LLVM\bin\clang-format.exe 0xb9ef7
 #2 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x86397 C:\Program Files\LLVM\bin\clang-format.exe 0xa2519
 #3 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x94664 C:\Program Files\LLVM\bin\clang-format.exe 0x7dd6e
 #4 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x7ec69 C:\Program Files\LLVM\bin\clang-format.exe 0x545c
 #5 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x385b C:\Program Files\LLVM\bin\clang-format.exe 0x1843d8
 #6 0x00007ff6c62ee843 (C:\Program Files\LLVM\bin\clang-format.exe+0xbe843)
 #7 0x00007ff6c62ee319 (C:\Program Files\LLVM\bin\clang-format.exe+0xbe319)
0x00007FF6C62EE843 (0x0000000000000000 0x0000003C00000000 0x0000000100000000 0x000000DC5C38AE20)
0x00007FF6C62EE319 (0x000000DC5C38B2D8 0x0000003C00000000 0x000000DC5C38CA00 0x000000DC00000000)
0x00007FF6C62ECD39 (0x0000000000000000 0x000000DC00000000 0x000000DC5C38AF18 0x00007FF96967F05B)
0x00007FF6C62E9EF7 (0x0000027544C3FF20 0x0000000000000000 0x0000000000000000 0x0000001000000000)
0x00007FF6C62B6397 (0x000000DC5C38BC80 0x00007FF6C62D292E 0x0000000000000000 0x0000000000000000)
0x00007FF6C62D2519 (0x0000000000000000 0x0000000000000009 0x0000027544C10320 0x0000027544C40ED0)
0x00007FF6C62C4664 (0x0000027544C3C170 0x0000000000000000 0x0000027544C3C7A0 0x0000000000000038)
0x00007FF6C62ADD6E (0x0000027544C237F0 0x00007FF96BE147B1 0x0000000000000000 0x0000027544C10000)
0x00007FF6C62AEC69 (0x0000027544C1D2E4 0x0072006700000000 0x0000027544C1D2B0 0x0000000000340032)
0x00007FF6C623545C (0x0000027544C17300 0x000000000000000E 0x0000000000000000 0x0000027544C15310)
0x00007FF6C623385B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF6C63B43D8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF96A577034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF96BE42651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```
