### ISSUE TITLE
[clang-format] Allow space after return type in template argument of std::function

### ISSUE THREAD

**Issue by marv** [llvm/llvm-project#57972]
I'm trying to introduce clang-format to a codebase that formats `std::function`'s with a space inbetween the return type and the function parameters:
```
std::function<ReturnType (ArgType a)>
```
and `clang-format` wants to change this to
```
std::function<ReturnType(ArgType a)>
```

Is there an option to control that behaviour? Or would it be acceptable to add one?

**Comment by swaldhoer** [comment]
You can use ``SpaceBeforeParensOptions`` and then use something like this:

```yaml
# Example of usage:
SpaceBeforeParens: Custom
SpaceBeforeParensOptions:
  AfterFunctionDefinitionName: true
 # set other options of SpaceBeforeParens as needed
```
