### ISSUE TITLE
[clang-format] AlignCompound gives alignment not by equal signs

### ISSUE THREAD

**Issue by leerg** [llvm/llvm-project#58029]
I have this selected options:
```yaml
AlignConsecutiveAssignments:
  Enabled: true
  AlignCompound: true
```

and it gives this result:
```cpp
 int i = 0;
 i     += 2;
```

but I expect it should be like in [documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html):
```cpp
 int i = 0;
 i    += 2;
```

clang-format version is 15.0.1

**Comment by rymiel** [comment]
I cannot reproduce on `main`, but I also cannot reproduce with clang-format 15

Maybe more context around the snippet or the whole format configuration is required?

**Comment by leerg** [comment]
@rymiel, yes sure.
Full configuration file:
```yaml
Language: Cpp
Standard: c++14

UseTab: Never
IndentWidth: 4
TabWidth: 4
AccessModifierOffset: -4

AlignConsecutiveAssignments:
  Enabled: true
  AlignCompound: true
```

input file: 
```cpp
int main(int argc, const char * argv[])
{
	int i = 0;
	i += 2;
}
```

and the output after formating:
```cpp
int main(int argc, const char *argv[]) {
    int i = 0;
    i     += 2;
}
```
