### ISSUE TITLE
`readability-identifier-naming` reports nothing but does something when no `CheckOptions` are provided

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#58096]
https://github.com/llvm/llvm-project/issues/57527#issuecomment-1237935132 indicates that `readability-identifier-naming` is one of the heavier clang-tidy checks. But it seems that it doesn't do anything until you actually provide `CheckOptions`.

Running `-dump-config` only shows the following default values:
```yaml
CheckOptions:
  - key:             readability-identifier-naming.IgnoreFailedSplit
    value:           'false'
  - key:             readability-identifier-naming.AggressiveDependentMemberLookup
    value:           'false'
  - key:             readability-identifier-naming.IgnoreMainLikeFunctions
    value:           'false'
```
