### ISSUE TITLE
[clang-format] Add an option that dictates how alternative-token operators are spelt

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#58115]
Some C++ programmers use alternative tokens instead of symbol tokens. We should have a way to ensure that the tokens can be checked.

```yaml
LogicalOperatorSpelling: Symbol|Words|AsIs|Custom
  LogicalAndSpelling: Symbol|Word|AsIs
  LogicalOrSpelling: Symbol|Word|AsIs
  LogicalNotSpelling: Symbol|Word|AsIs
```
There should also be equivalents for bitwise operators and compound operators.
