### ISSUE TITLE
[clang-format]: no space after trailing comment

### ISSUE THREAD

**Issue by scruel** [llvm/llvm-project#58403]
For clang-format version 15.0.1

`.clang-format`:
```yaml
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: -1
```

Original:
```cpp
int main() {
  int a = 0; //dsa
}
```

Excepted:
```cpp
int main() {
  int a = 0; // dsa
}
```

Actual:
```cpp
int main() {
  int a = 0; //dsa
}
```

**Comment by rymiel** [comment]
I cannot reproduce, are you sure the config is being applied correctly?  
Maybe there are more steps needed?

**Comment by scruel** [comment]
> I cannot reproduce, are you sure the config is being applied correctly? Maybe there are more steps needed?

Sorry, missed options in `.clang-format` file:

```
ReflowComments: false
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: -1
```
