### ISSUE TITLE
[clang-format]: formatting delimiters of raw string 

### ISSUE THREAD

**Issue by PaulSt** [llvm/llvm-project#58435]
I have posted the following question [on stackexchange](https://stackoverflow.com/questions/74102290/clang-format-and-special-delimiters), where is was suggested that it might actually be a bug, so if this is the case, I thought I would report it here. 

I am using a special raw string delimiter in my code to format doc string, it looks something like
```
R"mydelimiter(
    some raw string
)mydelimiter"
```

Now, clang-format likes to produce the following 
```
R "mydelimiter(
    some raw string
) mydelimiter "
```
which actually introduces a compilation error. 
I know that I can mark every block in my code with `// clang-format on/off` but I would like to find a more general solution. 

Here is what I tried so far:
- raw string format in my `.clang-format`
```yaml
RawStringFormats:
  - Language: Cpp
    Delimiters: ['mydelimiter']
```
- as well as several versions of regex macro blocks 
```yaml
MacroBlockBegin: 'R\"mydelimiter\('
MacroBlockEnd: '\)mydelimiter\",'
```
without any success. I am running clang-format version 14.0.6 and also I am running out of ideas :-/ help!

Apart from my tries above, this is my `.clang-format`
```yaml
---
Language: Cpp
BasedOnStyle: GNU
NamespaceIndentation: All
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
PenaltyReturnTypeOnItsOwnLine: 0
SortIncludes: false
---
```
