### ISSUE TITLE
clang-format not correctly formatting braces in function declaration

### ISSUE THREAD

**Issue by RustyClanker** [llvm/llvm-project#58527]
clang-format version 15.0.1, LLVM on Windows 10.

Using separate custom `BreakBeforeBraces` rule in `.clang-format` causes clang-format to handle function definitions incorrectly for struct and enum, if the brace rules for those keywords differ from a function.

```yaml
BreakBeforeBraces: Custom
BraceWrapping:
  AfterEnum: true
  AfterStruct: true
  AfterFunction: false
```

Example after format:

```c
int some_int_func(void) {
    return 0;
}

struct FooStruct return_a_struct(void)
{
    return (struct FooStruct){0};
}
```
