### ISSUE TITLE
[Format] Spaces added to align assignment shouldn't affect further indentation

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#58707]
`.clang-format`:
```yaml
AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveAssignments: Consecutive
ColumnLimit: 120
ContinuationIndentWidth: 2
```

Input and expected output:
```C++
inline constexpr quantity rotational_frequency = {.symbol = "n", .derived = [] { return rotation / time; }};
inline constexpr quantity phase_velocity       = {
  .symbol = "c", .derived = [] { return angular_frequency / angular_repetency; }};
inline constexpr quantity logarithmic_decrement = {
  .symbol = "Λ", .derived = [] { return damping_coefficient * period_duration; }};
```

Actual output:
```C++
inline constexpr quantity rotational_frequency = {.symbol = "n", .derived = [] { return rotation / time; }};
inline constexpr quantity phase_velocity       = {
        .symbol = "c", .derived = [] { return angular_frequency / angular_repetency; }};
inline constexpr quantity logarithmic_decrement = {
  .symbol = "Λ", .derived = [] { return damping_coefficient * period_duration; }};
```

The 6 spaces between `phase_velocity` and `= {` added to align the assignment operators are also added as indentation after the line break.
