### ISSUE TITLE
[clang-format] Excess characters in a line when formatting of BlockIndent.

### ISSUE THREAD

**Issue by red1bluelost** [llvm/llvm-project#59567]
Using the following config on the below code does not properly break the code into BlockIndent as it should. The static_assert line is formatted to exceed 80 character column limit.

From toying around, I noticed that if I changed the angle brackets (`<`, `>`) into parenthesis (`(`, `)`), the line is formatted correctly. 

```yaml
---
Language:                                  Cpp
AlignAfterOpenBracket:                     BlockIndent
ColumnLimit:                               80
...
```
```c++
#include <iterator>
#include <type_traits>

template <typename Category> struct S {
  static_assert(std::is_base_of_v<std::output_iterator_tag, Category> || std::is_base_of_v<std::input_iterator_tag, Category>);
};
```

The correct formatting would be:
```c++
  static_assert(
    std::is_base_of_v<std::output_iterator_tag, Category> ||
    std::is_base_of_v<std::input_iterator_tag, Category>
  );
```
