### ISSUE TITLE
clang-format does bad things with requires + decltype(auto)

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#59578]
`.clang-format`:
```yaml
BasedOnStyle: Google
Standard: Latest
AllowShortCaseLabelsOnASingleLine: true
```

The `decltype(auto)` is on the same line as the requires clause.
```cpp
  template <class T>
    requires(std::same_as<int, T>) decltype(auto)
  oops() {}
```

Inserting `//clang-format off` makes it worse
```cpp
  template <class T>
  // clang-format off
    requires(std::same_as<int, T>)
      // clang-format on
      decltype(auto)
    oops() {}
```
