### ISSUE TITLE
clang-format doesn't align compound assignment

### ISSUE THREAD

**Issue by songziming** [llvm/llvm-project#59895]
Content of `.clang-format`:

``` yaml
AlignConsecutiveAssignments:
    Enabled: true
    AlignCompound: true
```

C file to be formatted:

```c
int my_func(int y) {
  y           = y + 15;
  y       += 7;
  y   &= ~7;
  return y;
}
```

Format result:

```c
int my_func(int y) {
  y = y + 15;
  y += 7;
  y &= ~7;
  return y;
}
```

But if the file content is:

```c
var          = 5;
var     += 321;
var &= 7;
```

Format result is correct:

```c
var  = 5;
var += 321;
var &= 7;
```
