### ISSUE TITLE
clang-format LambdaBodyIndentation=OuterScope doesn't work correctly with BraceWrapping.BeforeLambdaBody=1

### ISSUE THREAD

**Issue by eugeneko** [llvm/llvm-project#59954]
When I use `LambdaBodyIndentation=OuterScope` with `BraceWrapping.BeforeLambdaBody=1`, brace is over-indented.
Here is the inputs and outputs.

```yaml
# .clang-format
---
Language: Cpp

BraceWrapping:
  BeforeLambdaBody: true
BreakBeforeBraces: Custom
LambdaBodyIndentation: OuterScope
```

```cpp
// input.cpp
int main()
{
	foo();
	bar([]() {foo(); foo();});
}
```

```cpp
// output.cpp
int main() {
  foo();
  bar(
      []()
      { //< the fuck
    foo();
    foo();
  });
}
```

I would expect this:

```cpp
// output.cpp
int main() {
  foo();
  bar(
      []()
  {
    foo();
    foo();
  });
}
```

clang-format version 15.0.3 (https://github.com/llvm/llvm-project 4a2c05b05ed07f1f620e94f6524a8b4b2760a0b1)
