### ISSUE TITLE
Incorrect clang-format pointer alignment when variables are declared in conditionals

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#60146]
Given:

```c++
void foo1(const T1* p1) {
    if (T2* v; check(&v, p1)) {
        goo(v);
    }
}
```

and `_clang-format`:

```yaml
---
BasedOnStyle: Google
IndentWidth: 4
# Google style default is PointerAlignment: Left,
PointerAlignment: Left
...
```

clang-format 15 yields the following. Notice the pointer alignment is no longer left, despite
asking for it to be left.

```c++
void foo1(const T1* p1) {
    if (T2 * v; check(&v, p1)) {
        goo(v);
    }
}
```

In this case, we scoped the variable declaration in the if conditional. If we move it out of the
conditional, pointer alignment is as expected:

```c++
void foo2(const T1* p1) {
    T2* v;
    if (check(&v, p1)) {
        goo(v);
    }
}
```
