### ISSUE TITLE
clang-tidy considers namespace scope static variables to be global variables in several checks

### ISSUE THREAD

**Issue by jmzeeman** [llvm/llvm-project#60915]
I don't think considering these the same as true globals is right as they have internal linkage. 

Given this code:
```c
static int x;

int f(void)
{
    return x;
}
```

With for example these checks:
```yml
  Checks: >
    readability-identifier-naming,
    cppcoreguidelines-avoid-non-const-global-variables
  CheckOptions:    
    - { key: readability-identifier-naming.GlobalVariablePrefix, value: g_ }
    - { key: readability-identifier-naming.GlobalVariableCase, value: lower_case }
```

The output is:
```console
test.c:1:12: warning: variable 'x' is non-const and globally accessible, consider making it const [cppcoreguidelines-avoid-non-const-global-variables]
static int x;
           ^
test.c:1:12: warning: invalid case style for global variable 'x' [readability-identifier-naming]
static int x;
           ^
           global_x
```
