### ISSUE TITLE
Format, IntegerLiteralSeparator not correct with literal suffix

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#61676]
`auto NR = 0x4000'0000_u64;` becomes `auto NR = 0x4'0000'000_u64;` for config:
````yml
IntegerLiteralSeparator:
  Binary:          4
  Decimal:         0
  Hex:             4
````
I would expect the first.

Note that literal is defined in the following way (in another header):
```cpp
   constexpr auto operator"" _u64(unsigned long long value) noexcept -> std::uint64_t
   {
      return static_cast<std::uint64_t>(value);
   }
```

It feels like it considers the `_` as part of the number. Though this is needed according to https://en.cppreference.com/w/cpp/language/user_literal
> All ud-suffixes introduced by a program must begin with the underscore character _. The standard library ud-suffixes do not begin with underscores.

Bug found on LLVM 16, was not a problem in LLVM 16-rc2
