### ISSUE TITLE
BinPackParameters splits template-template parameters in two

### ISSUE THREAD

**Issue by brevzin** [llvm/llvm-project#61732]
This class template:

```cpp
template <typename AAA, typename BBB, typename CCC, template <typename> class DDD>
class SomeTemplate;
```

with this `.clang-format`

```yml
BasedOnStyle: llvm

AccessModifierOffset: -4
AlignConsecutiveBitFields: Consecutive
AlignEscapedNewlines: Right
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortFunctionsOnASingleLine: true
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
BreakBeforeBraces: Custom
BreakConstructorInitializers: BeforeComma
BraceWrapping:
  BeforeElse: true
  BeforeCatch: true
ColumnLimit: 80
ConstructorInitializerAllOnOneLineOrOnePerLine: true
IndentWidth: 4
NamespaceIndentation: None
PenaltyBreakAssignment: 60
PenaltyBreakBeforeFirstCallParameter: 175
PointerAlignment: Left
QualifierAlignment: Custom
QualifierOrder: ['static', 'inline', 'constexpr', 'type', 'const', 'volatile']
SortIncludes: true
SortUsingDeclarations: true
SpaceAfterCStyleCast: true
SpaceAfterTemplateKeyword: true
SpacesBeforeTrailingComments: 2
SpacesInSquareBrackets: false
```

ends up formatting as:

```cpp
template <typename AAA,
          typename BBB,
          typename CCC,
          template <typename>
          class DDD>
class SomeTemplate;
```

Notably with `DDD` split in two lines, instead of `template <typename> class DDD`. This is a confusing formatting choice since `class DDD` is a valid template parameter in its own right, and it's very easy to miss the leading *template-head* here. 

If I set `BinPackParameters` to `true`, then I get:

```cpp
template <typename AAA, typename BBB, typename CCC,
          template <typename> class DDD>
class SomeTemplate;
```

This formats `DDD` the right way, but also packs the other parameters - which I wanted to avoid. 

Is there a way to format `SomeTemplate` this way?

```cpp
template <typename AAA,
          typename BBB,
          typename CCC,
          template <typename> class DDD>
class SomeTemplate;
```
