### ISSUE TITLE
[clang-format] BraceWrapping.AfterEnum overrides AllowShortEnumsOnASingleLine

### ISSUE THREAD

**Issue by alexhenrie** [llvm/llvm-project#62067]
I am using clang-format 15.0.7.

Config file:

```
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: true
BraceWrapping:
  AfterEnum: true
  AfterFunction: true
BreakBeforeBraces: Custom
```

Input code (copied from [the documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortenumsonasingleline))

```
enum { A, B } myEnum;

int main() { return 0; }
```

Expected output: No change

Actual output:

```
enum
{
  A,
  B
} myEnum;

int main() { return 0; }
```

I believe that it is a bug for `AfterEnum: true` to affect `AllowShortEnumsOnASingleLine: true` because `AfterFunction: true` does not affect `AllowShortFunctionsOnASingleLine: true`.

This may be related to issue #60475.
