### ISSUE TITLE
[clang-format] `AllowShortBlocksOnASingleLine: Empty` does not allow short blocks on single lines

### ISSUE THREAD

**Issue by thebear8** [llvm/llvm-project#62117]
clang-format version: 16.0.0 on Windows 10

`AllowShortBlocksOnASingleLine: Empty` behaves like `AllowShortBlocksOnASingleLine: Never` for empty blocks.

Minimal Example:

Config:
```yaml
---
BasedOnStyle: Chromium
AllowShortBlocksOnASingleLine: Empty
BreakBeforeBraces: Custom
BraceWrapping:
  AfterControlStatement: Always
  AfterFunction:   true

...
```

Yields this:
```c++
#include <iostream>

int main(int argc, char* argv[])
{
  while (true)
  {
  }

  while (true)
  {
    std::cout << "ASDAJKSDGJKASDGJAGSDJHAGSDKJGASJKDHGAKJHSDGJKHASGD";
  }
}
```

Setting `AllowShortBlocksOnASingleLine` to `Always` results in correct formatting:
```c++
#include <iostream>

int main(int argc, char* argv[])
{
  while (true) {}

  while (true)
  {
    std::cout << "ASDAJKSDGJKASDGJAGSDJHAGSDKJGASJKDHGAKJHSDGJKHASGD";
  }
}
```

I noticed this while working on a very large project, so I tried to boil it down as much as possible.
Using `AllowShortBlocksOnASingleLine: Always` isn't really feaisble because I only want empty blocks to be on a single line.
