### ISSUE TITLE
clang-format 16 on JSON with a leading space doesn't indent correctly

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#62229]
Given this JSON where there is a space before the "{":

```json
 {
    "a": "foo",
    "b": []
}
```

using `_clang-format`:

```yaml
---
BasedOnStyle: Google
IndentWidth: 4
ColumnLimit: 100
...
```

clang-format 16 yields the following:

```json
 {
    "a": "foo",
    "b": []
}
```

Notice the opening "{" is not in the first column.
