### ISSUE TITLE
Constructor initializers are not indented correctly by clang-format when using WhitespaceSensitiveMacros

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#62521]
Given:

```cpp
Foo::Foo()
    : setup()
    , fString(BOOST_PP_STRINGIZE(VER))
    , bar() {
    other();
}
```

using `_clang-format`:

```yaml
---
BasedOnStyle: Google
IndentWidth: 4
BreakConstructorInitializers: BeforeComma
ConstructorInitializerAllOnOneLineOrOnePerLine: false
...
```

clang-format 16 yields the following

```cpp
Foo::Foo()
    : setup()
    , fString(BOOST_PP_STRINGIZE(VER))
              , bar() {
    other();
}
```

Notice the bar() is shifted too much to the right. If we replace BOOST_PP_STRINGIZE with say STR,
then indentation is correct. Note, that BOOST_PP_STRINGIZE is one of the WhitespaceSensitiveMacros
setup by the Google style.
