### ISSUE TITLE
clang-format: IntegerLiteralSeparator formatted incorrectly with `s` literal suffix

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#62679]
WIth the configuration 

```yml
IntegerLiteralSeparator:
  Binary: 8
  Decimal: 3
  DecimalMinDigits: 5
  Hex: 0
```

Clang-Format 16.0.3 proposes the following change:

```diff
-   RateLimit limit{2, 1000s};
+   RateLimit limit{2, 10'00s};
```

There are two issues:
1. it seems to consider the `s` suffix as a digit, and hence place the tick in the wrong place
2. it should not format this number at all, thanks to `DecimalMinDigits`
