### ISSUE TITLE
[clang-format] Short function option not respected after preprocessor with ColumnLimit 0 and BraceWrapping AfterFunction

### ISSUE THREAD

**Issue by rymiel** [llvm/llvm-project#62721]
Very specific setup, but I believe it's all required. Tested with clang format versions 14, 15, 16 and trunk (58e6caaba1cf623292c8898be30a5a56722432b3)

Given this source file:

```cpp
struct Foo {
#pragma foo
int foo() { return 0; }
};
```

Formatted with the following config:

```yaml
AllowShortFunctionsOnASingleLine: All
BreakBeforeBraces: Custom
BraceWrapping:
  AfterFunction:   true
ColumnLimit:     0
```

Results in:

```cpp
struct Foo {
#pragma foo
  int foo()
  {
    return 0;
  }
};
```

The pragma may be replaced with any preprocessor directive
The surrounding class seems to be required too, for some reason

I believe this might be #35805, but that issue didn't mention BraceWrapping.AfterFunction, I'm inclined to close that one since it doesn't reproduce with just the information there, I believe something went missing

Discovered here: https://github.com/SerenityOS/serenity/pull/18766/files#r1193013334
