### ISSUE TITLE
clangd: C++ member var declaration is formatted poorly

### ISSUE THREAD

**Issue by ns-osmolsky** [llvm/llvm-project#62847]
Sublime Text shows a popup that is poorly formatted given the following C++ member variable declaration:

```
ns_event_t *m_eventMsg{nullptr};
```

The syntax above is C++11 and is (nearly) equivalent to `m_eventMsg = nullptr;`. Sublime shows that initialization but with extra line breaks… it thinks that it’s a block.

Here is a screenshot:
![sshot](https://github.com/llvm/llvm-project/assets/63256763/39445fe5-1257-45f8-ae52-74be4d7d5685)

As per the [LSP dev](https://github.com/sublimelsp/LSP-clangd/issues/15), this data comes from `clangd`.

**Comment by HighCommander4** [comment]
What clangd version are you using?

I could not reproduce this in vscode, here's how the vscode's hover looks on similar code:

![llvm-issue-62847](https://github.com/llvm/llvm-project/assets/1751085/f532a070-52bf-44fe-ac78-ac73bd69f22a)

**Comment by kadircet** [comment]
can you also post `.clang-format` file for your project? we run clang-format on definitions we generate, which respects `.clang-format` files in the mentioned file's parent directories.

**Comment by ns-osmolsky** [comment]
I'm on LLVM 16 and here is my `.clang-format`:
```
BasedOnStyle: Google
Standard: Cpp11
ColumnLimit: 95
IndentWidth: 4
ContinuationIndentWidth: 4
DerivePointerAlignment: false
PointerAlignment: Right
AccessModifierOffset: -4
IndentCaseLabels: false
AllowShortFunctionsOnASingleLine: Inline
AlwaysBreakAfterReturnType: TopLevelDefinitions
BreakBeforeBraces: Custom
BraceWrapping:
  AfterEnum: false
  AfterStruct: false
  AfterFunction: true
BinPackArguments: false
BinPackParameters: false
IndentRequires: true
IncludeIsMainRegex: "never"
```
