### ISSUE TITLE
clang format: lambda body indendation thrown off by capture block arguments

### ISSUE THREAD

**Issue by akforrest** [llvm/llvm-project#62938]
With Clang-Format 16, and
```yml
LambdaBodyIndentation: OuterScope
WhitespaceSensitiveMacros: ['QObject::connect']
BinPackArguments: 'false'
BinPackParameters: 'false'
```
Having an extra capture argument in the lambda throws off the indentation:
```cpp
 QObject::connect(obj, &QObject::someSignal, slotObj, [this]() {
     this->dosomething();
 });
 QObject::connect(obj, &QObject::someSignal, slotObj, [this, to]() {
                      this->dosomething(to);
 });
```
The first connect statement is correct, the second is not. As soon as the capture block has more than one argument in it the alignment is wrong. We are adding the connect statement to `WhitespaceSensitiveMacros` because we are unable to configure Clang-Format to not change line wrapping of function arguments.
