### ISSUE TITLE
ShortNamespaceLines inconsistent between clang-tidy and clang-format

### ISSUE THREAD

**Issue by alexolog** [llvm/llvm-project#63067]
With these lines in `.clang-tidy`:
```yaml
  - key: google-readability-namespace-comments.ShortNamespaceLines
    value: "10"
  - key: llvm-namespace-comment.ShortNamespaceLines
    value: "10"
```
and these settings in `.clang-format`:
```yaml
CompactNamespaces: false
NamespaceIndentation: None
FixNamespaceComments: true
ShortNamespaceLines: 10
```
I get inconsistent results from the two tools.

For example, given the configuration above, clang-tidy will complain on this code:
```C++
namespace test {
[[maybe_unused]] int constexpr i1 = 1;
[[maybe_unused]] int constexpr i2 = 1;
[[maybe_unused]] int constexpr i3 = 1;
[[maybe_unused]] int constexpr i4 = 1;
[[maybe_unused]] int constexpr i5 = 1;
[[maybe_unused]] int constexpr i6 = 1;
[[maybe_unused]] int constexpr i7 = 1;
[[maybe_unused]] int constexpr i8 = 1;
[[maybe_unused]] int constexpr i9 = 1;
}
```
But clang-format will not fix it, even though both specify `10` as the threshold.

In addition, clang-format seems to not include empty lines in the count while clang-tidy does.
