### ISSUE TITLE
Nested braced initializer lists not behaving as expected

### ISSUE THREAD

**Issue by btowntkd** [llvm/llvm-project#63115]
I am using clang-format and I have a particular block of code with nested braced initializers. I would like the code to look like this:

```cpp
auto test = TheThing{ 
    Arg1{ blorp, bleep, bloop, blop, blip },
    Arg2{ blorp, bleep, bloop, blop, blop, blip } };
```

Note the desired behavior:

 - When the parameter list is too long to fit on one line, each parameter is placed on its own line
 - The parameters are indented, *not* aligned
 - Each parameter contains a nested parameter list, which fits on a single line

But clang-format keeps reformatting it thusly:

```cpp
auto test = TheThing{ Arg1{ blorp, bleep, bloop, blop, blip },
                      Arg2{ blorp, bleep, bloop, blop, blop, blip } };
```

Note the undesired behavior:
- The first parameter is still on the same line as the open brace
- the parameters are aligned instead of indented

This is the clang-format settings I currently use:
```
---
BasedOnStyle: Microsoft
AccessModifierOffset: -4
AlignArrayOfStructures: Left
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: InlineOnly
AllowShortLambdasOnASingleLine: Inline
AlignTrailingComments: true
BraceWrapping:
  AfterCaseLabel: true
  AfterClass: true
  AfterControlStatement: Always
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: true
  AfterStruct: true
  AfterUnion: true
  AfterExternBlock: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: true
  BeforeWhile: true
  IndentBraces: true
  SplitEmptyFunction: false
BreakBeforeBraces: Allman
BreakConstructorInitializers: AfterColon
ColumnLimit: 120
DerivePointerAlignment: false
FixNamespaceComments: false
IncludeBlocks: Regroup
IndentWidth: 4
NamespaceIndentation: All
PointerAlignment: Left
ReferenceAlignment: Left
SortIncludes: Never
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
SpaceInEmptyParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false
SpaceAfterTemplateKeyword: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
TabWidth: 4
UseTab: Always


AlignAfterOpenBracket: AlwaysBreak
AllowAllArgumentsOnNextLine: false
AllowAllConstructorInitializersOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
BinPackArguments: false
BinPackParameters: false
ConstructorInitializerAllOnOneLineOrOnePerLine: true
Cpp11BracedListStyle: false
SpaceBeforeCpp11BracedList: false
```

I placed the settings that *seem* like they should be the most relevant in this case at the bottom.

Is there a setting I'm missing?
