### ISSUE TITLE
clang-format-17 fails to format nested initializers when ColumnLimit is set

### ISSUE THREAD

**Issue by docquantum** [llvm/llvm-project#63177]
# Problem

Nested initializers fail to format correctly when `ColumnLimit` is set.

# Version

This exists in older version of `clang-format` as well. However, the version I am testing with is:
```
Ubuntu clang-format version 17.0.0 (++20230607042350+cb9f1aaddac0-1~exp1~20230607042512.983)
```

# Tests

My test code is as follows:
```cpp
GPIO_Config r_led = {
    .Type    = GPIOA,
    .Init          = {.Pin   = GPIO_PIN_7,
                      .Mode  = GPIO_MODE_OUTPUT_PP,
                .Pull  = GPIO_NOPULL,
                   .Speed = GPIO_SPEED_FREQ_LOW,},
    .InitSecond = {.Pin   = GPIO_PIN_7,
                   .Mode  = GPIO_MODE_OUTPUT_PP,
                   .Pull  = GPIO_NOPULL,
                   .Speed = GPIO_SPEED_FREQ_LOW,},
};
```

When `ColumnLimit: 80` is set, formatting is ignored for the struct and continues after the semicolon.

However, removing the trailing commas in the nested structs does produce an expected result:
```cpp
GPIO_Config r_led = {
    .Type       = GPIOA,
    .Init       = {.Pin   = GPIO_PIN_7,
                   .Mode  = GPIO_MODE_OUTPUT_PP,
                   .Pull  = GPIO_NOPULL,
                   .Speed = GPIO_SPEED_FREQ_LOW},
    .InitSecond = {.Pin   = GPIO_PIN_7,
                   .Mode  = GPIO_MODE_OUTPUT_PP,
                   .Pull  = GPIO_NOPULL,
                   .Speed = GPIO_SPEED_FREQ_LOW},
};
```

If I set `ColumnLimit: 0`, formatting works as expected for the block:
```cpp
GPIO_Config r_led = {
    .Type = GPIOA,
    .Init = {
        .Pin   = GPIO_PIN_7,
        .Mode  = GPIO_MODE_OUTPUT_PP,
        .Pull  = GPIO_NOPULL,
        .Speed = GPIO_SPEED_FREQ_LOW,
    },
    .InitSecond = {
        .Pin   = GPIO_PIN_7,
        .Mode  = GPIO_MODE_OUTPUT_PP,
        .Pull  = GPIO_NOPULL,
        .Speed = GPIO_SPEED_FREQ_LOW,
    },
};
```

# Configuration
My `.clang-format`:
```yml
---
Language: Cpp
# BasedOnStyle: WebKit
AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AlignArrayOfStructures: None
AlignConsecutiveAssignments: 
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: true
  PadOperators: true
AlignConsecutiveBitFields: 
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: false
  PadOperators: false
AlignConsecutiveDeclarations: 
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: false
  PadOperators: false
AlignConsecutiveMacros: 
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: false
  PadOperators: false
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments: 
  Kind: Always
  OverEmptyLines: 1
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Empty
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: Inline
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: No
AttributeMacros: 
  - __capability
BinPackArguments: false
BinPackParameters: false
BitFieldColonSpacing: Both
BraceWrapping: 
  AfterCaseLabel: false
  AfterClass: true
  AfterControlStatement: Never
  AfterEnum: false
  AfterExternBlock: false
  AfterFunction: true
  AfterNamespace: true
  AfterObjCDeclaration: false
  AfterStruct: false
  AfterUnion: false
  BeforeCatch: false
  BeforeElse: false
  BeforeLambdaBody: false
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
BreakAfterAttributes: Never
BreakAfterJavaFieldAnnotations: false
BreakArrays: true
BreakBeforeBinaryOperators: All
BreakBeforeConceptDeclarations: Always
BreakBeforeBraces: Custom
BreakBeforeInlineASMColon: OnlyMultiline
BreakBeforeTernaryOperators: false
BreakConstructorInitializers: AfterColon
BreakInheritanceList: AfterColon
BreakStringLiterals: false
ColumnLimit: 80
CommentPragmas: '^ IWYU pragma: '
CompactNamespaces: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat: false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: LogicalBlock
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
ForEachMacros: 
  - foreach
  - Q_FOREACH
  - BOOST_FOREACH
IfMacros: 
  - KJ_IF_MAYBE
IncludeBlocks: Regroup
IncludeCategories: 
  - Regex: '^"(llvm|llvm-c|clang|clang-c)/'
    Priority: 2
    SortPriority: 0
    CaseSensitive: false
  - Regex: '^(<|"(gtest|gmock|isl|json)/)'
    Priority: 3
    SortPriority: 0
    CaseSensitive: false
  - Regex: '.*'
    Priority: 1
    SortPriority: 0
    CaseSensitive: false
IncludeIsMainRegex: '(Test)?$'
IncludeIsMainSourceRegex: ''
IndentAccessModifiers: false
IndentCaseBlocks: false
IndentCaseLabels: false
IndentExternBlock: NoIndent
IndentGotoLabels: true
IndentPPDirectives: None
IndentRequiresClause: true
IndentWidth: 4
IndentWrappedFunctionNames: true
InsertBraces: true
InsertNewlineAtEOF: true
InsertTrailingCommas: None
IntegerLiteralSeparator: 
  Binary: 0
  Decimal: 0
  Hex: 0
JavaScriptQuotes: Leave
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: false
LambdaBodyIndentation: Signature
LineEnding: LF
MacroBlockBegin: ''
MacroBlockEnd: ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: Inner
ObjCBinPackProtocolList: Auto
ObjCBlockIndentWidth: 4
ObjCBreakBeforeNestedBlockParam: true
ObjCSpaceAfterProperty: true
ObjCSpaceBeforeProtocolList: true
PackConstructorInitializers: Never
PenaltyBreakAssignment: 2
PenaltyBreakBeforeFirstCallParameter: 19
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakOpenParenthesis: 0
PenaltyBreakString: 1000
PenaltyBreakTemplateDeclaration: 10
PenaltyExcessCharacter: 1000000
PenaltyIndentedWhitespace: 0
PenaltyReturnTypeOnItsOwnLine: 60
PointerAlignment: Right
PPIndentWidth: -1
QualifierAlignment: Left
ReferenceAlignment: Pointer
ReflowComments: true
RemoveBracesLLVM: false
RemoveSemicolon: true
RequiresClausePosition: OwnLine
RequiresExpressionIndentation: OuterScope
SeparateDefinitionBlocks: Always
ShortNamespaceLines: 0
SortIncludes: CaseSensitive
SortJavaStaticImport: Before
SortUsingDeclarations: LexicographicNumeric
SpaceAfterCStyleCast: true
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: false
SpaceAroundPointerQualifiers: Default
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: true
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: Never
SpacesInConditionalStatement: false
SpacesInContainerLiterals: false
SpacesInCStyleCastParentheses: false
SpacesInLineCommentPrefix: 
  Minimum: 1
  Maximum: -1
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: c++17
StatementAttributeLikeMacros: 
  - Q_EMIT
StatementMacros: 
  - Q_UNUSED
  - QT_REQUIRE_VERSION
TabWidth: 4
UseTab: Never
WhitespaceSensitiveMacros: 
  - BOOST_PP_STRINGIZE
  - CF_SWIFT_NAME
  - NS_SWIFT_NAME
  - PP_STRINGIZE
  - STRINGIZE
...
```

**Comment by Jamwe** [comment]
# test case
Almost the same problem while formatting file tests\nestedTest.c of [misje/stateMachine](https://github.com/misje/stateMachine)

![tests\nestedTest.c](https://github.com/llvm/llvm-project/assets/36603516/28457df5-c498-4f48-a8e2-4a13600ef32d)

# .clang-format.
```yaml
{
  BasedOnStyle: LLVM,
  Language: Cpp,
  Standard: c++17,
  TabWidth: 2,
  IndentWidth: 2,
  ColumnLimit: 180,
  MaxEmptyLinesToKeep: 8,
  AlignArrayOfStructures: Right,
  AlignConsecutiveAssignments: { Enabled: true, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: true, PadOperators: true },
  AlignConsecutiveBitFields: { Enabled: true, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: true, PadOperators: true },
  AlignConsecutiveDeclarations: { Enabled: true, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: true, PadOperators: true },
  AlignConsecutiveMacros: { Enabled: true, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: true, PadOperators: true },
  AlignEscapedNewlines: Left,
  PointerAlignment: Right,
  AllowShortFunctionsOnASingleLine: None,
  AllowShortLambdasOnASingleLine: None,
  BreakBeforeBraces: Allman,
  BraceWrapping:
    {
      AfterCaseLabel: true,
      AfterClass: true,
      AfterControlStatement: Always,
      AfterEnum: true,
      AfterExternBlock: true,
      AfterFunction: true,
      AfterNamespace: true,
      AfterObjCDeclaration: true,
      AfterStruct: true,
      AfterUnion: true,
      BeforeCatch: true,
      BeforeElse: true,
      BeforeLambdaBody: true,
      BeforeWhile: false,
      IndentBraces: false,
      SplitEmptyFunction: true,
      SplitEmptyRecord: true,
      SplitEmptyNamespace: true,
    },
  BreakBeforeBinaryOperators: NonAssignment,
  IndentAccessModifiers: false,
  AccessModifierOffset: -2,
  IndentCaseBlocks: true,
  IndentCaseLabels: true,
  IndentGotoLabels: false,
  IndentPPDirectives: AfterHash,
  PPIndentWidth: -2,
  IndentWrappedFunctionNames: true,
  NamespaceIndentation: All,
  SpaceBeforeCaseColon: true,
  SpaceBeforeParens: Never,
  SpaceBeforeParensOptions:
    {
      AfterControlStatements: false,
      AfterForeachMacros: false,
      AfterFunctionDefinitionName: false,
      AfterFunctionDeclarationName: false,
      AfterIfMacros: false,
      AfterOverloadedOperator: false,
      AfterRequiresInClause: false,
      AfterRequiresInExpression: false,
      BeforeNonEmptyParentheses: false,
    },
  SpaceInEmptyBlock: true,
  SpacesBeforeTrailingComments: 4,
  SpacesInConditionalStatement: true,
  SpacesInContainerLiterals: true,
  SpacesInParentheses: true,
  SpacesInSquareBrackets: true,
  InsertBraces: false,
  QualifierAlignment: Leave,
  RemoveBracesLLVM: false,
  RemoveSemicolon: false,
  UseTab: Never,
  SortIncludes: Never,
  IncludeCategories:
    [
      { Regex: '^<.*\.h|.*\.hpp>', Priority: 1, SortPriority: 0, CaseSensitive: false },
      { Regex: "^<.*", Priority: 2, SortPriority: 1, CaseSensitive: false },
      { Regex: '^"\.\..*', Priority: 3, SortPriority: 2, CaseSensitive: false },
      { Regex: '^"[a-zA-Z0-9_\-]*', Priority: 4, SortPriority: 3, CaseSensitive: false },
      { Regex: ".*", Priority: 5, SortPriority: 4, CaseSensitive: false },
    ],
}
```
