### ISSUE TITLE
[clang-tidy] Options in --dump-config should be sorted

### ISSUE THREAD

**Issue by PiotrZSL** [llvm/llvm-project#64153]
Example:

```
--dump-config --checks="*"

--
Checks:          'clang-diagnostic-*,clang-analyzer-*,*'
WarningsAsErrors: ''
HeaderFileExtensions:
  - ''
  - h
  - hh
  - hpp
  - hxx
ImplementationFileExtensions:
  - c
  - cc
  - cpp
  - cxx
HeaderFilterRegex: ''
FormatStyle:     none
CheckOptions:
  readability-magic-numbers.IgnoredIntegerValues: '1;2;3;4;'
  misc-const-correctness.TransformValues: 'true'
  cppcoreguidelines-narrowing-conversions.IgnoreConversionFromTypes: ''
  bugprone-argument-comment.CommentFloatLiterals: '0'
  modernize-use-emplace.ContainersWithPush: '::std::stack;::std::queue;::std::priority_queue'
  misc-const-correctness.AnalyzeValues: 'true'
  hicpp-special-member-functions.AllowMissingMoveFunctionsWhenCopyIsDeleted: 'false'
  modernize-use-bool-literals.IgnoreMacros: 'true'
  google-readability-function-size.LineThreshold: '4294967295'
  portability-simd-intrinsics.Std: ''
  modernize-make-unique.IgnoreMacros: 'true'
  modernize-use-emplace.ContainersWithPushFront: '::std::forward_list;::std::list;::std::deque'
  cppcoreguidelines-pro-type-member-init.UseAssignment: 'false'
  misc-definitions-in-headers.HeaderFileExtensions: ';h;hh;hpp;hxx'
  cppcoreguidelines-narrowing-conversions.WarnOnEquivalentBitWidth: 'true'
  readability-uppercase-literal-suffix.IgnoreMacros: 'true'
  bugprone-dangling-handle.HandleClasses: 'std::basic_string_view;std::experimental::basic_string_view'
  readability-function-cognitive-complexity.DescribeBasicIncrements: 'true'
  llvm-else-after-return.WarnOnUnfixable: 'false'
  readability-container-data-pointer.IgnoredContainers: ''
  bugprone-exception-escape.IgnoredExceptions: ''
  google-build-namespaces.HeaderFileExtensions: ';h;hh;hpp;hxx'
  altera-single-work-item-barrier.AOCVersion: '1600'
  hicpp-use-noexcept.UseNoexceptFalse: 'true'
  hicpp-use-emplace.SmartPointers: '::std::shared_ptr;::std::unique_ptr;::std::auto_ptr;::std::weak_ptr'
  hicpp-use-override.FinalSpelling: final
  modernize-deprecated-headers.CheckHeaderFile: 'false'
  cppcoreguidelines-special-member-functions.AllowSoleDefaultDtor: 'false'
  concurrency-mt-unsafe.FunctionSet: any
  bugprone-suspicious-missing-comma.RatioThreshold: '0.200000'
  cert-str34-c.DiagnoseSignedUnsignedCharComparisons: 'false'
  hicpp-braces-around-statements.ShortStatementLines: '0'
  misc-include-cleaner.IgnoreHeaders: ''
  modernize-loop-convert.MakeReverseRangeFunction: ''
  cppcoreguidelines-no-malloc.Allocations: '::malloc;::calloc'
  modernize-use-override.FinalSpelling: final
  cert-msc32-c.DisallowedSeedTypes: 'time_t,std::time_t'
  cppcoreguidelines-avoid-do-while.IgnoreMacros: 'false'
  bugprone-argument-comment.CommentStringLiterals: '0'
  modernize-use-equals-default.IgnoreMacros: 'true'
  modernize-make-shared.IgnoreDefaultInitialization: 'true'
  abseil-string-find-startswith.IncludeStyle: llvm
  readability-function-size.ParameterThreshold: '4294967295'
```

Config options are printed in random order, and it's hard to find needed options.
Options should be sorted by check name + option name.
