### ISSUE TITLE
[clang-format] SpacesInParensOptions.InConditionalStatements = false is ignored when Other = true

### ISSUE THREAD

**Issue by zeule** [llvm/llvm-project#64416]
With the following settings
```
SpacesInParens: Custom
SpacesInParensOptions:
  InConditionalStatements: false
  InCStyleCasts: false
  InEmptyParentheses: false
  Other: true
````

clang format inserts spaces inside conditional statements. An illustrative fix:
```diff
diff --git a/clang/lib/Format/TokenAnnotator.cpp b/clang/lib/Format/TokenAnnotator.cpp
index 5ba3ef19f0c5..c8a93999c1da 100644
--- a/clang/lib/Format/TokenAnnotator.cpp
+++ b/clang/lib/Format/TokenAnnotator.cpp
@@ -3776,7 +3776,8 @@ bool TokenAnnotator::spaceRequiredBetween(const AnnotatedLine &Line,
        Right.is(tok::r_brace) && Right.isNot(BK_Block))) {
     return Style.SpacesInParensOptions.InEmptyParentheses;
   }
-  if (Style.SpacesInParensOptions.InConditionalStatements) {
+
+  {
     const FormatToken *LeftParen = nullptr;
     if (Left.is(tok::l_paren))
       LeftParen = &Left;
@@ -3784,9 +3785,10 @@ bool TokenAnnotator::spaceRequiredBetween(const AnnotatedLine &Line,
       LeftParen = Right.MatchingParen;
     if (LeftParen) {
       if (LeftParen->is(TT_ConditionLParen))
-        return true;
+        return Style.SpacesInParensOptions.InConditionalStatements;
+
       if (LeftParen->Previous && isKeywordWithCondition(*LeftParen->Previous))
-        return true;
+        return Style.SpacesInParensOptions.InConditionalStatements;
     }
   }
```
