### ISSUE TITLE
clang-format: inconsistent continuation indentation

### ISSUE THREAD

**Issue by vesterij** [llvm/llvm-project#64952]
clang-format version 16.0.5

Config
```yaml
Language:        Cpp
Standard:        c++20
AlignAfterOpenBracket: DontAlign
AlignEscapedNewlines: DontAlign
AlignOperands:   DontAlign
ColumnLimit:     0
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 8
IndentWidth:     4
TabWidth:        4
UseTab:          ForContinuationAndIndentation
```

Code
```cpp
int main() {
	int key = 3;
	std::vector<int> veryLongNameForThisVector{1, 2, 3, 4, 5};

	// Here continuation indentation is done with tabs only.
	auto it = std::find(veryLongNameForThisVector.begin(),
			veryLongNameForThisVector.end(),
			key);

	// Here continuation indentation has mix of tabs and spaces. Why?
	bool found = std::find(veryLongNameForThisVector.begin(),
						 veryLongNameForThisVector.end(),
						 key) != veryLongNameForThisVector.end();
}
```

Here first std::find does continuation indentation using only tabs as I was expecting.

The second std::find however mixes tabs and spaces for some reason. 

Is this a bug? Or have I just misunderstood how continuation indentation works (continuation from what)?

I know that if I use tabs for intendation and I choose to align operands, alignment has to be adjusted with spaces in some cases. But I don't think it should happen here.
