### ISSUE TITLE
Use multiarch layout with multilibs for libc++ headers

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#70172]
For the following `multilib.yaml` file:
```
---
MultilibVersion: 1.0

Variants:
- Dir: testdir1
  Flags: [--target=thumbv7m-none-unknown-eabi]

- Dir: testdir2
  Flags: [--target=thumbv7em-none-unknown-eabi]

Mappings:
- Match: --target=thumbv7em-none-unknown-eabi
  Flags: [--target=thumbv7m-none-unknown-eabi]
```

We'll end up with the following include directories:
```
-internal-isystem [[SYSROOT]]/bin/../lib/clang-runtimes/testdir1/include/c++/v1"
-internal-isystem [[SYSROOT]]/bin/../lib/clang-runtimes/testdir2/include/c++/v1"
```

This is suboptimal. libc++ headers are designed to be target agnostic with the exception of `__config_site` to avoid having to distribute multiple copies of headers, one for each target or multilib.

Ideally, what we should end up with is something like this:
```
-internal-isystem [[SYSROOT]]/bin/../include/thumbv7m-none-unknown-eabi/testdir1/include/c++/v1
-internal-isystem [[SYSROOT]]/bin/../include/thumbv7m-none-unknown-eabi/testdir2/include/c++/v1
-internal-isystem [[SYSROOT]]/bin/../include/c++/v1
```

Where `[[SYSROOT]]/bin/../include/thumbv7m-none-unknown-eabi/testdir1/include/c++/v1` and `[[SYSROOT]]/bin/../include/thumbv7m-none-unknown-eabi/testdir2/include/c++/v1` should only contain `__config_site`.
