### ISSUE TITLE
[clang-format] unexpected behavior from "AlignConsecutiveAssignments: Consecutive"

### ISSUE THREAD

**Issue by zhang-stephen** [llvm/llvm-project#73366]
I am using llvm 17 for a tiny C project on Mac OS 14. and the clang-format is installed by homebrew.

then I got this formatted file(it should be aligned along the `=`):

![image](https://github.com/llvm/llvm-project/assets/17326718/35e98f16-7fd6-41c4-90c0-5b159542f251)

the command I used(which was ran in the root of the project):

![image](https://github.com/llvm/llvm-project/assets/17326718/2aec4469-b775-47ee-b521-5e295d2619c1)

Do not mark this issue as "duplicated", please. I have checked #58029, which said the issue should be fixed in llvm 16. But I think it is not fixed completely.

`.clang-format`:

```yml
---
# Language: C, Cpp
BasedOnStyle: WebKit

# user-defined details
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: Consecutive # --> HERE: alignment along "+", instead of "=" <--
AlignConsecutiveDeclarations: Consecutive
AlignConsecutiveBitFields: Consecutive
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortLoopsOnASingleLine: true
AllowShortBlocksOnASingleLine: true
AllowShortIfStatementsOnASingleLine: WithoutElse
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
BraceWrapping:
    AfterCaseLabel: true
    AfterClass: true
    AfterControlStatement: Always
    AfterExternBlock: false
    AfterEnum: true
    AfterFunction: true
    AfterNamespace: true
    AfterStruct: true
    AfterUnion: true
    BeforeElse: true
    BeforeLambdaBody: false
    BeforeWhile: false
BreakBeforeConceptDeclarations: Always
BreakBeforeTernaryOperators: true
BreakStringLiterals: true
BreakConstructorInitializers: BeforeComma
BreakBeforeBraces: Custom
ColumnLimit: 120
EmptyLineBeforeAccessModifier: Always
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
IncludeBlocks: Regroup
IndentCaseBlocks: true
NamespaceIndentation: None
PointerAlignment: Left
ReferenceAlignment: Left
SpaceInEmptyBlock: false
SpaceBeforeCaseColon: false
UseTab: Never
UseCRLF: false

```
