### ISSUE TITLE
`readability-identifier-naming` should add universal default options

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#75688]
I almost always want my casing to be "lower_case", and it'd be nice to provide a default case, and only spell out the ones that don't conform to this (e.g. macros).

**Comment by kannishk** [comment]
Hey, @cjdb please assign me this issue. Would love to hack around!

**Comment by kannishk** [comment]
> Hey @EugeneZelenko I had a doubt.
> 
> Till now I have been trying to make this a part of the coding standard and errors should arise if anything deviates.(This doesn't seem to work)
> 
> I believe that clang-format should be one enforcing this change; Am I right on this part? The developer can write the code and clang-format making it prettier later.

@EugeneZelenko @cjdb

**Comment by usx95** [comment]
> I believe that clang-format should be one enforcing this change; Am I right on this part? The developer can write the code and clang-format making it prettier later.

This is not about formatting the code. Clang format only formats the code and does not enforce or change naming conventions.

This is done as part of the mentioned clangtidy check 
https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-naming.html

**Comment by firewave** [comment]
Even though this is no longer about clang-tidy still a no note.

It seems there changing defaults for `readability-identifier-naming` won't have any effect since it seems the check won't report anything unless you specify options - see #58096.

**Comment by cjdb** [comment]
Explicitly setting a default naming style would have the same effect as manually applying it to everything that's in the list. It's kind of frustrating to need to list everything, when they're all set to the same value.

```yaml
- key: readability-identifier-naming.DefaultCase:
  value: "lower_case"
- key: readability-identifier-naming.DefaultPrefix:
  value: ""
- key: readability-identifier-naming.DefaultSuffix:
  value: ""
- key: readability-identifier-naming.DefaultIgnoredRegexp:
  value: ""
- key: readability-identifier-naming.DefaultHungarianPrefix:
  value: ""
- key: readability-identifier-naming.MacroDefinitionCase
  value: "UPPER_CASE"
- key: readability-identifier-naming.MacroDefinitionPrefix
  value: "${PROJECT_NAME}_"
- key: readability-identifier-naming.PrivateMemberSuffix
  value: "_"
```

is way more concise than

```yaml
- key: readability-identifier-naming.ClassCase
  value: "lower_case"
- key: readability-identifier-naming.ClassMemberCase
  value: "lower_case"
- key: readability-identifier-naming.ClassMemberSuffix
  value: "_"
- key: readability-identifier-naming.ConceptCase
  value: "lower_case"
- key: readability-identifier-naming.ConstantCase
  value: "lower_case"
- key: readability-identifier-naming.ConstantMemberCase
  value: "lower_case"
- key: readability-identifier-naming.ConstexprVariableCase
  value: "lower_case"
- key: readability-identifier-naming.EnumCase
  value: "lower_case"
- key: readability-identifier-naming.EnumConstantCase
  value: "lower_case"
- key: readability-identifier-naming.FunctionCase
  value: "lower_case"
- key: readability-identifier-naming.MacroDefinitionCase
  value: "UPPER_CASE"
- key: readability-identifier-naming.MacroDefinitionPrefix
  value: "${PROJECT_NAME}_"
- key: readability-identifier-naming.MemberCase
  value: "lower_case"
- key: readability-identifier-naming.MethodCase
  value: "lower_case"
- key: readability-identifier-naming.NamespaceCase
  value: "lower_case"
- key: readability-identifier-naming.ParameterCase
  value: "lower_case"
- key: readability-identifier-naming.PrivateMemberSuffix
  value: "_"
- key: readability-identifier-naming.PrivateMethodCase
  value: "lower_case"
- key: readability-identifier-naming.PublicMemberCase
  value: "lower_case"
- key: readability-identifier-naming.PublicMethodCase
  value: "lower_case"
- key: readability-identifier-naming.TypeAliasCase
  value: "lower_case"
- key: readability-identifier-naming.VariableCase
  value: "lower_case"
```
and I'm more confident that the former isn't missing anything.
