### ISSUE TITLE
[clang-format] Incorrect short statement formatting with Allman (17.06)

### ISSUE THREAD

**Issue by dertarr** [llvm/llvm-project#77308]
Hello. Started using `clang-format` version `17.06` and noticed several strange issues. Here is one of them:

Clang formatter handles short statements inappropriately. I merged all issues with short statements in a single bug report. Here is my config:
```
---
Language: Cpp
BasedOnStyle: Google
AlignConsecutiveShortCaseStatements:
  Enabled:          true
  AcrossComments:   true
  AcrossEmptyLines: true
AllowShortBlocksOnASingleLine: Always
AllowShortCaseLabelsOnASingleLine: true
AllowShortIfStatementsOnASingleLine: WithoutElse
AllowShortLoopsOnASingleLine: true
BreakBeforeBraces: Allman
InsertBraces: true
...
```

Here is the list of related issues I see:

1. Formatter treats `Allow` word in a misleading way, more like `Enforce`. I would assume that this config *allows* me to keep one-liner short statements where I want to, without complaining about also having short statements on multiple lines. Maybe it makes sense to rename the `AllowShortXxxx` options or to add value `Leave` to `AllowShortBlocksOnASingleLine` option.
2. The `if-else` expression was also shrunk to two lines despite `AllowShortIfStatementsOnASingleLine: WithoutElse` setting.
3. The opening brace for `do {` statement was attached despite `BreakBeforeBraces: Allman` setting.
4. A short one-liner version of `do-while` loop was expanded to multiple lines despite `AllowShortLoopsOnASingleLine: true` setting.

Here is a sample file (on the left) and the formatted file (on the right)
<table>
<tr><th> Sample file </th><th> Formatted output </th></tr>
<tr><td valign="top">

```
void MODULE_ShowShortBlocks(void)
{
  // Short loops on several lines
  while (true)
  {
    continue;
  }

  // Short loops on a single line
  while (true) { continue; }

  // Short case statements on several lines
  switch (a)
  {
    case 1:
      x = 1;
      break;
    case 2:
      return;
  }

  // Short case statements merged
  switch (a)
  {
    case 1: x = 1; break;
    case 2: return;
  }

  // Short 'if' without 'else' block
  if (a == 0) { return; }

  // Short 'if' with 'else' block
  if (z == 7)
  {
    return;
  }
  else
  {
    LogError();
  }

  // A "do" example on a multiple lines
  do
  {
     PutItems(items, 1);
  } while (false);

  // A "do" example on a single line
  do { PutItems(items, 1); } while (false);
}
```

</td><td valign="top">

```
void MODULE_ShowShortBlocks(void)
{
  // Short loops on several lines
  while (true) { continue; }

  // Short loops on a single line
  while (true) { continue; }

  // Short case statements on several lines
  switch (a)
  {
    case 1: x = 1; break;
    case 2: return;
  }

  // Short case statements merged
  switch (a)
  {
    case 1: x = 1; break;
    case 2: return;
  }

  // Short 'if' without 'else' block
  if (a == 0) { return; }

  // Short 'if' with 'else' block
  if (z == 7) { return; }
  else { LogError(); }

  // A "do" example on a multiple lines
  do {
    PutItems(items, 1);
  } while (false);

  // A "do" example on a single line
  do {
    PutItems(items, 1);
  } while (false);
}
```

</td></tr></table>
