### ISSUE TITLE
[clang-format] Incorrect cursor position with IncludeBlocksStyle Regroup and LineEnding CRLF

### ISSUE THREAD

**Issue by NorthBlue333** [llvm/llvm-project#77450]
Hello,
We recently configured clang-format on our projects with Visual Studio.
We use the version shipped with Visual Studio 2022 : clang-format 16.0.5.

We found what we consider to be a bug: the cursor has the wrong position when formatting a file with CRLF line endings and includes already formatted.

Here are the reproduction steps:

`.clang-format`
```yml
LineEnding: CRLF
IncludeBlocks:   Regroup
IncludeCategories:
  - Regex:           '^<ext/.*\.h>'
    Priority:        2
    SortPriority:    0
  - Regex:           '^<.*\.h>'
    Priority:        1
    SortPriority:    0
  - Regex:           '^<.*'
    Priority:        2
    SortPriority:    0
  - Regex:           '.*\.generated\.h.*' # always last
    Priority:        2
    SortPriority:    100
  - Regex:           '.*\/.*\.h'
    Priority:        20
    SortPriority:    40
  - Regex:           '.*\/.*'
    Priority:        20
    SortPriority:    40
  - Regex:           '.*\.h'
    Priority:        30
    SortPriority:    30
  - Regex:           '.*'
    Priority:        30
    SortPriority:    30
```

`Foo.cpp`
```cpp
#include "Foo.h"
#include "Bar.h"
#include "Sub/Bar.h"
#include "Sub/Foo.h"

class Foo {
}
```

When formatting `Foo.cpp`, it correctly formats the include block:

`Foo.cpp`
```cpp
#include "Foo.h"

#include "Bar.h"

#include "Sub/Bar.h"
#include "Sub/Foo.h"

class Foo {
}
```

But when reformatting again, if the cursor is at pos 62 (just before `#include "Sub/Foo.h"`, note that we use CRLF), it will not return any replacements BUT it will return the wrong position for the cursor: 60. The cursor goes one line up, on `#include "Sub/Bar.h"`. The same thing happens when placing the cursor before `class Foo {`.

This seems to be aggravated by Visual Studio, which always sends to clang-format the start of the line as the cursor position, no matter where the cursor is on the line.

After some research, we think we've found the issue.

`clang/lib/Format/Format.cpp:2694`
```cpp
  std::string result;
  for (unsigned Index : Indices) {
    if (!result.empty()) {
      result += "\n";
      if (Style.IncludeStyle.IncludeBlocks ==
              tooling::IncludeStyle::IBS_Regroup &&
          CurrentCategory != Includes[Index].Category)
        result += "\n";
    }
    result += Includes[Index].Text;
    if (Cursor && CursorIndex == Index)
      *Cursor = IncludesBeginOffset + result.size() - CursorToEOLOffset;
    CurrentCategory = Includes[Index].Category;
  }

  if (Cursor && *Cursor >= IncludesEndOffset)
    *Cursor += result.size() - IncludesBlockSize;

  // If the #includes are out of order, we generate a single replacement fixing
  // the entire range of blocks. Otherwise, no replacement is generated.
  if (replaceCRLF(result) == replaceCRLF(std::string(Code.substr(
                                 IncludesBeginOffset, IncludesBlockSize))))
    return;
```

In this code, both cursor updates seem wrong. They are based on `result.size()` which **does not include the second line ending character** `\r`. The cursor position is then offsetted by the number of lines between include blocks.

The solution might be to use the correct new line character here, or to check the line ending length (1 character for LF and CR, 2 characters for CRLF).

I will provide a PR.

Thanks for your time
