### ISSUE TITLE
[clang-format] AlignOperands: DontAlign produces somewhat unexpected result

### ISSUE THREAD

**Issue by elvenfighter** [llvm/llvm-project#77778]
With a config file like this:
```yaml
Language: Cpp
Standard: c++17

ColumnLimit: 60
IndentWidth: 4
ContinuationIndentWidth: 8

BreakBeforeBinaryOperators: NonAssignment
BinPackArguments: true
AlignAfterOpenBracket: DontAlign
AlignOperands: DontAlign
# this was used to format the original code
#AlignOperands: Align
```

The following code:
```cpp
void test() {
    {
        {
            {
                int value = 24;
                LOG_STUFF(1, "[Tag] debug:" + __FILE__
                                     + " value = " + value
                                     + "some " + "more "
                                     + "text");
            }
        }
    }
}
```
Changes to
```cpp
void test() {
    {
        {
            {
                int value = 24;
                LOG_STUFF(1,
                        "[Tag] debug:" + __FILE__
                                + " value = " + value
                                + "some " + "more "
                                + "text");
            }
        }
    }
}
```
I.e. the tail operands still remain aligned to the first operand with the `ContinuationIndentWidth: 8`. However the whole function argument is placed on its own row for that reason. While `AlignOperands: Align` produces a bit more compact result.
