### ISSUE TITLE
clang-format produces `#if(abc && def) || ghi`

### ISSUE THREAD

**Issue by nabijaczleweli** [llvm/llvm-project#81569]
I get
```cpp
#if(__linux__ && !__GLIBC__) || __OpenBSD__  // cpuid
```
with config
```yaml
---
Language                                       : Cpp
BasedOnStyle                                   : LLVM
AlignAfterOpenBracket                          : true
AlignEscapedNewlinesLeft                       : true
AlignConsecutiveAssignments                    : true
AllowShortFunctionsOnASingleLine               : Inline
AlwaysBreakTemplateDeclarations                : true
ColumnLimit                                    : 160
ConstructorInitializerIndentWidth              : 6
IndentCaseLabels                               : true
MaxEmptyLinesToKeep                            : 2
KeepEmptyLinesAtTheStartOfBlocks               : false
NamespaceIndentation                           : All
PointerAlignment                               : Middle
SpacesBeforeTrailingComments                   : 2
IndentWidth                                    : 2
TabWidth                                       : 2
UseTab                                         : ForIndentation
SpaceBeforeParens                              : Never
FixNamespaceComments                           : false
...
```
on 1:19.0-58\~exp2+0~20240125133033.7\~1.gbp0cd83c.

I think it's obvious it should not be like that, and it should just be
```cpp
#if (__linux__ && !__GLIBC__) || __OpenBSD__  // cpuid
```
and match all the other `#if`s.
