### ISSUE TITLE
[clang-format] Reflowing macros sometimes erroneously removes backslashes, causing compilation to fail. 

### ISSUE THREAD

**Issue by BenoitLabrique-EH** [llvm/llvm-project#82618]
Using the configuration file below, applying clang-format to:

```
#define DEFINE_COMMAND_PROCESS_TABLE(Enum) \
    const STExample TCommand::EXPL_MAIN[] = { \
        {Enum::GetName(), "shows help"} \
    };
```

results in

```
#define DEFINE_COMMAND_PROCESS_TABLE(Enum)    \
    const STExample TCommand::EXPL_MAIN[] = { \
        {Enum::GetName(), "shows help"}
    };
```
which is obviously wrong because the last \ has been removed, causing the subsequent compilation to fail.

Clang-Format version is 17.0.6
The configuration I'm using is the following:

```yaml
---
Language: Cpp
Standard: c++20

AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments:
  Enabled:       true
  AlignCompound: true
  PadOperators:  false
AlignConsecutiveBitFields: AcrossEmptyLines
AlignConsecutiveDeclarations: Consecutive
AlignConsecutiveMacros: Consecutive
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments: Always
AllowAllArgumentsOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine : None
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None # DEPRECATED
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: Yes
AttributeMacros:
  - __capability
  - __packed
BinPackArguments: true
BinPackParameters: true
BitFieldColonSpacing: Both
BraceWrapping:
  AfterCaseLabel:        true
  AfterClass:            true
  AfterControlStatement: Always
  AfterEnum:             true
  AfterFunction:         true
  AfterNamespace:        true
  AfterObjCDeclaration:  true
  AfterStruct:           true
  AfterUnion:            true
  AfterExternBlock:      true
  BeforeCatch:           true
  BeforeElse:            true
  BeforeLambdaBody:      true
  BeforeWhile:           false
  IndentBraces:          false
  SplitEmptyFunction:    true
  SplitEmptyRecord:      true
  SplitEmptyNamespace:   true
BreakAfterJavaFieldAnnotations: false
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Custom
BreakBeforeConceptDeclarations: true
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeComma
BreakInheritanceList: AfterComma
BreakStringLiterals: true
BreakConstructorInitializersBeforeComma: true
ColumnLimit: 120
CommentPragmas: ^!<|^/<|^lint
CompactNamespaces: false
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DeriveLineEnding: false
DerivePointerAlignment: false
DisableFormat:   false
EmptyLineBeforeAccessModifier: LogicalBlock
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: false
ForEachMacros:
  - foreach
  - Q_FOREACH
  - BOOST_FOREACH
  - FOR_ALL
  - FOR_ALL_COND
IncludeBlocks: Preserve
IncludeCategories:
  - Regex:           '^"(llvm|llvm-c|clang|clang-c)/'
    Priority:        2
    SortPriority:    0
    CaseSensitive:   false
  - Regex:           '^(<|"(gtest|gmock|isl|json)/)'
    Priority:        3
    SortPriority:    0
    CaseSensitive:   false
  - Regex:           '.*'
    Priority:        1
    SortPriority:    0
    CaseSensitive:   false
IncludeIsMainRegex: '(Test)?$'
IncludeIsMainSourceRegex: ''
IndentCaseBlocks: true
IndentCaseLabels: false
IndentExternBlock: AfterExternBlock
IndentGotoLabels: false
IndentPPDirectives: BeforeHash
IndentWidth: 4
IndentWrappedFunctionNames: true
InsertTrailingCommas: None
JavaScriptQuotes: Leave
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: true
MacroBlockBegin: ''
MacroBlockEnd:   ''
MaxEmptyLinesToKeep: 2
NamespaceIndentation: All
ObjCBinPackProtocolList: Auto
ObjCBlockIndentWidth: 4
ObjCBreakBeforeNestedBlockParam: true
ObjCSpaceAfterProperty: false
ObjCSpaceBeforeProtocolList: false
PenaltyBreakAssignment: 0
PenaltyBreakBeforeFirstCallParameter: 0
PenaltyBreakComment: 60
PenaltyBreakFirstLessLess: 120
PenaltyBreakString: 1000
PenaltyBreakTemplateDeclaration: 0
PenaltyExcessCharacter: 1000000
PenaltyIndentedWhitespace: 0
PenaltyReturnTypeOnItsOwnLine: 200
PointerAlignment: Middle
ReflowComments: false
SortIncludes: Never
SortJavaStaticImport: Before
SortUsingDeclarations: Lexicographic
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: true
SpaceAroundPointerQualifiers: Default
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeCpp11BracedList: true
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: Custom
SpaceBeforeParensOptions:
  AfterControlStatements:       true
  AfterForeachMacros:           true
  AfterFunctionDeclarationName: false
  AfterFunctionDefinitionName : false
  AfterIfMacros:                true
  AfterOverloadedOperator :     false
  AfterRequiresInClause:        true
  AfterRequiresInExpression:    true
  BeforeNonEmptyParentheses:    false
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: false
SpacesBeforeTrailingComments: 2
SpacesInAngles: Never
SpacesInConditionalStatement: false
SpacesInContainerLiterals: false
SpacesInSquareBrackets: false
StatementAttributeLikeMacros:
  - Q_EMIT
  - emit
StatementMacros:
  - Q_UNUSED
  - QT_REQUIRE_VERSION
TabWidth: 4
UseTab:   Never
WhitespaceSensitiveMacros:
  - STRINGIZE
  - PP_STRINGIZE
  - BOOST_PP_STRINGIZE
  - NS_SWIFT_NAME
  - CF_SWIFT_NAME
AlignArrayOfStructures: Left
EmptyLineAfterAccessModifier: Never
IfMacros:
  - KJ_IF_MAYBE
IndentAccessModifiers: false
LambdaBodyIndentation: Signature
PPIndentWidth: -1
ReferenceAlignment: Pointer
ShortNamespaceLines: 1
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: -1
PackConstructorInitializers: Never
PenaltyBreakOpenParenthesis: 100
QualifierAlignment: Leave # Setting to something other than Leave, COULD lead to incorrect code formatting
SeparateDefinitionBlocks: Always
IndentRequiresClause: true
InsertBraces: false # warning: setting to true is unstable!
RequiresClausePosition: OwnLine
BreakAfterAttributes: Always
BreakArrays: false
InsertNewlineAtEOF: true
LineEnding: LF
RemoveSemicolon: false # warning: setting to true is unstable!
RequiresExpressionIndentation: OuterScope
KeepEmptyLinesAtEOF: false
RemoveParentheses: Leave # warning: setting to != Leave is unstable!
SpacesInParens: Never # set to Custom to let SpacesInParensOptions it
SpacesInParensOptions:
  InConditionalStatements: false
  InCStyleCasts:           false
  InEmptyParentheses:      false
  Other:                   false

...
```
