### ISSUE TITLE
[clang-format] Possible lack of indentation when a multi-line string is passed as an argument to a function

### ISSUE THREAD

**Issue by Tamaranch** [llvm/llvm-project#91360]
With
```yaml
Language: Cpp

AlignAfterOpenBracket: Align
BreakStringLiterals: true
ContinuationIndentWidth: 2
IndentWidth: 2
```
this code is left as is:
```c
f ("str1"
   "str2",
   arg2);
```
Shouldn't it be indented as follows:
```c
f ("str1"
     "str2",
   arg2);
```
This is usually done when an argument extends over several lines, to clearly separate this argument from the others. For example:
```c
f (a
     + b,
   arg2);
```
