### ISSUE TITLE
[clang-format] AllowShortFunctionsOnASingleLine not respected if BraceWrapping AfterFunction

### ISSUE THREAD

**Issue by Tamaranch** [llvm/llvm-project#91792]
With
```yaml
Language: Cpp
BasedOnStyle: GNU
```
this code
```c
void
f () { return; }
```
is formatted as
```c
void
f ()
{
  return;
}
```
Setting
```yaml
Language: Cpp
BasedOnStyle: GNU
BraceWrapping:
  AfterFunction: false
BreakBeforeBraces: Custom
```
"fixes" the issue.

version: 17.0.6 and 19.0.0_r498302.fa4e8995cb6b
