### ISSUE TITLE
Wrong formatting of labels in preprocessor lines

### ISSUE THREAD

**Issue by Julien-Elie** [llvm/llvm-project#92300]
Contrary to previous versions, clang-format 18 reformats:

```
#    define TXN_START(label, tid) \
    label:                        \
        TXN_START_NORETRY(label, tid)

#    define failure_response           \
    failure:                           \
        simple_response(client, code); \
        break;
```

as:

```
#    define TXN_START(label, tid) label : TXN_START_NORETRY(label, tid)

#    define failure_response                     \
        failure : simple_response(client, code); \
        break;
```

I don't think it is the expected output.  Previous versions of clang-format kept it unchanged.  It looks like `:` is now interpreted as a colon in a ternary operation instead of a colon following a label name.

**Comment by Julien-Elie** [comment]
Incidentally, I'm wondering whether the first example wouldn't be better with a formatting like:

```
#    define TXN_START(label, tid)     \
    label:                            \
        TXN_START_NORETRY(label, tid)
```

**Comment by owenca** [comment]
> Previous versions of clang-format kept it unchanged.

Which version(s)? And what's your .clang-format file?

**Comment by Julien-Elie** [comment]
Hi @owenca, thanks for having taken a look at this bug report.  I see that you even already provided fixes.  Thanks!

FWIW, my `.clang-format` is:

```
Language: Cpp
BasedOnStyle: LLVM
AlignArrayOfStructures: Left
AlignConsecutiveMacros: AcrossEmptyLinesAndComments
AlignEscapedNewlines: Left
AllowShortEnumsOnASingleLine: false
AlwaysBreakAfterReturnType: AllDefinitions
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: WebKit
ColumnLimit: 79
IncludeCategories:
    - Regex: '^"(config.h|portable/system.h)"'
      Priority: 0
IndentPPDirectives: AfterHash
IndentWidth: 4
IndentWrappedFunctionNames: false
MaxEmptyLinesToKeep: 2
SpaceAfterCStyleCast: true
```

The previous version I was using is Clang 17.0.6 which had not the issue, nor versions 16, 15, 14, etc. (but I do not remember the exact releases I used for them).
