### ISSUE TITLE
clang-format: Inserts unwanted newlines in template <typename...> typename class template

### ISSUE THREAD

**Issue by cvigue** [llvm/llvm-project#93793]
Desired format:

```
template <template <typename...> typename Xxx,
          template <typename...> typename Yyy,
          typename... T>
class A
{
};

```

Actual format: 

```
template <template <typename...> typename Xxx,
          template <typename...>
          typename Yyy,
          typename... T>
class A
{
};
```

My .clang-format:

```
BasedOnStyle: Microsoft
ColumnLimit: 0
SortIncludes: Never
BreakBeforeBinaryOperators: All
BinPackArguments: False
BinPackParameters: False
LambdaBodyIndentation: OuterScope
IndentCaseBlocks: true
MaxEmptyLinesToKeep: 3
BraceWrapping:
  AfterNamespace: false
  AfterCaseLabel: true
  BeforeLambdaBody: true

```

Using clang-format 14
