### ISSUE TITLE
[clang-format] SpaceAfterCStyleCast doesn't work with braced initializer list

### ISSUE THREAD

**Issue by Avnzx** [llvm/llvm-project#96096]
```c
struct pos pos_minus(const struct pos pt) {
    return (struct pos){.x=-pt.x, .y=-pt.y};
}
``` 

Is the result given this config file, while the option would suggest that there should be a space between the `)` and `{`:

```yaml
---
BasedOnStyle:    LLVM
IndentWidth:     4
UseCRLF:         false
UseTab:          Never
---
Language: Cpp
PointerAlignment: Right
AllowShortEnumsOnASingleLine: false
AllowShortIfStatementsOnASingleLine: Never
InsertBraces: true
AllowShortFunctionsOnASingleLine: None
SpaceAfterCStyleCast: true
...
```

```bash
$ clang-format --version
clang-format version 17.0.6
````
