### ISSUE TITLE
[clang-format] pragmas are considered hashes in IndentPPDirectives

### ISSUE THREAD

**Issue by zeule** [llvm/llvm-project#97891]
When IndentPPDirectives is set to AfterHash, placing `#pragma once` at the beginning of the include file make all `#include` directives indented.

**Comment by owenca** [comment]
Please provide the version and config of clang-format and the code snippet you used.

**Comment by zeule** [comment]
Oops, sorry: llvm 18.1.8

.clang-format:
```yaml
---
# We'll use defaults from the LLVM style, but with 4 columns indentation.
BasedOnStyle: LLVM
Language: Cpp
TabWidth: 4
UseTab: AlignWithSpaces
IndentWidth: 4

IndentPPDirectives: AfterHash
```

In a fragment:
```c++
#pragma once
#ifndef HEADER_ID_H
#define HEADER_ID_H // (1)
```
clang-format inserts indent in (1) after the hash sign
