### ISSUE TITLE
When breaking on ternary operators with AlignOperands set, continuation indent is also added

### ISSUE THREAD

**Issue by kelnos** [llvm/llvm-project#98559]
Config:

```yaml
Language: Cpp
BasedOnStyle: LLVM
AlignOperands: Align  # default implied by LLVM style, but similar issue with AlignAfterOperator set instead
BreakBeforeTernaryOperators: true  # default implied by LLVM style
ContinuationIndentWidth: 4  # default implied by LLVM style

# Not strictly necessary to repro, but makes it easy to repro without having long lines
ColumnLimit: 0
# Not necessary for repro, but illustrates that binary operator alignment is handled differently
BreakBeforeBinaryOperators: NonAssignment
```

The following code (as typed):

```c
int foo = bar > baz
  ? 42
  : 99;
```

Gets reformatted to:

```c
int foo = bar > baz
              ? 42
              : 99;
```

It looks like what's happening is that it's first aligning the `?` and `:` underneath the "b" in `bar` as per `AlignOperands`, but then it also adds four more spaces per `ContinuationIndentWidth`.

The four extra spaces are undesirable, and would seem to contradict the documentation.  What I expect to see:

```c
int foo = bar > baz
          ? 42
          : 99;
```

Setting `ContinuationIndent` to `0` "fixes" the problem, but of course gives undesirable formatting in all the other places where continuation indents are used.

Note that *binary* operators are handled how I would consider correctly (after formatting):

```c
int biff = foo
           + bar
           + baz;
```
